### ISSUE TITLE
rxjs-compat NOT automatically installed

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#10631]
Per the paragraph on the announcement blog page:

> For example, the command ng update @angular/core will update all of the Angular framework packages as well as RxJS and TypeScript, and will run any schematics available on these packages to keep you up to date. As part of this one command, we’ll automatically install rxjs-compat into your application to make the adoption of RxJS v6 smoother.

However, after running the ng upgrade commands, rxjs-compat was NOT automatically installed. When I ran my app, there were several errors related to rxjs

```
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
src/app/students/students.component.ts(2,10): error TS2305: Module '"/Users/john/Dev/DotNet/TimeTracker/node_modules/rxjs/Observable"' has no exported member 'Observable'.
src/app/students/students.service.ts(3,10): error TS2305: Module '"/Users/john/Dev/DotNet/TimeTracker/node_modules/rxjs/Observable"' has no exported member 'Observable'.
```
### Versions
```
Angular CLI: 6.0.0
Node: 10.0.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* Update an existing app, per directions on update.angular.io

### Observed behavior

rxjs-compat was not added to package.json automatically

### Desired behavior
Per the docs, rxjs-compat should have been installed.

**Comment by shkarab** [comment]
same issues here

**Comment by CanKer** [comment]
same here

**Comment by exavior75** [comment]
Same here.

**Comment by ivancas84** [comment]
same

**Comment by ElisePatrikainen** [comment]
Same - I tried to run as well ng update rxjs, but it did not add rxjs-compat to the package.json, neither added it to the npm list.

**Comment by Group10Chennai** [comment]
I too have the same issue but resolved by

npm install rxjs-compat@6.0.0-tactical-rc.1

**Comment by sreeksp** [comment]
@here removing rxjs-compat after the migration still throw the same error

**Comment by yogeshpatil143** [comment]
npm i rxjs-compat

Add these on o your root folder

**Comment by clydin** [comment]
`rxjs-compat` should not longer be needed.  However if this issue is still occurring for anyone, the `rxjs` package itself contains the necessary migrations to install the `rxjs-compat` package.  Please open an issue with `rxjs` if the update migrations are not being properly executed when updating from a pre-6.0 version of rxjs to a new version via the `ng update` command.
