### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by JimInWoodstock** [angular/angular-cli#1071]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10
2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
v6.1.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

unzipped the angular-cli zip file into "e:\Angular2 Projects\clitool"
e:
cd \Angular2 Projects\clitool
Installed angular-cli using the command "npm install -g angular-cli"
issued the command "ng new testproj" which gave errors. Log file is attached.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
[log.txt](https://github.com/angular/angular-cli/files/311015/log.txt)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by hmrc87** [comment]
* delete dist and tmp folder in your project folder

* Try doing all the cmd-work within a Shell (eg. Powershell) with admin-rights 
https://stackoverflow.com/questions/7690994/powershell-running-a-command-as-administrator

* Update your NPM with npm update

**Comment by filipesilva** [comment]
Closed as an abandoned issue. Seems to have been a broken install and @hmrc87's instructions should solve it.

**Comment by hussainwali74** [comment]
@filipesilva  sir please help:
according to the instructions of @hmrc87 I tried to delete the dist and temp folder but I don't have them in my project folder I still get the error no matter whichever project I am working in the cli gives me the same error **cannot find module 'chalk' **

**Comment by filipesilva** [comment]
@hussainwali74 those instructions were for an old version of Angular CLI that had a different structure. 

In your case please make sure you are using the `@angular/cli` package, delete the `node_modules` folder in your project and reinstall.

If you are updating from an old version of the cli (when the package was called `angular-cli` instead), have a look at https://github.com/angular/angular-cli/wiki/stories-1.0-update for update instructions.
