### ISSUE TITLE
ng update fails on self signed certificate in certificate chain

### ISSUE THREAD

**Issue by acostaf** [angular/angular-cli#10871]
### Versions
Angular CLI: 6.0.1
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.1
@angular-devkit/core         0.6.1
@angular-devkit/schematics   0.6.1
@schematics/angular          0.6.1
@schematics/update           0.6.1
rxjs                         6.1.0
typescript                   2.7.2

### Repro steps
ng update 

### Observed behavior
fails and displays "self signed certificate in certificate chain"

### Mention any other details that might be useful (optional)

I also run it using the below list and still getting the same issue
npm config set strict-ssl false
npm install npm -g --ca NULL
ng update --skip-install

**Comment by Brocco** [comment]
Closing... This was addressed in this PR angular/devkit#838 and will be included in the next release.

**Comment by acostaf** [comment]
@Brocco will this be fixed on 6.0.2 ?

**Comment by tommck** [comment]
Has this been released yet?  I'm still getting this error today
