### ISSUE TITLE
Installing angular-cli latest issue

### ISSUE THREAD

**Issue by HackPoint** [angular/angular-cli#1209]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. Mac OSX (El Capitan)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
 `module.js:442
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/angular-cli/node_modules/leek/lib/leek.js:3:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
`

3. Tryed to install the angular-cli latest version

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`118045 verbose stack Error: ENOENT: no such file or directory, rename '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/.staging/abbrev-2f33b7c6' -> '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
118045 verbose stack     at destStatted (/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
118045 verbose stack     at FSReqWrap.oncomplete (fs.js:117:15)
118045 verbose stack
118045 verbose stack Error: ENOENT: no such file or directory, rename '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/.staging/abbrev-2f33b7c6' -> '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
118045 verbose stack     at Error (native)
118046 verbose cwd /Users/gena/ironbuzz/private/super-fitness
118047 error Darwin 15.5.0
118048 error argv "/Users/gena/.nvm/versions/node/v6.2.1/bin/node" "/Users/gena/.nvm/versions/node/v6.2.1/bin/npm" "i" "-g" "angular-cli"
118049 error node v6.2.1
118050 error npm  v3.9.3
118051 error path /Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/.staging/abbrev-2f33b7c6
118052 error code ENOENT
118053 error errno -2
118054 error syscall rename
118055 error enoent ENOENT: no such file or directory, rename '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/.staging/abbrev-2f33b7c6' -> '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
118056 error enoent ENOENT: no such file or directory, rename '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/.staging/abbrev-2f33b7c6' -> '/Users/gena/.nvm/versions/node/v6.2.1/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
118056 error enoent This is most likely not a problem with npm itself
118056 error enoent and is related to npm not being able to find a file.
118057 verbose exit [ -2, true ]`

> > Thanks! We'll be in touch soon.

**Comment by Foxandxss** [comment]
```
$ npm remove -g angular-cli
$ npm cache clean
$ npm install -g angular-cli
```

That should fix it.

**Comment by Splaktar** [comment]
That does seem to fix it, thank you.

Strange that with beta.8 installed, I'm still seeing this output:
```
ng --version
angular-cli: 1.0.0-beta.6
node: 4.4.3
os: darwin x64
```

**Comment by Splaktar** [comment]
This seems to be the same issue as #1186.

**Comment by Sangeethaself** [comment]
while installing @tangular/cli 

getting this following error 

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
--

**Comment by M4H3NDR4N** [comment]
while installing angular

got this error,

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-04-27T12_17_11_520Z-debug.log

**Comment by anupammaurya** [comment]
Uninstall node
Delete Angular folder from Appdata>>Roaming>>...

- restart
- npm i
- npm -g update npm
- npm uninstall -g @angular/cli angular/cli
- npm cache clean
- npm install -g @angular/cli
