### ISSUE TITLE
Weird behaviour w/ `ng --version`

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#12640]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Command (mark with an `x`)
```
- [x] version
```

### Versions
NG CLI:  7.0.1
OS: Linux Mint 19.1 (based on Ubuntu 18.04)
Angular: ^6.1.0

Have `ng` CLI 7.0.1 installed in `/opt/node-v10.12.0-linux-x64/bin`.
That directory is where `ng` is found.

## `ng --version` in an angular workspace, no `node_modules` present

`ng --version` gives:

```log
➜  ehb-ui-web.git git:(develop) ✗ ng --version
ENOENT: no such file or directory, scandir '[LOCAL DIRECDTORY]/node_modules'
Error: ENOENT: no such file or directory, scandir '[LOCAL_DIRECTORY]/node_modules'
    at Object.readdirSync (fs.js:783:3)
    at VersionCommand.run (/opt/node-v10.12.0-linux-x64/lib/node_modules/@angular/cli/commands/version-impl.js:48:41)
    at VersionCommand.validateAndRun (/opt/node-v10.12.0-linux-x64/lib/node_modules/@angular/cli/models/command.js:122:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
➜  ehb-ui-web.git git:(develop) ✗ 
```

Why does it matter whether `node_modules` is present ?

## `ng --version` not inside of an Angular project, it considers ${HOME}/angular.json !!

```
➜  Source ls -l
total 32
drwxr-xr-x  2 USER USER 4096 May  4 20:57 Codebase/
drwxr-xr-x  4 USER USER 4096 May  4 19:33 Curl/
drwxr-xr-x 17 USER USER 4096 Sep 29 17:19 XXXXX/
-rw-r--r--  1 USER USER 9895 May  4 19:33 XXXXX.sln
drwxr-xr-x  3 USER USER 4096 May  4 19:33 SicList/
drwxr-xr-x  3 USER USER 4096 May  4 19:33 Xerces/
➜  Source ng --version
An invalid configuration file was found ['$HOME/angular.json']. Please delete the file before running the command.
➜  Source                                                
```

Can this behaviour be switched off ?

### The log given by the failure

Logs are embedded above.

### Desired functionality

`ng --version` should just report the version configuration.
Otherwise it is going to be difficult to use it, say in shell scripts where there is no human interaction.

How about a switch somewhere along `--ignore-project-meta-files` ?

I get it.
During development, `ng` must find the one and only valid `angular.json` and mandate the presence of `node_modules` in the current working directory.

**Comment by hansl** [comment]
We don't use `angular.json` file in your home folder anymore. We use `.angular-config.json` instead to ensure this is not a problem anymore.

I'm going to close this as fixed in 7.

**Comment by beeman** [comment]
@hansl does not seem to be fixed, this still happens in directories that have a `package.json` but no `node_modules` folder.

The steps to reproduce:

```
cd /tmp
mkdir issue-12640
cd issue-12640
npm init -y
Wrote to /private/tmp/issue-12640/package.json:

{
  "name": "issue-12640",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Bram Borggreve <borggreve@gmail.com> (https://github.com/beeman)",
  "license": "MIT"
}

ng --version
ENOENT: no such file or directory, scandir '/private/tmp/issue-12640/node_modules'
Error: ENOENT: no such file or directory, scandir '/private/tmp/issue-12640/node_modules'
    at Object.readdirSync (fs.js:809:3)
    at VersionCommand.run (/usr/local/lib/node_modules/@angular/cli/commands/version-impl.js:48:41)
    at VersionCommand.validateAndRun (/usr/local/lib/node_modules/@angular/cli/models/command.js:124:31)
    at process._tickCallback (internal/process/next_tick.js:43:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:778:11)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
```
