### ISSUE TITLE
ng add @angular/pwa doesn't work correctly in angular-cli 6.2.5 (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by christianmorante** [angular/angular-cli#12914]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.2.5
Node: 8.11.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cdk                      6.4.7
@angular/cli                      6.2.5
@angular/material                 6.4.7
@angular/pwa                      0.10.5
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2

### Repro steps

ng new pwademo
ng add @angular/material
ng build --prod
ng add @angular/pwa

### The log given by the failure

Installing packages for tooling via npm.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/pwa@0.10.5
updated 1 package in 47.645s
Installed packages for tooling via npm.
Maximum call stack size exceeded

### Desired functionality

The command doesnt add automatically PWA features to my Angular application such as manifest file or icons in assets folder or edit my index.html file with reference to manifest, only show me the error message
**Maximum call stack size exceeded**

**Comment by clydin** [comment]
Currently you will need to execute `ng add @angular/pwa@6` to ensure the version compatible with Angular 6 is used.

**Comment by christianmorante** [comment]
I'm just running the command
`ng add @angular/pwa`

**Comment by jakawell** [comment]
I'm having the same issue. I was able to get it to work by specifying the last stable release:
`ng add @angular/pwa@0.8.7 --project my-project-name`

**Comment by christianmorante** [comment]
Oh hell, it worked for me. But is there any clue as to why?
Thanks @jakawell.

**Comment by jakawell** [comment]
I'm not sure. The latest version was just published recently, so I'm guessing something isn't quite right with it.

**Comment by alan-agius4** [comment]
The latest version is targeted to be used with Version 7.

**Comment by azaddjan** [comment]
No issue with bellow version. Update your cli.

`ng version
`

Angular CLI: 7.0.5
Node: 10.11.0
Angular: 7.0.3

**Comment by lukaszgodula** [comment]
I have the same issue with cli v7 and angular v7

**Comment by tsukhu** [comment]
> @0.8.7

I am using nx extensions v7 and angular 7.0.5 and ran into the same issue.
@jakawell thanks for your solution , that one works (using the older version/stable version of @angular/pwa@0.8.7)

**Comment by alan-agius4** [comment]
Hi, the problem is no longer reproducable if you use the latest versions of the CLI and devkit packages.

```
    "@angular-devkit/build-angular": "^0.10.5",
    "@angular/cli": "^7.0.5",
```

**Comment by igwemagnusnnamdi65** [comment]
@jakawell thanks so much.You rock.

**Comment by imen-developer** [comment]
it should be fixed by updating your global angular cli to the last stable version

**Comment by jcuervas** [comment]
"@angular-devkit/build-angular": "^0.10.5",
 "@angular/cli": "^7.0.5",
This worked for me also (in project package.json)

**Comment by IgorMinar** [comment]
The root cause here is that the @angular/pwa doesn't declare any peerDependency in the package.json config, so the npm client installs the latest one which doesn't seem to be compatible. To fix this we need to define a peerDep on the right version.

To fix this for v6 developers, we might need to cut a version that is compatible with v6 and declares a peerDep on v6.

**Comment by gkalpak** [comment]
`peerDependency` on what? Angular or cli/devkit?

**Comment by IgorMinar** [comment]
on the cli because it's the cli that provides schematics and other stuff needed by @angular/pwa

**Comment by gkalpak** [comment]
Makes sense.
I just want to point out that some parts (such as the `ngsw-config.json`) must be compatible with the `@angular/service-worker` version used. Maybe we should move them to `@angular/service-worker` and have cli somehow get them from there.

**Comment by IgorMinar** [comment]
since cli and the framework are aligned on major versions, it should be
fine to pin pwa to just cli. no?

**Comment by gkalpak** [comment]
If we only change things related to the `ngsw-config` in major versions, yes.

**Comment by marcobaccaro** [comment]
If you delete the node_modules folder it works fine.

**Comment by saurabhzh** [comment]
For my case I updated my angular CLI and then 'ng add @angular/pwa' is working fine.
To update Angular CLI in your project use:

npm uninstall --save-dev angular-cli
npm install --save-dev @angular/cli@latest

**Comment by alan-agius4** [comment]
Fixed via https://github.com/angular/angular-cli/pull/13286

**Comment by nreynis** [comment]
@alan-agius4 It's not fixed, can you please reopen the issue ?

Just updated to `@angular/cli:7.2.3` and the error is still here.
I've also deleted the node_modules directory and it still fails the same way.

I can't add pwa support to my project.

**Comment by cnscorpions** [comment]
> I'm having the same issue. I was able to get it to work by specifying the previous stable release:
> `ng add @angular/pwa@0.8.7 --project my-project-name`

it seems to work, thnk u

**Comment by HeydyCH** [comment]
@jakawell muchas gracias. Me funciono (y)
