### ISSUE TITLE
Incorrect scss file name generated

### ISSUE THREAD

**Issue by mwhitis** [angular/angular-cli#13764]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Has worked previously, but I don't know how long ago it regressed

### Description

 A clear and concise description of the problem...
Using cli 7.3.3

Generates src/styles.**scss**

Angular.json looking for src/styles.**sass**

## 🔬 Minimal Reproduction

ng new foo 
Y to angular routing
Change Stylesheet to SASS

ng serve

## 🔥 Exception or Error
<pre><code>

ERROR in multi ./src/styles.sass
Module not found: Error: Can't resolve '/Users/mwhitis/git/mwhitis/foo/src/styles.sass' in '/Users/m420498/git/mwhitis/foo'
ℹ ｢wdm｣: Failed to compile.
</code>
</pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.3
Node: 11.10.0
OS: darwin x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by mwhitis** [comment]
Added generated angular.json

[angular.json.txt](https://github.com/angular/angular-cli/files/2900997/angular.json.txt)

**Comment by alan-agius4** [comment]
I suspect that your global Angular CLI version is not the latest.

Can you install it and try again?

```cmd
npm install @angular/cli@latest -g
```

As this should have been solved by https://github.com/angular/angular-cli/pull/13552

**Comment by mwhitis** [comment]
Updated with the above command, and still getting the error.

**Comment by alan-agius4** [comment]
Hi, I looked into this and I was unable to reproduce the reported issue with the latest CLI.

```
npm install @angular/cli@latest -g
ng new foo
choose routing & sass
grep -r "styles" angular.json
            "styles": [
              "src/styles.scss"
            "styles": [
              "src/styles.scss"

```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
