### ISSUE TITLE
The analytics prompt shouldn't run in CI environments

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular-cli#14563]
# 🐞 Bug report

### Command (mark with an `x`)

```
npm install
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
v7 and below

### Description

When upgrading to v8 the analytics prompt breaks CI as it hangs infinitely waiting for the user to choose to enable it or not

## 🔬 Minimal Reproduction

Run npm install on a v8 cli project on CI. For example: https://travis-ci.org/mattlewis92/angular-calendar/builds/538499347

Attempting to disable analytics on the project then fails as the config it adds to angular.json is invalid
```
ng analytics project off
```

<img width="255" alt="Screenshot 2019-05-29 at 09 57 39" src="https://user-images.githubusercontent.com/6425649/58562951-40c47480-81f8-11e9-9174-edf551566d46.png">

## 🔥 Exception or Error
<img width="915" alt="Screenshot 2019-05-29 at 09 53 42" src="https://user-images.githubusercontent.com/6425649/58562659-aa904e80-81f7-11e9-893d-fe006518d688.png">

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0
Node: 12.1.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0
@angular-devkit/build-angular      0.800.0
@angular-devkit/build-ng-packagr   0.800.0
@angular-devkit/build-optimizer    0.800.0
@angular-devkit/build-webpack      0.800.0
@angular-devkit/core               8.0.0
@angular-devkit/schematics         8.0.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0
@schematics/angular                8.0.0
@schematics/update                 0.800.0
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

The `is-ci` package could be used to disable that prompt on CI envs: https://www.npmjs.com/package/is-ci

The `analytics` config needs to be added to the schema so it can be disabled at the project level

The workaround for now is to add this to travis.yml
```
before_install: npx @angular/cli analytics off
```

**Comment by mgechev** [comment]
You can set [this flag](https://github.com/angular/angular-cli/blob/f8fe4b0ee82d880396119a2594f3cee8dadb2947/docs/design/analytics.md#disabling-usage-analytics) in your CI to disable the analytics. We'll work on fixing this in the next patch release.

**Comment by mattlewis92** [comment]
Awesome, thanks @mgechev! btw it might be worth documenting the `NG_CLI_ANALYTICS` variable here: https://angular.io/analytics

**Comment by cyrilletuzi** [comment]
I also have this issue. For info: it appeared during the CLI beta phase, then was fixed (it was OK in CLI v8.0.0-rc.4), and is here again in v8.0.0, so a commit between v8.0.0-rc.4 and 8.0.0 reintroduced this issue.

**Comment by tiffanychenn** [comment]
This still seems to be a problem for me. I'm using v8.0.6 and I get this same issue when I try npm installing in my pipeline. I'm building using fly. Screenshot of result below. 
![Screen Shot 2019-07-02 at 9 39 36 AM](https://user-images.githubusercontent.com/15021515/60517521-d34fac00-9cad-11e9-9afb-dcd95ea9ef9f.png)

**Comment by tiffanychenn** [comment]
Still having this issue. I'm currently using v8.0.6 and building on concourse's CI. See screenshot below.

![Screen Shot 2019-07-02 at 9 39 36 AM](https://user-images.githubusercontent.com/15021515/60521479-5a545280-9cb5-11e9-8dd1-be4c0b3322c0.png)

**Comment by trazek** [comment]
> Still having this issue. I'm currently using v8.0.6 and building on concourse's CI. See screenshot below.
> 
> ![Screen Shot 2019-07-02 at 9 39 36 AM](https://user-images.githubusercontent.com/15021515/60521479-5a545280-9cb5-11e9-8dd1-be4c0b3322c0.png)

The issue above is taking place when the CI process is installing dependencies. We have tried flipping an env variable to have the CLI not prompt this message with no luck
