### ISSUE TITLE
Missing angular-cli-build.js in 1.0.0-beta.11-webpack

### ISSUE THREAD

**Issue by serhiisol** [angular/angular-cli#1566]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
```
Mac OS X El Capitan 10.11.6
```

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
```
angular-cli: 1.0.0-beta.11-webpack
node: 6.3.1
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
```
$ ng new webpack-test
$ ng serve
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
⇒  ng serve
(node:10190) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
Error: No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/serhiysolonko/Development/Playground/wepback-test/node_modules/angular-cli/lib/models/builder.js:57:13)
    at Class.module.exports.Task.extend.init (/Users/serhiysolonko/Development/Playground/wepback-test/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/serhiysolonko/Development/Playground/wepback-test/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/serhiysolonko/Development/Playground/wepback-test/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/serhiysolonko/Development/Playground/wepback-test/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/serhiysolonko/Development/Playground/wepback-test/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/serhiysolonko/Development/Playground/wepback-test/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/serhiysolonko/Development/Playground/wepback-test/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/serhiysolonko/Development/Playground/wepback-test/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

PS. https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition - doesn't exist 😄

**Comment by mmgyce** [comment]
Did you type ```ng --version``` inside the webpack-test directory? I had the same error yesterday, I think when you create a new app with ```ng new myApp``` the angular-cli version installed locally is not the 1.0.0-beta.11-webpack version.

**Comment by NejcZdovc** [comment]
@serhiisol try following:

```
npm cache clean
npm install --save-dev angular-cli@webpack
```

**Comment by serhiisol** [comment]
the problem is that cli doesn't create this file at all. before I even run it, it doesn't exist

**Comment by serhiisol** [comment]
@NejcZdovc Why should I do that, if I have latest version of *beta.11-webpack* installed

**Comment by NejcZdovc** [comment]
@serhiisol you have it on global level, but probably not on local level. File angular-cli-build.js was used with systemjs.

**Comment by NejcZdovc** [comment]
You can check it here #1528

**Comment by serhiisol** [comment]
Everything installed from package.json, it has to be with correct versioning. I believe something is missing on cli side. Cause project is clean and it should just run.

**Comment by NejcZdovc** [comment]
@serhiisol You can check it here also [explanation](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md#local-project-package)

**Comment by itsmeprasanjit** [comment]
ng init did the trick but there is definately some bugs.

**Comment by serhiisol** [comment]
Ok, basically removing ^ from package.json
```
"angular-cli": "1.0.0-beta.11-webpack"
```

does trick, but that's not obvious at all, why npm installs incorrect angular-cli, it seems like without it, it installs another incompatible version.

**Comment by itsmeprasanjit** [comment]
npm install --save-dev angular-cli@webpack 👍

**Comment by serhiisol** [comment]
that's also not obvious at all 😄

**Comment by hansl** [comment]
This has been fixed already and is included in the nexrt release today or tomorrow.

**Comment by cmermingas** [comment]
I didn't know my commit in my little learning project would show up here just because I mentioned this issue for my own reference :)

Anyway, I followed the instructions [here](https://github.com/angular/angular-cli/blob/5ea4b03b6e47d8eef1ef0e64d6a37368b64f1672/WEBPACK_UPDATE.md) to install and create a project from scratch. I also followed the recommendations above: npm cache clean *inside the project*, then removed the caret (^) from package.json, reran npm install. But I still get this error when running `ng github-pages:deploy`

**Comment by srivasrk** [comment]
@cmermingas . I am facing the same issue. I have tried npm install --save-dev angular-cli@webpack. Also removed the crate in package.json.
Don't know whats wrong. Been a long day already.
**ng github-pages:deploy still throws the error: "no angular cli-build.js found"**

**Comment by srivasrk** [comment]
I am new to github, and I didn't realize this issue was already closed. Excuse my ignorance. @cmermingas We should probably log a new issue.

**Comment by stefanaerts** [comment]
same problem for me with angular-cli@1.0.0-beta.11-webpack.2
--steps ---------------
1) ng new 'projectname' ,
2) create repo on github 
3) git commit -m 'initial commit with angular-cli generated code' 
4) git push -u origin master 
5) ng github-pages:deploy
-----------------------
ng github-pages:deploy throws the error: "no angular cli-build.js found"

**Comment by stefanaerts** [comment]
and i did all of it, install angular-cli local puts ^ in front but that doesnt work.
Then i changed the local package.json again with ^ removed, but still the same error.
i did npm install and repeated all the steps again, still the same error.
So it would be very nice if somebody of the angular-cli developers can explain whats going on. Thx.

**Comment by filipesilva** [comment]
@cmermingas @srivasrk @stefanaerts there was a separate problem affecting the github deploy functionality that has been fixed in https://github.com/angular/angular-cli/pull/1633 and is pending release.

**Comment by ReneVallecillo** [comment]
I'm getting this error too.

**Comment by elvirdolic** [comment]
This error is still not fixed

with   "angular-cli": "^1.0.0-beta.11-webpack.8", by build server fails

without it works

**Comment by Blak3Nick** [comment]
I had to install awesome-typescript-loader as a dev dependency after running 
 npm install --save-dev angular-cli@webpack. Finally got  the project up and running again.

**Comment by pomeara** [comment]
I'm having this problem today, the angular-cli seems like a great idea but continues to have numerous bugs

**Comment by serhiisol** [comment]
Guys, this ticket already closed due to new releases of cli (for instance with beta 16 everything works as it should)

PS. Try to update to latest, should help

**Comment by sutin1234** [comment]
where angular-cli-build.json: in project angular-cli
