### ISSUE TITLE
Source Code showed in Browser Developer Tools is showing instrumented source code.

### ISSUE THREAD

**Issue by abner** [angular/angular-cli#1798]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: local (v1.0.0-beta.11-webpack.2, branch: master)
node: 6.3.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

When trying to debug my tests the source code mapped is showing illegible because of the instrumented code needed for the coverage report feature.

As seen in the screenshot bellow:

![](https://cloud.githubusercontent.com/assets/42773/17584436/deb216c0-5f8c-11e6-8985-f1c34d8552bf.png)

I think we could have an argument `debug` which we would pass to the ng test task which will not run the coverage config parts and, this way, debug will be possible.

I already have this implemented here and will submit a merge request for that.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We had an issue with sourcemaps but it should be solved in the next release (or in master if you want to try). If not, please tell me so I can reopen this issue.

**Comment by abner** [comment]
I just tried It on master and it is not solved. It's  related to instrumentation. The only way i think we have to solve this is to have an option to turn of the instrumentation, like I proposed with the debug argument on test tasks in the pull request.

**Comment by rubaomin** [comment]
I had a similar problem. My version is "angular-cli: 1.0.0-beta.11-webpack.2". 
When ran the command "ng serve" an hour to another, debug crashed. 
I was many hours doing everything changed browser, IDEs, did a master reset on the node modules and nothing resolved.
After much research, I found an open question in "webpack" and was resolved with 'devtool: '#inline-source-map'in the settings.
So I searched the angular-cli sources to see if something tracked. 
I found that the setting "devtool" in the files used in the dev environment (not production) in "..\node_modules\angular-cli\addon\ng2\models\" were configured with "devtool: 'inline-source-map" except one, "webpack-build-development.ts".
This was the setting "devtool: 'cheap-module-source-map'" and changed it to "devtool: 'inline-source-map'" to try 'ng serve' and it worked.
The "ng serve" returned to debug in a way (with sourcemaps generated correctly).
I do not know why it was that setting, but until that is resolved by the team the right way, is my tip.
I hope I can help someone not to lose hours like me just trying to debug my project that stopped working debug an hour to another.
:D

**Comment by abner** [comment]
This does not occurred to me using master angular-cli. The latest version published in npm is old and may have this issue. Try install angular-cli form master and create a app. After that change the package.json updating the angular-cli dependency to point to github master also (check the revision number and use the same version) of the angular-cli installed globally.

**Comment by filipesilva** [comment]
@abner so is this fixed for you?

**Comment by abner** [comment]
no @filipesilva . it isn't fixed.

**Comment by adstep** [comment]
I am still seeing this issue.

1. OS? Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run ng --version. If there's nothing outputted, please run
in a Terminal: node --version and paste the result here:
1.0.0-beta.17

**Comment by chadbr** [comment]
Same here - beta.17 on mac... can't debug through source from spec's

**Comment by theBull** [comment]
@filipesilva thanks for the merge! Just to clarify, since I'm not sure where to look for documentation around this new feature of toggling code coverage and linting, the following would be how to disable code coverage from the karma tests, correct?

```
ng test --code-coverage=false
```

**Comment by mdanetzky** [comment]
Angular cli 1.1.1
```
ng new debugtest
cd debugtest
ng test
```
in the browser -> Debug -> developer tools / sources -> cmd+p -> 
cannot find app.component.ts!

**Comment by filipesilva** [comment]
We seem to have a regression in unit test sourcemaps, investigating in https://github.com/angular/angular-cli/issues/6583.
