### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Emulated' of undefined

### ISSUE THREAD

**Issue by edcarroll** [angular/angular-cli#1948]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 Pro x64
Build 14393.rs1_release_inmarket.160819-1924

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: local (v1.0.0-beta.11-webpack.8, branch: master)
node: 6.3.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
$ ng new
Upgrade to rc.6
$ ng serve
Error appears when opening in browser

4. The log given by the failure. Normally this include a stack trace and some
   more information.
config.js:15Uncaught TypeError: Cannot read property 'Emulated' of undefinedCompilerConfig @ config.js:15(anonymous function) @ compiler.js:75__webpack_require__ @ bootstrap 76af11c…:52(anonymous function) @ main.bundle.js:50229__webpack_require__ @ bootstrap 76af11c…:52(anonymous function) @ main.bundle.js:13600__webpack_require__ @ bootstrap 76af11c…:52(anonymous function) @ main.bundle.js:56646__webpack_require__ @ bootstrap 76af11c…:52(anonymous function) @ main.bundle.js:56624__webpack_require__ @ bootstrap 76af11c…:52(anonymous function) @ version.js:1__webpack_require__ @ bootstrap 76af11c…:52(anonymous function) @ main.bundle.js:67347__webpack_require__ @ bootstrap 76af11c…:52webpackJsonpCallback @ bootstrap 76af11c…:23(anonymous function) @ main.bundle.js:1

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by edcarroll** [comment]
package.json dependencies:
```json
{
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/compiler-cli": "0.6.0",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.17"
}
```

**Comment by gelliott181** [comment]
Angular-CLI does not yet work with Angular 2 RC6. See #1937 and the latest comments in #1901

**Comment by hassanasad** [comment]
Please try updating to Node 6.5.0 - that seemed to fix issues for lots of people. Not sure about Windows machine though.

**Comment by GregOnNet** [comment]
Hi @hassanasad ,

updating NodeJS had no effect on my machine.
Can you explain why NodeJS and the compilation process could be related.

**Comment by churchilllake** [comment]
In the report, I suggest a specific line causing the problem.

**Comment by slyedoc** [comment]
reverted to es5, no issues.

in es6, didn't seem to see the import for ViewEncapsulation correctly, closure had __WEBPACK_IMPORTED_MODULE_0__angular_core__ instead of ViewEncapsulation, don't know enough enough about import to know if this is normal

**Comment by charlieamer** [comment]
Hi @slyedoc can you please briefly explain how you "reverted to es5", because i am having the same issue right now, and i am new to angular 2. Thanks.

**Comment by ronzeidman** [comment]
I'm not using angular-cli (using webpack directly) and I've encountered the same issue. Verifying that I have the right versions of node/npm/typescript didn't help, the only thing that solved it is changing the tsconfig `"module": "es6", --> "module": "commonjs",`
I'm writing this here since google sends people searching for "Cannot read property 'Emulated' of undefined" here.
This issue is weird since I have another project that works with the same configuration + es6 module, same machine and there are no issues...
This is probably a webpack2 issue so someone probably should to open an issue there.

**Comment by kover** [comment]
This definitely helps.

**Comment by jtsom** [comment]
Good god.. I can't wait until all of the various moving pieces for Angular 2 get locked down - between fighting with AngularCLI versions, Typescript versions (can't use 2.0.2, that breaks, gotta lock it to 2.0.0), and Angular itself (RC6), trying to get a dev environment set up is an exercise in futility! (my company is looking into Angular 2 for it's next  dev platform, and having to say well there are all these issues just to get started, makes one want to look at other, more stable, platforms!)

**Comment by TheLarkInn** [comment]
### Listen up

😄 This issue was caused by webpack not being able to handle deep namespaced reexports appropriately (packages got rearranged for RC6) while trying to treeshake: [see #2953](https://github.com/webpack/webpack/issues/2953)

Updating to webpack@2.1.0-beta.22 will **solve this issue**. 

This issue is also **fixed on master for the CLI** [as of yesterday #2011](https://github.com/angular/angular-cli/pull/2011).

**Comment by TheLarkInn** [comment]
Fixed with #2011

**Comment by jtsom** [comment]
Yup. Shame trying to install master, using the directions 
`https://github.com/angular/angular-cli/tree/e20af2109ecd844bba4d64039fb31624afea6399#updating-angular-cli`
fail with all sorts of errors:

```
angular-cli@1.0.0-beta.11-webpack.8 C:\code\angular-cli
+-- UNMET PEER DEPENDENCY @angular/platform-server@^2.0.0-rc.6
+-- UNMET PEER DEPENDENCY typescript@2.0.2
+-- UNMET PEER DEPENDENCY webpack@2.1.0-beta.22
| `-- node-libs-browser@1.0.0
|   `-- crypto-browserify@3.11.0
|     `-- browserify-sign@4.0.0
|       `-- elliptic@6.3.1
|         `-- brorand@1.0.6
`-- UNMET PEER DEPENDENCY zone.js@^0.6.17

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.0 requires a peer of @angular/platform-server@^2.0.0-rc.6 but none was installed.
npm WARN @angular/core@2.0.0-rc.6 requires a peer of zone.js@^0.6.17 but none was installed.
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.
```

and yes I have typescript 2.0.2 installed:
`PS C:\code\angular-cli> tsc -v
Version 2.0.2`

Sigh. Now I have to clean up back to working state...

**Comment by mattma** [comment]
@TheLarkInn I am using the current master branch, generate a brand new "angular2" project, run `ng serve`, still get the same error. `config.js:15Uncaught TypeError: Cannot read property 'Emulated' of undefined`

I checked my `angular-cli` project dependency `webpack` is `beta.22`, but inside the newly generated project using angular-cli dependency `beta.8`. so it is still using `webpack beta 11`.

```
 ng serve
** NG Live Development Server is running on http://localhost:4200. **
3512ms building modules                 2ms add01521ms 882ms asset39ms emittinggHash: 4993f7e77698840ac956
Version: webpack 2.1.0-beta.21
```

Should you cut a new release like `angular-cli beta.9`, so it gets the latest `webpack 2.1.0-beta.22`? Or tried with installing local `webpack beta.22`, but it seems that it only takes from angular-cli internal webpack dependency

**Comment by richavyas** [comment]
Hi @TheLarkInn,
I updated my current project (running on rc.6) to use angular-cli@webpack following the directions from this doc:https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md

After `ng serve`, it shows the webpack version as `Version: webpack 2.1.0-beta.21` but I still get this error in browser:
`config.js:15Uncaught TypeError: Cannot read property 'Emulated' of undefined`

**Comment by Pekes317** [comment]
I was having the same issue and I uninstalled angular-cli globally and locally. Re-installed it globally then updated the package JSON and started a new project. I then updated the local JSON and uninstalled Webpack and reinstalled beta 22. Although I think updating the JSON and uninstalling Webpack and installing beta 22. You might have to update the Node Modules as whole though.

**Comment by richavyas** [comment]
I tried the solution that you suggested @Pekes317,  local JSON and uninstalled Webpack and reinstalled beta 22 and updated complete Node Modules too but when I run ng serve, it eventually shows Webpack version as `Version: webpack 2.1.0-beta.21`, doesn't matter my local `package.json` and even `npm list` include `"webpack": "2.1.0-beta.22"`. 
Absolutely clueless what to do.

**Comment by kover** [comment]
@richavyas go to node_modules/angular-cli, uninstall `npm uninstall webpack --save` then `npm install webpack --save`.

**Comment by richavyas** [comment]
Thanks @kover, it worked!!!!!!

**Comment by sharpmachine** [comment]
Holy heck this is a mess.

**Comment by cbassols** [comment]
I updated NodeJS to version 6.6.0 and it solved my problem.

Thanks @hassanasad for your suggestion 😀 👍
