### ISSUE TITLE
Update from ng 11 to 12 fails running npx @angular/cli@12 update

### ISSUE THREAD

**Issue by MBAatEJOT** [angular/angular-cli#22692]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] update from 11 to 12

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Update from 10 to 11

### Description

Try to follow the steps at https://update.angular.io/?l=2&v=11.0-12.0 (**not** using windows)

## 🔬 Minimal Reproduction

Trying to run `npx @angular/cli@12 update @angular/core@12 @angular/cli@12`

## 🔥 Exception or Error

<pre><code>
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/18399/lib/node_modules/@angular/cli/bin/postinstall/script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@12.2.16 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @angular/cli@12.2.16 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-11T13_29_53_949Z-debug.log
Install for [ '@angular/cli@12' ] failed with code 1

</code></pre>

## Extract from npm log
```
5231 silly postinstall @angular/cli@12.2.16
5232 info lifecycle @angular/cli@12.2.16~postinstall: @angular/cli@12.2.16
5233 verbose lifecycle @angular/cli@12.2.16~postinstall: unsafe-perm in lifecycle false
5234 verbose lifecycle @angular/cli@12.2.16~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.npm/_npx/8175/lib/node_modules/@angular/cli/node_modules/.bin:/root/.npm/_npx/8175/lib/node_modules/.bin:/workspaces/my-project/node_modules/.bin:/root/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin:/root/.local/bin
5235 verbose lifecycle @angular/cli@12.2.16~postinstall: CWD: /root/.npm/_npx/8175/lib/node_modules/@angular/cli
5236 silly lifecycle @angular/cli@12.2.16~postinstall: Args: [ '-c', 'node ./bin/postinstall/script.js' ]
5237 silly lifecycle @angular/cli@12.2.16~postinstall: Returned: code: 1  signal: null
5238 info lifecycle @angular/cli@12.2.16~postinstall: Failed to exec postinstall script
5239 timing action:postinstall Completed in 146ms
5240 verbose unlock done using /root/.npm/_locks/staging-5a86bcc16c941898.lock for /root/.npm/_npx/8175/lib/node_modules/.staging
5241 timing stage:rollbackFailedOptional Completed in 1062ms
5242 timing stage:runTopLevelLifecycles Completed in 19494ms
5243 verbose stack Error: @angular/cli@12.2.16 postinstall: `node ./bin/postinstall/script.js`
5243 verbose stack Exit status 1
5243 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
5243 verbose stack     at EventEmitter.emit (events.js:400:28)
5243 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
5243 verbose stack     at ChildProcess.emit (events.js:400:28)
5243 verbose stack     at maybeClose (internal/child_process.js:1058:16)
5243 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
5244 verbose pkgid @angular/cli@12.2.16
5245 verbose cwd /workspaces/my-project
5246 verbose Linux 5.10.16.3-microsoft-standard-WSL2
5247 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "install" "@angular/cli@12" "--global" "--prefix" "/root/.npm/_npx/8175" "--loglevel" "error" "--json"
5248 verbose node v14.18.3
5249 verbose npm  v6.14.15
5250 error code ELIFECYCLE
5251 error errno 1
5252 error @angular/cli@12.2.16 postinstall: `node ./bin/postinstall/script.js`
5252 error Exit status 1
5253 error Failed at the @angular/cli@12.2.16 postinstall script.
5253 error This is probably not a problem with npm. There is likely additional logging output above.
5254 verbose exit [ 1, true ]
```

## 🌍 Your Environment

<pre><code>

Angular CLI: 11.2.7
Node: 14.18.3
OS: linux x64

Angular: 11.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.7
@angular-devkit/build-angular   0.1102.7
@angular-devkit/core            11.2.7
@angular-devkit/schematics      11.2.7
@angular/cdk                    11.2.7
@angular/cli                    11.2.7
@angular/material               11.2.7
@schematics/angular             11.2.7
@schematics/update              0.1102.7
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Anything else relevant?**
It's running in an devcontainer

```dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/base:0-focal

RUN echo 'set show-all-if-ambiguous on' >> /etc/inputrc
RUN echo '"\\e[Z": menu-complete' >> /etc/inputrc

ENV \
		DOTNET_RUNNING_IN_CONTAINER=true \
		DOTNET_USE_POLLING_FILE_WATCHER=true \
		NUGET_XMLDOC_MODE=skip

RUN apt-get update \
	&& apt-get install -y wget pandoc

RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
	&& dpkg -i packages-microsoft-prod.deb

RUN apt-get update \
	&& apt-get install -y apt-transport-https

RUN apt-get update \
	&& apt-get install -y dotnet-sdk-6.0 \
	&& dotnet help \
	&& dotnet tool install --global dotnet-ef

RUN apt-get update \
	&& apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt-get install -y nodejs

RUN apt-get install -y build-essential

RUN npm i -g @angular/cli@^11
```

**Comment by alan-agius4** [comment]
Can you try to run the below command instead

```
ng @angular/cli update @angular/core@12 @angular/cli@12
```

**Comment by MBAatEJOT** [comment]
> Can you try to run the below command instead
> 
> ```
> ng @angular/cli update @angular/core@12 @angular/cli@12
> ```

This command won't work but 

> ng update @angular/core@12 @angular/cli@12

does.

**Comment by alan-agius4** [comment]
Opps sorry I did mean `ng update @angular/core@12 @angular/cli@12`. 

Closing as it seems that the issue has been resolved.

**Comment by MBAatEJOT** [comment]
Yeah, well the original problem **isn't solved**.  `npx @angular/cli@12 update @angular/core@12 @angular/cli@12` still won't work. 

The reason of the issue is, that either the bug should be fixed or the steps of https://update.angular.io should be adjusted to use `ng update` instead of `npx @angular/cli@12 update`

**Comment by alan-agius4** [comment]
@MBAatEJOT, yeah we should correct that.

**Comment by alan-agius4** [comment]
Docs PR: https://github.com/angular/angular-update-guide/pull/177
