### ISSUE TITLE
ng new - Cannot find module 'glob'

### ISSUE THREAD

**Issue by prabhatsharma** [angular/angular-cli#233]
prabhat@paradise-linux ~/projects $ ng new ab
Cannot find module 'glob'
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/angular-cli/addon/ng2/tasks/lib-install.js:11:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by jkuri** [comment]
Thanks for notice. We will fix this. In the meantime try installing glob globally.

**Comment by afavetta** [comment]
Same here with ng serve:
`C:\Alberto\moviesearch>ng serve
Cannot find module 'glob'
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Alberto\moviesearch\node_modules\angular-cli\addon\ng2\tasks\lib-install.js:11:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)`

I use Node v4.3.1

Thanks!

**Comment by filipesilva** [comment]
This is fixed currently in code, and should be up on the next version. You can try using the latest master for the time being.

**Comment by gadieichhorn** [comment]
the fix looks like its 2 month old but this is still an issue.

> ng build
BuildingCould not require 'angular-cli-build.js': Cannot find module 'glob'
Error: Could not require 'angular-cli-build.js': Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\Development\GitHub\play\node_modules\angular-cli\lib\broccoli\angular2-app.js:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

> ng -v
angular-cli: 0.0.33
node: 5.10.1
os: win32 x64

**Comment by PascalPrecht** [comment]
@gadieichhorn the missing `glob` dep has been fixed in latest master. This will go out in the next release.

For now, run `npm install --save glob` in your project
