### ISSUE TITLE
angular-cli doesn't respond

### ISSUE THREAD

**Issue by Fahrradflucht** [angular/angular-cli#2649]
### OS?

macOS 10.12
### Versions.

`ng --version` doesn't respond as well but the installed version is: `angular-cli@1.0.0-beta.17`

```
➜  ~  node -v
v6.7.0
```
### The log given by the failure.

There is actually no error message `ng new my-app` or `ng --version` just hang forever with no output until I hit Control-C.

```
➜  ~  ng new my-app
^C
```

**Comment by JanStureNielsen** [comment]
@Fahrradflucht -- do you have a `npm-debug.log`? If so, `cat` it...  And what does your `/var/log/messages` say when this happens?

**Comment by Fahrradflucht** [comment]
> do you have a npm-debug.log? 

No

> And what does your /var/log/messages say when this happens?

There is no `/var/log/messages`

--

As far as I can see there isn't even a node process that gets spun up.

**Comment by xavifuefer** [comment]
Same issue here... no logs either.

**Comment by ycros** [comment]
So I had this issue just now, I did some tracing and saw that the process was hanging shortly after trying to access `/usr/local/var/run/watchman/<myusername>-state` - it looks like it was trying to connect to the `sock` domain socket within that directory. The only problem is, I don't have any watchman process running, so it was just hanging. I was tracing system calls, and I couldn't spot where the code that was causing it to try and do this was.

I fixed it by removing my `/usr/local/var/run/watchman` directory. It's possible the problem I hit is a separate issue.

**Comment by Fahrradflucht** [comment]
Deleting `/usr/local/var/run/watchman/<myusername>-state` fixed it! 🎉 

Any idea why this is?

**Comment by filipesilva** [comment]
Not too sure of why this happens. Maybe some internal ember-cli machinery is hooking up into your local watchman dir. Need to look into it.

**Comment by Brocco** [comment]
Issue has been resolved, closing.

**Comment by xmlking** [comment]
@Brocco still cannot CTRL-C to stop `ng serve` . It hands and and have to do `kill -9`
I am using angular cli `v1.0.0-beta.26`

**Comment by nortain** [comment]
As of 1.4.4 CTRL-C still does not stop `ng serve` on Mac.  It would be really nice if we didn't have to kill the listening process.

**Comment by ashnur** [comment]
same on win10, ctrl+c never stops the node process. it's a joke.
