### ISSUE TITLE
Dramatic increase in build time for @angular-devkit/build-angular >= 20.2.x

### ISSUE THREAD

**Issue by kris-vista** [angular/angular-cli#31350]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular-devkit/build-angular 20.1.6

### Description

We run an nx monorepo with around 20+ Angular applications, some of these applications are quite large and are made up of 50+ child libraries
Most developers run Windows

Our apps currently do not use esbuild, they are still using `@angular-devkit/build-angular:browser`

After updating from Angular 20.1.x to 20.2.x (We have also tried 20.3.x) the build process has dramatically slowed down, to give an example, when running serve on one of our larger apps, making a change to an html file would take around 10 - 30 seconds to do a rebuild, now it takes around 5 minutes.

I have narrowed this down to `@angular-devkit/build-angular` by reducing versions of libraries, running builds and seeing how long it takes, I can run the application with all angular versions at `20.2.x` but `@angular-devkit/build-angular` at `20.1.6` and the build speeds return to normal

### Minimal Reproduction

I'm not sure how to give instructions to rerpoduce this issue as it requires a large app but if you have a large app on the latest version of angular, useing `@angular-devkit/build-angular:browser` for the builder
- Run serve, note how long it takes
- Change a file, note how long a rebuild takes

then downgrade `@angular-devkit/build-angular` to `20.1.6`, re run serve and note the new times

I'm happy to run some debug tasks but I'm not sure what to run at this point.

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 20.2.2
Node: 22.20.0
Package Manager: npm 10.9.3
OS: win32 x64


Angular: 20.2.4
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------
@angular-devkit/architect       0.2002.2
@angular-devkit/build-angular   20.2.2
@angular-devkit/core            20.2.2
@angular-devkit/schematics      20.2.2
@angular/cdk                    20.2.3
@angular/cli                    20.2.2
@angular/youtube-player         19.1.2
@schematics/angular             20.2.2
ng-packagr                      20.2.0
rxjs                            7.8.1
typescript                      5.9.2
zone.js                         0.15.0


I am also running NX 21.5.2
```

### Anything else relevant?

Updating to es build makes things better but i have also noticed running tests is slower than usual too

**Comment by clydin** [comment]
Other than dependency version updates, few changes have been made to the `browser` builder within those version ranges.
One potential item to look at is if there is a `postcss.config.json` or `.postcssrc.json` in the project or workspace root. Support was added to load those and use them when processing both global and component stylesheets.

If performance is a prime concern, please consider switching to the `application` build system.  It has provided up to a 70% reduction in build times for some projects.

**Comment by kris-vista** [comment]
> Other than dependency version updates, few changes have been made to the `browser` builder within those version ranges. One potential item to look at is if there is a `postcss.config.json` or `.postcssrc.json` in the project or workspace root. Support was added to load those and use them when processing both global and component stylesheets.
> 
> If performance is a prime concern, please consider switching to the `application` build system. It has provided up to a 70% reduction in build times for some projects.

I don't have `postcss.config.json` or `.postcssrc.json` anywhere in the monorepo

I am slowly switching to esbuild but this takes time in a largeish monorepo and it was such a dramatic change in build speeds I presume I'm not the only one suffering from it and that it should be reported

**Comment by clydin** [comment]
We have not had any other reports regarding this currently.
If you have some time, you can attempt to narrow down the root cause with your projects by trying 20.2.0 followed by each prerelease version (20.2.0-rc.1, 20.2.0-rc.0, 20.2.0-next.3, etc.).  Hopefully, that should help to isolate the specific commit.

**Comment by kris-vista** [comment]
I tried all the way back to `"@angular-devkit/build-angular": "20.2.0-next.0"` and its still slow there too unfortunately, so whatever is happening was introduced between `20.1.6` and `20.2.0-next.0`

Using `@angular-devkit/build-angular:application` does make application builds much faster but I am still having massive slow down on testing libraries, they now take forever to complete, and again, downgrading just `@angular-devkit/build-angular` to `20.1.6` makes everything speed right up again

One very important thing I have noticed, this appears to be a *Windows* specific issue, our build pipeline which is using Ubuntu works fine, but all our developers using Windows have this issue

Is there any sort of trace I can run against my build to see where things are hanging?

**Comment by octaviookumu** [comment]
We experienced a similar issue in our environment.

**Environment:**
```
Angular CLI: 20.2.2
Node: 22.18.0
Package Manager: npm 10.9.3
OS: darwin arm64

Angular: 20.3.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------
@angular-devkit/architect       0.2002.2
@angular-devkit/build-angular   20.2.2
@angular-devkit/core            20.2.2
@angular-devkit/schematics      20.2.2
@angular/cdk                    20.2.5
@angular/cli                    20.2.2
@schematics/angular             20.2.2
ng-packagr                      20.2.0
rxjs                            7.8.2
typescript                      5.9.2
zone.js                         0.15.1

Running on Nx monorepo (v21.5.x)
```

**Issue Details:**
- Serving app times increased from ~15 seconds to 50 seconds after upgrading from @angular-devkit/build-angular 20.1.x to 20.2.x
- Simple file changes (HTML, CSS, TS) trigger the long rebuild times (40 - 50s)

**Workaround Confirmed:**
Downgrading `@angular-devkit/build-angular` to `20.1.6` (while keeping other Angular packages at 20.2.x/20.3.x) resolves the performance issue and restores normal build times

This confirms the regression is specifically in @angular-devkit/build-angular between versions 20.1.6 and 20.2.0

**Comment by alan-agius4** [comment]
The only change to the browser builder between version `20.1.6` and `20.2.0-next.0` was a `webpack` version bump. Could you please test the build times using webpack versions **5.100.0**, **5.100.1** and **5.102.1**? Please use pnpm/npm/yarn overrides for this test.

**Comment by alan-agius4** [comment]
Closing due to inactivity/lack of response from the original reporter.

**Comment by hvpavel** [comment]
Hi @alan-agius4 ,

We have the same issue in our project. 

> Could you please test the build times using webpack versions 5.100.0, 5.100.1 and 5.102.1? Please use pnpm/npm/yarn overrides for this test.

I just ran these tests using npm overrides. I am using Angular 20.2.x with `@angular-devkit/build-angular@20.1.6`.

I see no difference in build time when using webpack 5.100.0 and 5.100.1. However, with webpack 5.102.1 the building time increases drastically. On average it takes 10x more time to rebuild an application, 6-8s turns into 55-90s. 

Could you please reopen the issue?

**Comment by alan-agius4** [comment]
Can you also please try `5.100.2`?

**Comment by hvpavel** [comment]
> Can you also please try `5.100.2`?

`webpack@5.100.2` has this issue too.

**Comment by alan-agius4** [comment]
So based on the webpack [release](https://github.com/webpack/webpack/releases/tag/v5.100.2) possibility it can be related to “ Dependency without the source order attribute must keep their original index”.

Ultimately there is not much we can do from our end here.

//cc @alexander-akait who is one of the maintainers of webpack.

**Comment by alexander-akait** [comment]
@alan-agius4 

> Dependency without the source order attribute must keep their original index

it not related to performance, this to fix a problem with order of `import` with css and other non js resources, so I don't think the problem there

What is the first version webpack was used in `20.2.x`?

**Comment by alan-agius4** [comment]
The first version used was `5.100.2`. From the comments above it appears the using overrides to  set webpack to `5.100.1` removes the performance regression.

**Comment by alexander-akait** [comment]
@alan-agius4 Weird, we have benchmarks and no changes there between these versions...

I think it is related to https://github.com/webpack/webpack/releases/tag/v5.101.0, we have 

> Fixed a regression in module concatenation after implementing deferred import support

And most likely this problem related to this due timing...

@hvpavel Can you give more context? Is it only for `production` or `development` mode? Are you sure do you use `5.100.2` (how do you check this)?

**Comment by hvpavel** [comment]
> Can you give more context?

It's an nx-monorepo based project with the respective nx configuration and packages. Nx report:

```
Node           : 22.20.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.3

nx                     : 21.5.3
@nx/js                 : 21.5.3
@nx/jest               : 21.5.3
@nx/eslint             : 21.5.3
@nx/workspace          : 21.5.3
@nx/angular            : 21.5.3
@nx/devkit             : 21.5.3
@nx/eslint-plugin      : 21.5.3
@nx/module-federation  : 21.5.3
@nx/node               : 21.5.3
@nx/plugin             : 21.5.3
@nx/rspack             : 21.5.3
@nx/web                : 21.5.3
@nx/webpack            : 21.5.3
@nx/docker             : 21.5.3
typescript             : 5.9.2
---------------------------------------
Community plugins:
@dot-build/serve-and-run-angular : 2.0.0
@ng-bootstrap/ng-bootstrap       : 19.0.1
@ngrx/component-store            : 20.0.1
@ngrx/effects                    : 20.0.1
@ngrx/entity                     : 20.0.1
@ngrx/operators                  : 20.0.1
@ngrx/router-store               : 20.0.1
@ngrx/signals                    : 20.0.1
@ngrx/store                      : 20.0.1
angular-eslint                   : 20.3.0
ng-extract-i18n-merge            : 2.15.1
```

I'm attaching a very simplified `apps/app-example/project.json` file to demonstrate the app production and development configuration. 

[project-example.json](https://github.com/user-attachments/files/23125081/project-example.json)

> Is it only for production or development mode?

Both modes are affected. However, earlier I was only talking about `development` mode

> I see no difference in build time when using webpack 5.100.0 and 5.100.1. However, with webpack 5.102.1 the building time increases drastically. On average it takes 10x more time to rebuild an application, 6-8s turns into 55-90s.

I also ran production build, and I observed consistent result across 5 runs with both 5.100.1 and 5.100.2 webpack versions. When I switched to `5.100.2`, building time (with `.nx` and `.angular` deleted) increased by ~70s, rebuilding time (with `.nx` and `.angular`) increased by ~50s.

```
# webpack@5.100.1
% rm -r .nx .angular
% nx build app-example --skipNxCache
Time: 196688ms
 NX   Successfully ran target build for project app-example (3m)
# repeat with .nx and .angular
% nx build app-example --skipNxCache
Time: 42454ms
 NX   Successfully ran target build for project app-example (48s)

# webpack@5.100.2
% rm -r .nx .angular
% nx build app-example --skipNxCache
Time: 268241ms
 NX   Successfully ran target build for project app-example (5m)
# repeat with .nx and .angular
% nx build app-example --skipNxCache
Time: 89618ms
 NX   Successfully ran target build for project app-example (2m)
```

> Are you sure do you use 5.100.2 (how do you check this)?

I've installed `webpack@5.100.2` as well as other versions that I tested by declaring an override in our `package.json` file:

```json
{
  "overrides": {
    "webpack": "5.100.2"
  }
}
```

Once installed, `package-lock.json` shows the corresponding version of `webpack`.

**Comment by alan-agius4** [comment]
I am closing this as this is not something that is actionable by the Angular CLI. As per the above it does indicate that this is an issue with Webpack started from version `5.100.2`.

**Comment by alexander-akait** [comment]
@hvpavel Can you try to use the latest version of webpack, yes, we have a regression in 5.100.2, but it was fixed

**Comment by hvpavel** [comment]
Hi @alexander-akait ,

I've just tried `webpack@5.102.1`, and unfortunately the issue still exists there.

**Comment by alexander-akait** [comment]
@hvpavel Are you sure that you really try `webpack@5.102.1`? Can you describe how you verify it? We have no reports about perf problems and our perf cases show the same time, webpack is a transitive deps for angular-cli, so `overrides` potentially doesn't work for some cases

**Comment by hvpavel** [comment]
@alexander-akait , I use npm overrides in order to install the latest wepback version. This is what I get in my `package-lock.json` after installation:

```json
{
  "node_modules/webpack": {
    "version": "5.102.1",
    "..."
  }
}
```

There is no other webpack installation listed in `package-lock.json`.

I've also verified the version of the package in `node_modules`:

```sh
$: cat node_modules/webpack/package.json | grep version
  "version": "5.102.1",
```

You can suggest another way to verify the version too, and I'll provide you with the answer :)

**Comment by alexander-akait** [comment]
@hvpavel hm, there are not much commits - https://github.com/webpack/webpack/compare/v5.100.1...v5.100.2, can you try manually them revert and look at permanence? 

Potential places:
- https://github.com/webpack/webpack/commit/89eb6a3c8109563050c5da42ed99de51782e6501 (maybe?)
- https://github.com/webpack/webpack/commit/e25189162aaf2576bf41996ec99fde2d6e134778 (I think should not touch perfomance)
- https://github.com/webpack/webpack/commit/9eb964224c7c5085dfd353466f32853b24a52d6c - should improve perfomance
- https://github.com/webpack/webpack/commit/0a984462ab2e69952bd9cf6895fdd6cbd2866c7d (maybe this?)

**Comment by hvpavel** [comment]
@alexander-akait , could you please suggest how I can install any of the listed versions of webpack in my project? I see no build commands to compose webpack, and it seems that using `npm pack .` doesn't produce a valid zip from the webpack repository.

**Comment by muhamedkarajic** [comment]
My webpack version was in v19
```json
"webpack": "5.98.0",
```

Maybe try that one @kris-vista ? However by me it makes no difference. I tested both and in v19 it takes me 25s to recompile while in v20 it takes me 75s to recompile. 

In my package.json I am using the Nx executor
```
@angular-devkit/build-angular:browser
```

**Comment by alexander-akait** [comment]
@hvpavel Just manually install `5.100.2` and in `node_modules/webpack/lib` revert these changes to check what is the problem

@muhamedkarajic Do you try to install the latest version of webpack?

**Comment by muhamedkarajic** [comment]
@alexander-akait 

```cmd
"webpack": "5.102.1"
```

I tried that version does NOT work. Since the update the initial serve takes from 125s to 181s. And recompile after some changes takes from 20s to 81s.

**Comment by alexander-akait** [comment]
@muhamedkarajic Can you create reproducible test repo?

**Comment by hvpavel** [comment]
Hi @alexander-akait ,

I've tested webpack according to your suggestion here:

> [@hvpavel](https://github.com/hvpavel) hm, there are not much commits - [webpack/webpack@v5.100.1...v5.100.2](https://github.com/webpack/webpack/compare/v5.100.1...v5.100.2), can you try manually them revert and look at permanence?
> 
> Potential places:
> 
> * [webpack/webpack@89eb6a3](https://github.com/webpack/webpack/commit/89eb6a3c8109563050c5da42ed99de51782e6501) (maybe?)
> * [webpack/webpack@e251891](https://github.com/webpack/webpack/commit/e25189162aaf2576bf41996ec99fde2d6e134778) (I think should not touch perfomance)
> * [webpack/webpack@9eb9642](https://github.com/webpack/webpack/commit/9eb964224c7c5085dfd353466f32853b24a52d6c) - should improve perfomance
> * [webpack/webpack@0a98446](https://github.com/webpack/webpack/commit/0a984462ab2e69952bd9cf6895fdd6cbd2866c7d) (maybe this?)

In order to test the changes I removed `node_modules/webpack/lib` folder and copied `lib/` folder from the webpack repository and then used `nx serve` to build the app. 

```shell
rm -r node_modules/webpack/lib
cp -r ../webpack/lib node_modules/webpack/lib
nx serve
```

- [webpack/webpack@0a98446](https://github.com/webpack/webpack/commit/0a984462ab2e69952bd9cf6895fdd6cbd2866c7d) straight away showed significant drop in the project recompilation time: avg 5s -> 35s 
- [webpack/webpack@9eb9642](https://github.com/webpack/webpack/commit/9eb964224c7c5085dfd353466f32853b24a52d6c) and [webpack/webpack@e251891](https://github.com/webpack/webpack/commit/e25189162aaf2576bf41996ec99fde2d6e134778) demonstrated the same performance as [webpack/webpack@0a98446](https://github.com/webpack/webpack/commit/0a984462ab2e69952bd9cf6895fdd6cbd2866c7d)
- [webpack/webpack@89eb6a3](https://github.com/webpack/webpack/commit/89eb6a3c8109563050c5da42ed99de51782e6501) worsened situation even further: avg recompilation time 35s -> 50s

Note: when I am talking about recompilation time, I am referring to the time that wepback takes to rebuild a project when the project is served via `nx serve` and a simple change in a component is made.

**Comment by alexander-akait** [comment]
@hvpavel Thanks for context, let's open an issue in webpack repo (just provide the same information as above), we need to investigate it, will be great to see how many modules affected here, because it should not take such many time...

**Comment by muhamedkarajic** [comment]
@alexander-akait have you had the change to open the issue on webpack?

**Comment by angelnikolov** [comment]
We seem to have the exact same issue.. `nx serve` recompilation increased **5x**. I also tried bumping webpack to `5.103.0` but it had no effect on the build performance.
Overriding webpack back to `5.98.0` improved build performance, but it obviously isn't a long-term solution.

**Comment by alexander-akait** [comment]
@angelnikolov Can you create a reproducible test repo, we've already raised this issue in the discussions, but with real code we would have solved it much faster.

**Comment by angelnikolov** [comment]
@alexander-akait I can't really make a repro quickly since we discovered this in a large close-source project and it's hard to take a piece of it (lot's of other dependencies that might affect the result).
Let me try reproducing it in a new project over the weekend and will get back to you.

**Comment by alexander-akait** [comment]
@angelnikolov Thank you, I also want to say that you can create a private repository and invite me (if necessary, I can sign an NDA), this is only required to study the situation

**Comment by xiaoxiaojx** [comment]
@hvpavel Please help test the following webpack versions. I’ve optimized the implementation of the PR that had performance issues. Thank you.
```bash
yarn add webpack@github:webpack/webpack#refs/pull/20204/head
```

**Comment by mhdmhsni** [comment]
Hi @xiaoxiaojx! leaving a comment here on behalf of @hvpavel as I'm his teammate! I've tested your PR and the results seems to be good.

Thank you for tackling this!

## Steps of testing

- installed `webpack: 5.103.0` to make sure the latest version is being used. (install via overrides).
- confirmed that the regression is still there with rebuild time of **>50s**.
- cloned [xiaoxiaojx repo](https://github.com/xiaoxiaojx/webpack/tree/perf/updateParent).
- (EDIT: in my project) `rm -rf node_modules/webpack/lib`
- `cp -r ../webpack/lib node_modules/webpack/lib`
- `nx serve`
- changed something really small in a component to trigger the `rebuild`
- the rebuild time was **<7s**
- <img width="533" height="217" alt="Image" src="https://github.com/user-attachments/assets/5c5161c9-b937-43f0-8fe9-f14546f500c4" />

## NX report
```bash
Node           : 22.20.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.3

nx                     : 21.6.9
@nx/js                 : 21.6.9
@nx/jest               : 21.6.9
@nx/eslint             : 21.6.9
@nx/workspace          : 21.6.9
@nx/angular            : 21.6.9
@nx/devkit             : 21.6.9
@nx/eslint-plugin      : 21.6.9
@nx/module-federation  : 21.6.9
@nx/node               : 21.6.9
@nx/plugin             : 21.6.9
@nx/rspack             : 21.6.9
@nx/web                : 21.6.9
@nx/webpack            : 21.6.9
@nx/docker             : 21.6.9
typescript             : 5.8.3
---------------------------------------
Community plugins:
@dot-build/serve-and-run-angular : 2.0.0
@ng-bootstrap/ng-bootstrap       : 19.0.1
@ngrx/component-store            : 20.1.0
@ngrx/effects                    : 20.1.0
@ngrx/entity                     : 20.1.0
@ngrx/operators                  : 20.1.0
@ngrx/router-store               : 20.1.0
@ngrx/signals                    : 20.1.0
@ngrx/store                      : 20.1.0
angular-eslint                   : 20.7.0
ng-extract-i18n-merge            : 3.1.0
```

**Comment by alexander-akait** [comment]
@mhdmhsni Thanks for feedback, merged - https://github.com/webpack/webpack/pull/20204, will be in the next minor release

**Comment by kakao-fleek-moon** [comment]
@alan-agius4 

Hello.

We're experiencing the same issue while using legacy builders in Angular (not using nx).

Webpack released a version with a fix for this issue 2 days ago.
(https://github.com/webpack/webpack/commit/4baab4e5778ca5d855d549189ffec5a674246ce0)

Could Angular also release a version that reflects webpack's changes?

**Comment by alan-agius4** [comment]
@kakao-fleek-moon, this will be available in the next patch release 21.0.4 which should be released later today.  https://github.com/angular/angular-cli/pull/32163

**Comment by kakao-fleek-moon** [comment]
@alan-agius4 
Thank you. I'm using Angular v20, so will this be reflected in version 20 as well?

**Comment by kakao-fleek-moon** [comment]
@alan-agius4 
It wasn't reflected in Angular 20 version. Could you please reflect it in version 20 as well?

**Comment by alan-agius4** [comment]
@kakao-fleek-moon, v20 is in LTS. Only security related fixes are merged.

**Comment by kakao-fleek-moon** [comment]
@alan-agius4 

Thank you for your response. I understand that v20 is in LTS and only security-related fixes are being merged.

However, I'd like to explain the situation:

This issue causes rebuild times to increase from approximately **1 second to 30+ seconds** for even a single line of code change, which severely impacts developer productivity.

While downgrading to an earlier minor version within v20 would resolve this issue, we cannot do so due to security concerns with those older versions. At the same time, upgrading to v21 is not currently feasible due to organizational dependencies and coordination required across multiple teams.

This means that not only our organization, but **all users** of the `@angular-devkit/build-angular:browser` builder on v20 are forced to endure a significantly degraded development experience with no viable workaround.

Would it be possible to consider this as an exceptional case for backporting, even though it's not strictly security-related? The performance regression is quite severe and affects daily development workflows substantially.

Thank you for your consideration.

**Comment by kakao-fleek-moon** [comment]
@alan-agius4 
Sorry for mentioning you repeatedly.
I'm leaving this comment again to check, as it seems you may have missed responding. 
Is the case above also not able to be handled as an exception?

**Comment by alan-agius4** [comment]
@kakao-fleek-moon, I am currently OOO. I’ll have a chat with @dgp1130 when I am back next week to check if this warrants an LTS.

**Comment by kakao-fleek-moon** [comment]
@alan-agius4 
Hi, I was wondering if a decision has been made yet?

**Comment by alan-agius4** [comment]
@kakao-fleek-moon, I had a chat with @dgp1130 and we will be be back porting this to version 20.

**Comment by kakao-fleek-moon** [comment]
Thank you so much.

**Comment by kakao-fleek-moon** [comment]
Hi @alan-agius4 
I was wondering if there's an estimated timeline for when this fix might be released. 
Our team continues to experience inconvenience due to this issue, so any rough ETA would be greatly appreciated.
Thanks again for your work on this! 🙏

**Comment by alan-agius4** [comment]
> Our team continues to experience inconvenience due to this issue, so any rough ETA would be greatly appreciated.

It should be on NPM later today.
