### ISSUE TITLE
ERROR in compiler_1.StaticSymbolResolver is not a constructor

### ISSUE THREAD

**Issue by mmort75** [angular/angular-cli#3727]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.24
node: 7.3.0
os: win32 x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### Repro steps.
ng build after updating app to latest version of angular cli and angular material.  It will no longer compile properly.

### The log given by the failure.
ERROR in compiler_1.StaticSymbolResolver is not a constructor

**Comment by bufke** [comment]
I had this problem too. I fixed it by carefully checking my packages.json to match those set in angular-cli and checking some dependencies that have renamed themselves from things like ng2-foo to ng-foo so that I have newer versions of those packages. Check every package even a mismatched typescript version can break things. For example ng2-clipboard became ngx-clipboard. Very tedious but it solved it for me.

**Comment by mmort75** [comment]
Thanks.  Doing this and clearing node_modules fixed the problem.  I just had to re-install missing dependencies one by one @bufke

**Comment by MrSingh** [comment]
I had the same problem, I deleted the node_modules folder and installed them again via `npm i` and then `ng serve` worked.  I still get the error but the project builds!
