### ISSUE TITLE
Update of styles should not reload the full page

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#3869]
Currently the server performs a full page reload. It should reload only the styles instead.

Possible solutions (clientside js):

- [CSSrefresh](http://cssrefresh.frebsite.nl/)
- [CSS auto-reload](http://nv.github.io/css_auto-reload/)

**Comment by clydin** [comment]
This would only affect global styles.  Component styles are inlined.
And the page would still reload.  The Dev server controls the reload.  However, it recently started supporting HMR.  You need to manually configurable your app to support it though.

**Comment by MickL** [comment]
Page reload for component styles is necessary and ok. But for regular styles css/scss/less it shouldn't reload the page.

Btw i assert that most developer won't use component styles.

**Comment by montella1507** [comment]
Well.. i think the must of reloading the page is not the biggest problem. The biggest problem is,  that webpack is rebuilding typescripts, optimizing assets and tons of another work, even if you had changed only 1 row in GLOBAL sass file. 

So the typical terrible experience with that is:
1) SASS rebuild time: 100ms
2) Webpack detects changes style.css 
3) Webpack rebuild: 25000ms 

I have tried lazy styles too, but the behavior is exactly the same .. Webpack is rebuiling..

Is it really needed to rebuild ALL, even if you have changed something in Global style = non shadow domed etc.

**Comment by gildebrand** [comment]
I have the same issue. I don't utilize component inline styling, but I do have a SCSS-file in the same directory, that is imported into my global stylesheet. For every small change in any SCSS-file, the entire app is recompiled, and reloaded. This takes approximately 20-25 seconds on my Mac, which is horrible when used to changes updating immediately.

**Comment by montella1507** [comment]
--extract-css in next Angular-cli 25. But it has several new bugs regarding webpack rc.3.. it has been already fixed in rc.4 so we have to wait for angular-cli 26

**Comment by clydin** [comment]
Actually the JS bundle is significantly faster than the extracted CSS in terms of rebuild time.
There is no one fix for the speed issue;  each new beta is showing incremental improvements however.

Webpack 2.2.0 final should be in beta.26

**Comment by montella1507** [comment]
@clydin well.. i would use styles: []  WITHOUT --extracted-css. but i really need SASS source maps.. and it has not been working for months... .map files are generated, but they are empty.. 

So i hoped, that --extracted-css will help NOT-ONLY with rebuild times, but with sourcemaps...  

So the only solution that is OK for me is:
1) use gulp-sass to build SCSS files 
2) copy generated .css to content folder
3) Wait for webpack "rebuild for nothing"
4) Wait for page refresh

It takes 150ms to rebuild SCSS + 16sec to rebuild solution with webpack without any change in code....

Its annoying, but it is the fastest solution with working source maps.

I still believe in dream, when i do one little change in SCSS and have to wait only 150ms for SASS rebuild 🗡

**Comment by niklas-dahl** [comment]
the ionic 2 cli makes it that changing a components stylesheet **does not** trigger a full reload, no idea how they do it and if it is possible to re-create this behaiviour here, but it uses angular 2 aswell so maby this is a starting point.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/3943

**Comment by shyamal890** [comment]
@filipesilva Sorry, I still don't fully understand the solution. 

1. From what I gather with the merged request in #3943 scss changes to file `styles.scss` and it's references shouldn't trigger rebuild. While at the same time if a change is made to `scss` file linked to a component rebuild would trigger. (`ng serve` without flags)

2. I tried 1 and it triggers build for both global `scss` files and component linked `scss` files. 

3. Even tried building with `ng serve -ec` that too triggers rebuild in both cases global and linked scss files.

**Comment by ndunks** [comment]
Many developer using modern browser such-as chrome based that can update-css without reload page (with devtool). I think is good if Angular has option about 'only compile/build scss /css to styles bundle' without reload page. or maybe an option to ignore watching some file(s).

**Comment by stephengardner** [comment]
I'm not sure what closing the issue is about but if you have **HMR** enabled on an Angular application with **Lazy-loaded** modules and you edit CSS, then the page will **refresh**.  Perhaps this deserves a separate issue?

**Comment by mtuzinskiy** [comment]
Why is it closed? It's still not resolved and it makes a development experience with Angular much worse than it could be.

**Comment by MickL** [comment]
I dont know if it is possible to not reload the page since a lot of styles are part of conponents(js files) and loaded dynamically. Maybe with the `--extract-css` option? Or with new Ivy renderer?

Compile times habe become very fast even for complex applications(often around one second) and when you are theming you often change the html-files, too which _have to_ trigger a full reload. So maybe there will not be a big benefits.

Anyway I would love to see css injection on development within less a second, too. This issue is definitely not resolved, @filipesilva maybe reopen?

**Comment by filipesilva** [comment]
@MickL my memory is sketchy about the resolution for this issue, but I think using [HMR](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) should be enough for global CSS to be updated without a page reload. I think that should also work for component CSS. Is that not the case?
