### ISSUE TITLE
Install cli peer dep missing rxjs and extraneous tsickle

### ISSUE THREAD

**Issue by Koshmaar** [angular/angular-cli#4484]
### OS?
Windows 7 x64 , running a cygwin console

### Versions.

> As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
> which will only support Node 6.9 and greater. This package will be officially deprecated
> shortly after.
> 
> To disable this warning use "ng set --global warnings.packageDeprecation=false".
> 
> angular-cli: 1.0.0-beta.28.3
> node: 6.9.1
> os: win32 x64

### Repro steps.

I just installed it:

> $ npm install -g angular-cli
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> C:\Users\Hubert\AppData\Roaming\npm\ng -> C:\Users\Hubert\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
> 
> > node-sass@4.5.0 install C:\Users\Hubert\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-48_binding.node
> Download complete
> Binary saved to C:\Users\Hubert\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-48\binding.node
> Caching binary to C:\Users\Hubert\AppData\Roaming\npm-cache\node-sass\4.5.0\win32-x64-48_binding.node
> 
> > node-sass@4.5.0 postinstall C:\Users\Hubert\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> > node scripts/build.js
> 
> Binary found at C:\Users\Hubert\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-48\binding.node
> Testing binary
> Binary is fine
> C:\Users\Hubert\AppData\Roaming\npm
> 
> [list of all packages]
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.

### The log given by the failure.
In addition to above:

> $ npm -g list | grep angular
> +-- angular-cli@1.0.0-beta.28.3
> | +-- @angular-cli/ast-tools@1.0.16
> | | +-- @angular/tsc-wrapped@0.5.2
> | +-- @angular-cli/base-href-webpack@1.0.16
> | +-- @angular/compiler@2.4.6
> | +-- @angular/compiler-cli@2.4.6
> | +-- @angular/core@2.4.6
> npm ERR! peer dep missing: rxjs@^5.0.1, required by @angular/core@2.4.6
> npm ERR! extraneous: tsickle@0.2.5 C:\Users\Hubert\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@angular-cli\ast-tools\node_modules\tsickle
> 
> 

### Mention any other details that might be useful.

I was able to run `ng new myapp` without problem.

**Comment by grizzm0** [comment]
Pretty sure this was fixed in #4465

**Comment by Koshmaar** [comment]
Ok! So I manually made this edit from commit in `C:\Users\Hubert\AppData\Roaming\npm\node_modules\angular-cli\package.json`
and did ` npm -g update angular-cli` but still get error:
> npm ERR! missing: rxjs@^5.0.1, required by angular-cli@1.0.0-beta.28.3

What else should I do?

**Comment by schmuli** [comment]
Still getting `extraneous` error during `npm ls`.

```
@angular/cli: 1.0.0-beta.30
node: 7.2.1
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/material: 2.0.0-beta.1
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6
```

**Comment by grizzm0** [comment]
Btw, you should use the new package name @angular/cli instead of angular-cli. angular-cli is beta 28.3 while @angular/cli is beta 30.

**Comment by nosaku** [comment]
Just now installed cli and got the following error:

npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.

**Comment by mickeyjohn** [comment]
Just installed angular-cli now and got the same error.

"npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed."

However, rxjs was installed with later version.
npm show rxjs version
5.1.0

**Comment by schmuli** [comment]
@mickeyjohn Be aware that `npm show` is actually showing information from NPM registry, not locally installed modules. Try `npm ls rxjs` for local modules.

**Comment by robertdacorte** [comment]
It isn't for OS, in OSX I have the same problem

**Comment by dahaupt** [comment]
I am getting the same errors for a globally installed `@angular/cli`.

**Comment by simsulla** [comment]
same here on "npm install -g @angular/cli"
`npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.`

**Comment by dragonvm** [comment]
I had this problem and solved updating angular cli following these steps:

https://github.com/angular/angular-cli#updating-angular-cli

I choosed to overwrite package.json and other files whose I didnt modify before.

**Comment by slapers** [comment]
This kind of solved it for me (running osx 10.12.2), i had an old version installed so did:

```
➜  ~ npm uninstall -g angular-cli @angular/cli
➜  ~ npm cache clean
➜  ~ npm install -g @angular/cli@latest
```

But unfortunately still got:
```
npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
```

Running ng help just crashed because of missing rxjs modules. So i just did:
```
➜  ~ npm install -g rxjs  
/usr/local/lib
└─┬ rxjs@5.1.0 
  └── symbol-observable@1.0.4 
``` 

After this the cli works correctly....

**Comment by Koshmaar** [comment]
Doing `npm install -g rxjs` helped to get rid of rxj peer error, but the extraneous was still there. 

So I did what @slapers wrote and that got rid of extraneous, but peer rxjs WARN (not ERR) came back:

> npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed

**Comment by catull** [comment]
@Koshmaar Have you tried 

`npm uninstall -g angular-cli`
`npm uninstall -g @angular/cli`
`npm cache clean`
`npm install -g @angular/cli`

**Comment by Koshmaar** [comment]
I just did that, before updating npm to 4.2 , and got: 

> $ npm -g list | grep angular
> +-- @angular/cli@1.0.0-beta.31
> | +-- UNMET PEER DEPENDENCY @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0
> | +-- UNMET PEER DEPENDENCY @angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0
> | +-- UNMET PEER DEPENDENCY @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0
> | +-- UNMET PEER DEPENDENCY @angular/tsc-wrapped@^0.5.0
> npm ERR! peer dep missing: @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
> npm ERR! peer dep missing: @angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
> npm ERR! peer dep missing: @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0, required by @ngtools/webpack@1.2.9
> npm ERR! peer dep missing: @angular/tsc-wrapped@^0.5.0, required by @ngtools/webpack@1.2.9

So to fix that I should do `npm install -g @angular/compiler` etc  ? I'd prefer to avoid having @angular in global namespace, just have it in local, but if there's no other way...

**Comment by catull** [comment]
No, I would not worry about it.

I have installed @angular/cli many times, I can create apps, `ng test` and `ng serve` them.
If I was you, I would not try very hard to appease every warning to make it go away.

Sure, it is annoying to see all those "UNMET PEER DEPENDENCY THIS and THAT"; however. you can ignore them and move on.

If you create a new app, and the look at what the package.json contains, you actually see it has

```json
  ...
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    ...
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.31",
    "@angular/compiler-cli": "^2.4.0",
    ....
  }
```

**Comment by filipesilva** [comment]
We've fixed these warnings since. Sorry about that folks.

**Comment by Maverick4u** [comment]
I started off fresh from with new application from scratch and was able to get a clean result with 
npm list -g --depth=0

Following are the steps.
1)	Uninstall angular-cli from global scope
This will remove old version of angular cli which has been deprecated and renamed to @angular/cli
        npm uninstall -g angular-cli
	npm cache clean
	npm uninstall --save-dev angular-cli
				           	
2)	Install @angular/cli at both global scope and current applications local scope
Global package:
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest

Local project package:
npm install --save-dev @angular/cli@latest

**Comment by Maverick4u** [comment]
Here is the result of command: npm list -g --depth=0

C:\Users\<localuserfolder>\AppData\Roaming\npm
+-- @angular/cli@1.0.0
+-- lite-server@2.2.2
+-- npm@4.1.2
+-- rxjs@5.2.0
`-- typescript@2.2.1
