### ISSUE TITLE
ng build succeeds on garbage ts file

### ISSUE THREAD

**Issue by jlabonski** [angular/angular-cli#4666]
I have a project with a type assertion to a model. The model ts file is mostly garbage but ng build succeeds and the project launches just fine. Desired behavior is that errors in ts files should produce errors during builds. 

### OS?
MacOS 10.12.3

### Versions.
angular-cli: 1.0.0-beta.28.3
node: 7.5.0
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6

### Repro steps.
Example code [here](https://github.com/jlabonski/ng-cli-wtf)

### The log given by the failure.
No logs, compile success, serve success.

### Mention any other details that might be useful.
Discovered this by putting a bunch of stubs in my model during development. I expected the tsc to yell about the unused methods and local vars, but it was oddly silent. My editors caught it (Atom, VSC, WebStorm) but ng did not.

Relying on an editor with tighter ts integration than the compile step of a project is not the best thing. There's something weird going on in ng's hijacking of tsc and the tsconfig. ng's build step should be canonical, pedantic, and final.

**Comment by Meligy** [comment]
It's tslint which is supposed to do that. `ng build` does not run `tslint`. `ng lint` does it.

**Comment by jlabonski** [comment]
`ng build`'s  `tsc` will compile a .ts file consisting of a poem? Why is that `tslint`'s issue?

There's code written in C in that .ts I pushed up, as well as some Lewis Carroll.

**Comment by Meligy** [comment]
I went by what was in the issue text. Sorry for that.

Looking at the code, it sure should show an error.

I assume this fails for you?

```
./node_modules/.bin/tsc -p src
```

And `ng build` still does not?

**Comment by jlabonski** [comment]
```
$ ./node_modules/.bin/tsc -p src
src/app/model/dog.ts(15,35): error TS1005: ';' expected.
src/app/model/dog.ts(15,39): error TS1005: ';' expected.
src/app/model/dog.ts(15,47): error TS1005: ';' expected.
src/app/model/dog.ts(16,10): error TS1005: ';' expected.
src/app/model/dog.ts(16,13): error TS1005: ';' expected.
src/app/model/dog.ts(16,20): error TS1005: ';' expected.
src/app/model/dog.ts(16,24): error TS1005: ';' expected.
src/app/model/dog.ts(16,29): error TS1005: ';' expected.
src/app/model/dog.ts(16,34): error TS1005: '(' expected.
src/app/model/dog.ts(16,38): error TS1005: ')' expected.
src/app/model/dog.ts(17,16): error TS1005: ';' expected.
src/app/model/dog.ts(17,21): error TS1005: ';' expected.
src/app/model/dog.ts(17,25): error TS1005: ';' expected.
src/app/model/dog.ts(17,28): error TS1005: ';' expected.
src/app/model/dog.ts(17,32): error TS1005: ';' expected.
src/app/model/dog.ts(17,36): error TS1005: ';' expected.
src/app/model/dog.ts(17,39): error TS1005: ';' expected.
src/app/model/dog.ts(17,43): error TS1005: ';' expected.
src/app/model/dog.ts(18,10): error TS1005: ';' expected.
src/app/model/dog.ts(18,12): error TS1005: ';' expected.
src/app/model/dog.ts(18,19): error TS1005: ';' expected.
src/app/model/dog.ts(18,35): error TS1005: ';' expected.
src/app/model/dog.ts(20,5): error TS1003: Identifier expected.
src/app/model/dog.ts(20,55): error TS1002: Unterminated string literal.
src/app/model/dog.ts(21,12): error TS1005: ';' expected.
src/app/model/dog.ts(21,18): error TS1005: ';' expected.
src/app/model/dog.ts(21,25): error TS1005: ';' expected.
src/app/model/dog.ts(21,35): error TS1005: ';' expected.
src/app/model/dog.ts(21,39): error TS1005: ';' expected.
src/app/model/dog.ts(21,44): error TS1003: Identifier expected.
src/app/model/dog.ts(22,10): error TS1005: ';' expected.
src/app/model/dog.ts(22,14): error TS1005: ';' expected.
src/app/model/dog.ts(22,20): error TS1005: ';' expected.
src/app/model/dog.ts(22,24): error TS1005: '(' expected.
src/app/model/dog.ts(22,26): error TS1005: ';' expected.
src/app/model/dog.ts(22,33): error TS1005: ';' expected.
src/app/model/dog.ts(22,35): error TS1005: ')' expected.
src/app/model/dog.ts(22,40): error TS1005: ';' expected.
src/app/model/dog.ts(22,45): error TS1005: ';' expected.
src/app/model/dog.ts(22,48): error TS1005: ';' expected.
src/app/model/dog.ts(23,12): error TS1005: ';' expected.
src/app/model/dog.ts(23,14): error TS1005: ';' expected.
src/app/model/dog.ts(23,19): error TS1005: ';' expected.
src/app/model/dog.ts(23,23): error TS1005: ';' expected.
src/app/model/dog.ts(23,29): error TS1005: ';' expected.
src/app/model/dog.ts(23,35): error TS1005: ';' expected.
src/app/model/dog.ts(23,38): error TS1005: ';' expected.
src/app/model/dog.ts(23,43): error TS1003: Identifier expected.
src/app/model/dog.ts(23,44): error TS1002: Unterminated string literal.
src/app/model/dog.ts(27,7): error TS1005: '=' expected.
src/app/model/dog.ts(27,12): error TS1005: ';' expected.
src/app/model/dog.ts(27,16): error TS1005: '=' expected.
src/app/model/dog.ts(27,24): error TS1005: ';' expected.
src/app/model/dog.ts(27,29): error TS1005: '=' expected.
src/app/model/dog.ts(27,38): error TS1005: ';' expected.
src/app/model/dog.ts(27,40): error TS1005: '=' expected.
src/app/model/dog.ts(27,45): error TS1127: Invalid character.
src/app/model/dog.ts(28,7): error TS1005: '=' expected.
src/app/model/dog.ts(28,13): error TS1005: ';' expected.
src/app/model/dog.ts(28,16): error TS1005: ';' expected.
src/app/model/dog.ts(28,24): error TS1005: ';' expected.
src/app/model/dog.ts(28,28): error TS1005: ';' expected.
src/app/model/dog.ts(28,33): error TS1127: Invalid character.
src/app/model/dog.ts(29,5): error TS1005: ';' expected.
src/app/model/dog.ts(29,24): error TS1005: ';' expected.
src/app/model/dog.ts(29,27): error TS1005: ';' expected.
src/app/model/dog.ts(29,35): error TS1005: ';' expected.
src/app/model/dog.ts(29,41): error TS1005: ';' expected.
src/app/model/dog.ts(29,49): error TS1127: Invalid character.
src/app/model/dog.ts(30,9): error TS1005: ';' expected.
src/app/model/dog.ts(30,11): error TS1005: ';' expected.
src/app/model/dog.ts(30,22): error TS1005: ';' expected.
src/app/model/dog.ts(30,28): error TS1005: ';' expected.
src/app/model/dog.ts(30,34): error TS1005: ';' expected.
src/app/model/dog.ts(30,40): error TS1003: Identifier expected.
src/app/model/dog.ts(33,10): error TS1005: ';' expected.
src/app/model/dog.ts(33,15): error TS1005: ';' expected.
src/app/model/dog.ts(33,20): error TS1005: ';' expected.
src/app/model/dog.ts(33,25): error TS1005: ';' expected.
src/app/model/dog.ts(33,32): error TS1005: ';' expected.
src/app/model/dog.ts(33,39): error TS1005: ';' expected.
src/app/model/dog.ts(33,50): error TS1002: Unterminated string literal.
src/app/model/dog.ts(35,1): error TS1128: Declaration or statement expected.
src/app/model/dog.ts(38,1): error TS1127: Invalid character.
src/app/model/dog.ts(39,1): error TS1127: Invalid character.
src/app/model/dog.ts(40,1): error TS1127: Invalid character.
src/app/model/dog.ts(40,9): error TS1005: ';' expected.
src/app/model/dog.ts(40,17): error TS1005: ';' expected.
src/app/model/dog.ts(40,30): error TS1005: ';' expected.
src/app/model/dog.ts(40,39): error TS1005: ';' expected.
src/app/model/dog.ts(43,5): error TS1005: ';' expected.
src/app/model/dog.ts(43,14): error TS1109: Expression expected.
src/app/model/dog.ts(46,12): error TS1005: ';' expected.
src/app/model/dog.ts(46,22): error TS1005: ';' expected.
src/app/model/dog.ts(46,36): error TS1109: Expression expected.
src/app/model/dog.ts(46,42): error TS1005: ';' expected.
src/app/model/dog.ts(47,12): error TS1005: ';' expected.
src/app/model/dog.ts(49,14): error TS1005: ';' expected.
src/app/model/dog.ts(51,18): error TS1109: Expression expected.
src/app/model/dog.ts(51,22): error TS1005: ';' expected.
src/app/model/dog.ts(51,24): error TS1109: Expression expected.
src/app/model/dog.ts(52,5): error TS1128: Declaration or statement expected.
src/app/model/dog.ts(52,18): error TS1109: Expression expected.
src/app/model/dog.ts(52,22): error TS1005: ';' expected.
src/app/model/dog.ts(52,24): error TS1109: Expression expected.
src/app/model/dog.ts(53,18): error TS1109: Expression expected.
src/app/model/dog.ts(53,22): error TS1005: ';' expected.
src/app/model/dog.ts(53,24): error TS1109: Expression expected.
src/app/model/dog.ts(54,18): error TS1109: Expression expected.
src/app/model/dog.ts(54,22): error TS1005: ';' expected.
src/app/model/dog.ts(54,24): error TS1109: Expression expected.
src/app/model/dog.ts(55,18): error TS1109: Expression expected.
src/app/model/dog.ts(55,22): error TS1005: ';' expected.
src/app/model/dog.ts(55,24): error TS1109: Expression expected.
src/app/model/dog.ts(56,18): error TS1109: Expression expected.
src/app/model/dog.ts(56,22): error TS1005: ';' expected.
src/app/model/dog.ts(56,24): error TS1109: Expression expected.
src/app/model/dog.ts(57,18): error TS1109: Expression expected.
src/app/model/dog.ts(57,22): error TS1005: ';' expected.
src/app/model/dog.ts(57,24): error TS1109: Expression expected.
src/app/model/dog.ts(58,18): error TS1109: Expression expected.
src/app/model/dog.ts(58,22): error TS1005: ';' expected.
src/app/model/dog.ts(58,24): error TS1109: Expression expected.
src/app/model/dog.ts(64,1): error TS1128: Declaration or statement expected.

$ ng build
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
Hash: e4ba3b032dcd243bf97a
Time: 5555ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 4.18 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.38 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
```

**Comment by filipesilva** [comment]
I can verify this happens. Good way to confuse and entertain colleagues.

So it seems that this is some odd side effect of how TS uses interfaces, and how webpack works? As soon as I try to use it as a 'real' class (`var woof = new Dog('woofer');`), I get the errors.

So huh, interesting catch. @hansl do you know why app code can safely burst into poetry?

**Comment by filipesilva** [comment]
I think this is a corollary of https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897 actually. Webpack compiles `src/app/app.component.ts` but since `Dog` is an interface, no import is generated for it so webpack doesn't care about what's in the file.
