### ISSUE TITLE
unmet peer dependencies?

### ISSUE THREAD

**Issue by vicatcu** [angular/angular-cli#4721]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.31
node: 6.9.1
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

npm install -g @angular/cli@latest

### The log given by the failure.
> Normally this include a stack trace and some more information.

/home/vic/.nvm/versions/node/v6.9.1/bin/ng -> /home/vic/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/bin/ng

> node-sass@4.5.0 install /home/vic/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/vic/.npm/node-sass/4.5.0/linux-x64-48_binding.node

> node-sass@4.5.0 postinstall /home/vic/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Binary found at /home/vic/.nvm/versions/node/v6.9.1/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-48/binding.node
Testing binary
Binary is fine
/home/vic/.nvm/versions/node/v6.9.1/lib
└─┬ @angular/cli@1.0.0-beta.31 
  ├── UNMET PEER DEPENDENCY @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0
  ├── UNMET PEER DEPENDENCY @angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0
  ├── UNMET PEER DEPENDENCY @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0
  ├── UNMET PEER DEPENDENCY @angular/tsc-wrapped@^0.5.0
  ├── @ngtools/json-schema@1.0.3 
  ├─┬ @ngtools/webpack@1.2.9 
  │ ├── enhanced-resolve@3.1.0 
  │ ├─┬ loader-utils@0.2.16 
  │ │ ├── big.js@3.1.3 
  │ │ ├── emojis-list@2.1.0 
  │ │ └── json5@0.5.1 
  │ ├─┬ magic-string@0.19.0 
  │ │ └── vlq@0.2.1 
  │ └── source-map@0.5.6 
  ├── async@2.1.4 
  ├─┬ autoprefixer@6.7.3 
  │ ├─┬ browserslist@1.7.3 
  │ │ └── electron-to-chromium@1.2.2 
  │ ├── caniuse-db@1.0.30000623 
  │ ├── normalize-range@0.1.2 
  │ ├── num2fraction@1.2.2 
  │ ├─┬ postcss@5.2.13 
  │ │ └── js-base64@2.1.9 
  │ └── postcss-value-parser@3.3.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ common-tags@1.4.0 
  │ └─┬ babel-runtime@6.23.0 
  │   ├── core-js@2.4.1 
  │   └── regenerator-runtime@0.10.1 
  ├─┬ css-loader@0.26.1 
  │ ├─┬ babel-code-frame@6.22.0 
  │ │ ├── esutils@2.0.2 
  │ │ └── js-tokens@3.0.1 
  │ ├─┬ css-selector-tokenizer@0.7.0 
  │ │ ├── cssesc@0.1.0 
  │ │ ├── fastparse@1.1.1 
  │ │ └─┬ regexpu-core@1.0.0 
  │ │   ├── regenerate@1.3.2 
  │ │   ├── regjsgen@0.2.0 
  │ │   └─┬ regjsparser@0.1.5 
  │ │     └── jsesc@0.5.0 
  │ ├── lodash.camelcase@4.3.0 
  │ ├── object-assign@4.1.1 
  │ ├── postcss-modules-extract-imports@1.0.1 
  │ ├─┬ postcss-modules-local-by-default@1.1.1 
  │ │ └── css-selector-tokenizer@0.6.0 
  │ ├─┬ postcss-modules-scope@1.0.2 
  │ │ └── css-selector-tokenizer@0.6.0 
  │ ├─┬ postcss-modules-values@1.2.2 
  │ │ └── icss-replace-symbols@1.0.2 
  │ └── source-list-map@0.1.8 
  ├─┬ cssnano@3.10.0 
  │ ├── decamelize@1.2.0 
  │ ├── defined@1.0.0 
  │ ├─┬ has@1.0.1 
  │ │ └── function-bind@1.1.0 
  │ ├─┬ postcss-calc@5.3.1 
  │ │ ├── postcss-message-helpers@2.0.0 
  │ │ └─┬ reduce-css-calc@1.3.0 
  │ │   ├── math-expression-evaluator@1.2.16 
  │ │   └── reduce-function-call@1.0.2 
  │ ├─┬ postcss-colormin@2.2.2 
  │ │ └─┬ colormin@1.1.2 
  │ │   ├─┬ color@0.11.4 
  │ │   │ ├── clone@1.0.2 
  │ │   │ ├─┬ color-convert@1.9.0 
  │ │   │ │ └── color-name@1.1.1 
  │ │   │ └── color-string@0.3.0 
  │ │   └── css-color-names@0.0.4 
  │ ├── postcss-convert-values@2.6.1 
  │ ├── postcss-discard-comments@2.0.4 
  │ ├── postcss-discard-duplicates@2.0.2 
  │ ├── postcss-discard-empty@2.1.0 
  │ ├── postcss-discard-overridden@0.1.1 
  │ ├─┬ postcss-discard-unused@2.2.3 
  │ │ └── uniqs@2.0.0 
  │ ├─┬ postcss-filter-plugins@2.0.2 
  │ │ └─┬ uniqid@4.1.1 
  │ │   └── macaddress@0.2.8 
  │ ├── postcss-merge-idents@2.1.7 
  │ ├── postcss-merge-longhand@2.0.2 
  │ ├─┬ postcss-merge-rules@2.1.1 
  │ │ ├─┬ caniuse-api@1.5.3 
  │ │ │ ├── lodash.memoize@4.1.2 
  │ │ │ └── lodash.uniq@4.5.0 
  │ │ ├─┬ postcss-selector-parser@2.2.2 
  │ │ │ ├── flatten@1.0.2 
  │ │ │ ├── indexes-of@1.0.1 
  │ │ │ └── uniq@1.0.1 
  │ │ └── vendors@1.0.1 
  │ ├── postcss-minify-font-values@1.0.5 
  │ ├── postcss-minify-gradients@1.0.5 
  │ ├─┬ postcss-minify-params@1.2.2 
  │ │ └── alphanum-sort@1.0.2 
  │ ├── postcss-minify-selectors@2.1.1 
  │ ├── postcss-normalize-charset@1.1.1 
  │ ├─┬ postcss-normalize-url@3.0.8 
  │ │ ├── is-absolute-url@2.1.0 
  │ │ └─┬ normalize-url@1.9.0 
  │ │   ├── prepend-http@1.0.4 
  │ │   ├─┬ query-string@4.3.2 
  │ │   │ └── strict-uri-encode@1.1.0 
  │ │   └─┬ sort-keys@1.1.2 
  │ │     └── is-plain-obj@1.1.0 
  │ ├── postcss-ordered-values@2.2.3 
  │ ├── postcss-reduce-idents@2.4.0 
  │ ├── postcss-reduce-initial@1.0.1 
  │ ├── postcss-reduce-transforms@1.0.4 
  │ ├─┬ postcss-svgo@2.1.6 
  │ │ ├─┬ is-svg@2.1.0 
  │ │ │ └── html-comment-regex@1.1.1 
  │ │ └─┬ svgo@0.7.2 
  │ │   ├─┬ coa@1.0.1 
  │ │   │ └── q@1.4.1 
  │ │   ├── colors@1.1.2 
  │ │   ├─┬ csso@2.3.1 
  │ │   │ └── clap@1.1.2 
  │ │   ├─┬ js-yaml@3.7.0 
  │ │   │ ├─┬ argparse@1.0.9 
  │ │   │ │ └── sprintf-js@1.0.3 
  │ │   │ └── esprima@2.7.3 
  │ │   ├── sax@1.2.2 
  │ │   └── whet.extend@0.9.9 
  │ ├── postcss-unique-selectors@2.0.2 
  │ └── postcss-zindex@2.2.0 
  ├─┬ debug@2.6.1 
  │ └── ms@0.7.2 
  ├── denodeify@1.2.1 
  ├── diff@3.2.0 
  ├── ember-cli-normalize-entity-name@1.0.0 
  ├── ember-cli-string-utils@1.1.0 
  ├─┬ extract-text-webpack-plugin@2.0.0-rc.3 
  │ └─┬ ajv@4.11.3 
  │   ├── co@4.6.0 
  │   └─┬ json-stable-stringify@1.0.1 
  │     └── jsonify@0.0.0 
  ├── file-loader@0.10.0 
  ├─┬ findup@0.1.5 
  │ ├── colors@0.6.2 
  │ └── commander@2.1.0 
  ├─┬ fs-extra@2.0.0 
  │ ├── graceful-fs@4.1.11 
  │ └── jsonfile@2.4.0 
  ├── get-caller-file@1.0.2 
  ├─┬ glob@7.1.1 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.6 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.3 
  │ ├── once@1.4.0 
  │ └── path-is-absolute@1.0.1 
  ├─┬ html-webpack-plugin@2.28.0 
  │ ├── bluebird@3.4.7 
  │ ├─┬ html-minifier@3.3.1 
  │ │ ├─┬ camel-case@3.0.0 
  │ │ │ ├─┬ no-case@2.3.1 
  │ │ │ │ └── lower-case@1.1.3 
  │ │ │ └── upper-case@1.1.3 
  │ │ ├── clean-css@4.0.7 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ ├── he@1.1.1 
  │ │ ├─┬ ncname@1.0.0 
  │ │ │ └── xml-char-classes@1.0.0 
  │ │ ├── param-case@2.1.0 
  │ │ └── relateurl@0.2.7 
  │ ├─┬ pretty-error@2.0.2 
  │ │ ├─┬ renderkid@2.0.0 
  │ │ │ ├─┬ css-select@1.2.0 
  │ │ │ │ ├── boolbase@1.0.0 
  │ │ │ │ ├── css-what@2.1.0 
  │ │ │ │ ├─┬ domutils@1.5.1 
  │ │ │ │ │ └─┬ dom-serializer@0.1.0 
  │ │ │ │ │   ├── domelementtype@1.1.3 
  │ │ │ │ │   └── entities@1.1.1 
  │ │ │ │ └── nth-check@1.0.1 
  │ │ │ ├─┬ dom-converter@0.1.4 
  │ │ │ │ └── utila@0.3.3 
  │ │ │ ├─┬ htmlparser2@3.3.0 
  │ │ │ │ ├── domelementtype@1.3.0 
  │ │ │ │ ├── domhandler@2.1.0 
  │ │ │ │ ├── domutils@1.1.6 
  │ │ │ │ └─┬ readable-stream@1.0.34 
  │ │ │ │   └── isarray@0.0.1 
  │ │ │ └── utila@0.3.3 
  │ │ └── utila@0.4.0 
  │ └── toposort@1.0.3 
  ├── inflection@1.12.0 
  ├─┬ inquirer@3.0.1 
  │ ├── ansi-escapes@1.4.0 
  │ ├─┬ cli-cursor@2.1.0 
  │ │ └─┬ restore-cursor@2.0.0 
  │ │   ├─┬ onetime@2.0.0 
  │ │   │ └── mimic-fn@1.1.0 
  │ │   └── signal-exit@3.0.2 
  │ ├── cli-width@2.1.0 
  │ ├─┬ external-editor@2.0.1 
  │ │ └── tmp@0.0.31 
  │ ├── figures@2.0.0 
  │ ├── mute-stream@0.0.7 
  │ ├─┬ run-async@2.3.0 
  │ │ └── is-promise@2.1.0 
  │ ├── rx@4.1.0 
  │ ├─┬ string-width@2.0.0 
  │ │ └── is-fullwidth-code-point@2.0.0 
  │ └── through@2.3.8 
  ├── isbinaryfile@3.0.2 
  ├─┬ istanbul-instrumenter-loader@2.0.0 
  │ ├── convert-source-map@1.4.0 
  │ └─┬ istanbul-lib-instrument@1.4.2 
  │   ├─┬ babel-generator@6.23.0 
  │   │ ├── babel-messages@6.23.0 
  │   │ ├─┬ detect-indent@4.0.0 
  │   │ │ └─┬ repeating@2.0.1 
  │   │ │   └── is-finite@1.0.2 
  │   │ ├── jsesc@1.3.0 
  │   │ └── trim-right@1.0.1 
  │   ├── babel-template@6.23.0 
  │   ├─┬ babel-traverse@6.23.1 
  │   │ ├── globals@9.15.0 
  │   │ └─┬ invariant@2.2.2 
  │   │   └── loose-envify@1.3.1 
  │   ├─┬ babel-types@6.23.0 
  │   │ └── to-fast-properties@1.0.2 
  │   ├── babylon@6.15.0 
  │   └── istanbul-lib-coverage@1.0.1 
  ├── json-loader@0.5.4 
  ├── karma-sourcemap-loader@0.3.7 
  ├─┬ karma-webpack@2.0.2 
  │ ├── async@0.9.2 
  │ ├── lodash@3.10.1 
  │ ├─┬ source-map@0.1.43 
  │ │ └── amdefine@1.0.1 
  │ └─┬ webpack-dev-middleware@1.10.0 
  │   └── range-parser@1.2.0 
  ├─┬ less@2.7.2 
  │ ├─┬ errno@0.1.4 
  │ │ └── prr@0.0.0 
  │ ├── image-size@0.5.1 
  │ ├── mime@1.3.4 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ promise@7.1.1 
  │ │ └── asap@2.0.5 
  │ └─┬ request@2.79.0 
  │   ├── aws-sign2@0.6.0 
  │   ├── aws4@1.6.0 
  │   ├── caseless@0.11.0 
  │   ├─┬ combined-stream@1.0.5 
  │   │ └── delayed-stream@1.0.0 
  │   ├── extend@3.0.0 
  │   ├── forever-agent@0.6.1 
  │   ├─┬ form-data@2.1.2 
  │   │ └── asynckit@0.4.0 
  │   ├─┬ har-validator@2.0.6 
  │   │ ├── commander@2.9.0 
  │   │ └─┬ is-my-json-valid@2.15.0 
  │   │   ├── generate-function@2.0.0 
  │   │   ├─┬ generate-object-property@1.2.0 
  │   │   │ └── is-property@1.0.2 
  │   │   └── jsonpointer@4.0.1 
  │   ├─┬ hawk@3.1.3 
  │   │ ├── boom@2.10.1 
  │   │ ├── cryptiles@2.0.5 
  │   │ ├── hoek@2.16.3 
  │   │ └── sntp@1.0.9 
  │   ├─┬ http-signature@1.1.1 
  │   │ ├── assert-plus@0.2.0 
  │   │ ├─┬ jsprim@1.3.1 
  │   │ │ ├── extsprintf@1.0.2 
  │   │ │ ├── json-schema@0.2.3 
  │   │ │ └── verror@1.3.6 
  │   │ └─┬ sshpk@1.10.2 
  │   │   ├── asn1@0.2.3 
  │   │   ├── assert-plus@1.0.0 
  │   │   ├── bcrypt-pbkdf@1.0.1 
  │   │   ├─┬ dashdash@1.14.1 
  │   │   │ └── assert-plus@1.0.0 
  │   │   ├── ecc-jsbn@0.1.1 
  │   │   ├─┬ getpass@0.1.6 
  │   │   │ └── assert-plus@1.0.0 
  │   │   ├── jodid25519@1.0.2 
  │   │   ├── jsbn@0.1.1 
  │   │   └── tweetnacl@0.14.5 
  │   ├── is-typedarray@1.0.0 
  │   ├── isstream@0.1.2 
  │   ├── json-stringify-safe@5.0.1 
  │   ├─┬ mime-types@2.1.14 
  │   │ └── mime-db@1.26.0 
  │   ├── oauth-sign@0.8.2 
  │   ├── qs@6.3.0 
  │   ├── stringstream@0.0.5 
  │   ├── tough-cookie@2.3.2 
  │   ├── tunnel-agent@0.4.3 
  │   └── uuid@3.0.1 
  ├── less-loader@2.2.3 
  ├── lodash@4.17.4 
  ├─┬ minimatch@3.0.3 
  │ └─┬ brace-expansion@1.1.6 
  │   ├── balanced-match@0.4.2 
  │   └── concat-map@0.0.1 
  ├── node-modules-path@1.0.1 
  ├─┬ node-sass@4.5.0 
  │ ├── async-foreach@0.1.3 
  │ ├─┬ cross-spawn@3.0.1 
  │ │ ├─┬ lru-cache@4.0.2 
  │ │ │ ├── pseudomap@1.0.2 
  │ │ │ └── yallist@2.0.0 
  │ │ └─┬ which@1.2.12 
  │ │   └── isexe@1.1.2 
  │ ├─┬ gaze@1.1.2 
  │ │ └─┬ globule@1.1.0 
  │ │   └── lodash@4.16.6 
  │ ├── get-stdin@4.0.1 
  │ ├── in-publish@2.0.0 
  │ ├── lodash.assign@4.2.0 
  │ ├── lodash.clonedeep@4.5.0 
  │ ├── lodash.mergewith@4.6.0 
  │ ├─┬ meow@3.7.0 
  │ │ ├─┬ camelcase-keys@2.1.0 
  │ │ │ └── camelcase@2.1.1 
  │ │ ├─┬ loud-rejection@1.6.0 
  │ │ │ └─┬ currently-unhandled@0.4.1 
  │ │ │   └── array-find-index@1.0.2 
  │ │ ├── map-obj@1.0.1 
  │ │ ├── minimist@1.2.0 
  │ │ ├─┬ normalize-package-data@2.3.5 
  │ │ │ ├── hosted-git-info@2.2.0 
  │ │ │ ├─┬ is-builtin-module@1.0.0 
  │ │ │ │ └── builtin-modules@1.1.1 
  │ │ │ └─┬ validate-npm-package-license@3.0.1 
  │ │ │   ├─┬ spdx-correct@1.0.2 
  │ │ │   │ └── spdx-license-ids@1.2.2 
  │ │ │   └── spdx-expression-parse@1.0.4 
  │ │ ├─┬ read-pkg-up@1.0.1 
  │ │ │ ├─┬ find-up@1.1.2 
  │ │ │ │ └── path-exists@2.1.0 
  │ │ │ └─┬ read-pkg@1.1.0 
  │ │ │   ├─┬ load-json-file@1.1.0 
  │ │ │   │ ├─┬ parse-json@2.2.0 
  │ │ │   │ │ └─┬ error-ex@1.3.0 
  │ │ │   │ │   └── is-arrayish@0.2.1 
  │ │ │   │ ├── pify@2.3.0 
  │ │ │   │ └─┬ strip-bom@2.0.0 
  │ │ │   │   └── is-utf8@0.2.1 
  │ │ │   └── path-type@1.1.0 
  │ │ ├─┬ redent@1.0.0 
  │ │ │ ├── indent-string@2.1.0 
  │ │ │ └── strip-indent@1.0.1 
  │ │ └── trim-newlines@1.0.0 
  │ ├── nan@2.5.1 
  │ ├─┬ node-gyp@3.5.0 
  │ │ ├── fstream@1.0.10 
  │ │ ├── nopt@3.0.6 
  │ │ └─┬ tar@2.2.1 
  │ │   └── block-stream@0.0.9 
  │ ├─┬ npmlog@4.0.2 
  │ │ ├─┬ are-we-there-yet@1.1.2 
  │ │ │ └── delegates@1.0.0 
  │ │ ├── console-control-strings@1.1.0 
  │ │ ├─┬ gauge@2.7.3 
  │ │ │ ├── aproba@1.1.1 
  │ │ │ ├── has-unicode@2.0.1 
  │ │ │ ├─┬ string-width@1.0.2 
  │ │ │ │ └── is-fullwidth-code-point@1.0.0 
  │ │ │ └─┬ wide-align@1.1.0 
  │ │ │   └─┬ string-width@1.0.2 
  │ │ │     └── is-fullwidth-code-point@1.0.0 
  │ │ └── set-blocking@2.0.0 
  │ ├─┬ sass-graph@2.1.2 
  │ │ └─┬ yargs@4.8.1 
  │ │   ├── cliui@3.2.0 
  │ │   ├─┬ string-width@1.0.2 
  │ │   │ └── is-fullwidth-code-point@1.0.0 
  │ │   ├── window-size@0.2.0 
  │ │   └─┬ yargs-parser@2.4.1 
  │ │     └── camelcase@3.0.0 
  │ └─┬ stdout-stream@1.4.0 
  │   └─┬ readable-stream@2.2.2 
  │     ├── buffer-shims@1.0.0 
  │     ├── core-util-is@1.0.2 
  │     ├── isarray@1.0.0 
  │     ├── process-nextick-args@1.0.7 
  │     └── util-deprecate@1.0.2 
  ├─┬ nopt@4.0.1 
  │ ├── abbrev@1.1.0 
  │ └─┬ osenv@0.1.4 
  │   └── os-homedir@1.0.2 
  ├─┬ opn@4.0.2 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
  ├─┬ portfinder@1.0.13 
  │ └── async@1.5.2 
  ├── postcss-loader@0.13.0 
  ├── raw-loader@0.5.1 
  ├── resolve@1.2.0 
  ├── rimraf@2.5.4 
  ├── rsvp@3.3.3 
  ├─┬ rxjs@5.1.1 
  │ └── symbol-observable@1.0.4 
  ├── sass-loader@4.1.1 
  ├── script-loader@0.7.0 
  ├── semver@5.3.0 
  ├── silent-error@1.0.1 
  ├─┬ source-map-loader@0.1.6 
  │ ├── async@0.9.2 
  │ └── source-map@0.1.43 
  ├── style-loader@0.13.1 
  ├─┬ stylus@0.54.5 
  │ ├── css-parse@1.7.0 
  │ ├── glob@7.0.6 
  │ ├── sax@0.5.8 
  │ └── source-map@0.1.43 
  ├─┬ stylus-loader@2.4.0 
  │ └── when@3.6.4 
  ├─┬ temp@0.8.3 
  │ ├── os-tmpdir@1.0.2 
  │ └── rimraf@2.2.8 
  ├── typescript@2.1.6 
  ├─┬ url-loader@0.5.7 
  │ └── mime@1.2.11 
  ├─┬ walk-sync@0.3.1 
  │ ├── ensure-posix-path@1.0.2 
  │ └── matcher-collection@1.0.4 
  ├─┬ webpack@2.2.1 
  │ ├── acorn@4.0.11 
  │ ├── acorn-dynamic-import@2.0.1 
  │ ├── ajv-keywords@1.5.1 
  │ ├── interpret@1.0.1 
  │ ├── loader-runner@2.3.0 
  │ ├── memory-fs@0.4.1 
  │ ├─┬ node-libs-browser@2.0.0 
  │ │ ├── assert@1.4.1 
  │ │ ├─┬ browserify-zlib@0.1.4 
  │ │ │ └── pako@0.2.9 
  │ │ ├─┬ buffer@4.9.1 
  │ │ │ ├── base64-js@1.2.0 
  │ │ │ └── ieee754@1.1.8 
  │ │ ├─┬ console-browserify@1.1.0 
  │ │ │ └── date-now@0.1.4 
  │ │ ├── constants-browserify@1.0.0 
  │ │ ├─┬ crypto-browserify@3.11.0 
  │ │ │ ├─┬ browserify-cipher@1.0.0 
  │ │ │ │ ├─┬ browserify-aes@1.0.6 
  │ │ │ │ │ └── buffer-xor@1.0.3 
  │ │ │ │ ├─┬ browserify-des@1.0.0 
  │ │ │ │ │ └── des.js@1.0.0 
  │ │ │ │ └── evp_bytestokey@1.0.0 
  │ │ │ ├─┬ browserify-sign@4.0.0 
  │ │ │ │ ├── bn.js@4.11.6 
  │ │ │ │ ├── browserify-rsa@4.0.1 
  │ │ │ │ ├─┬ elliptic@6.3.3 
  │ │ │ │ │ ├── brorand@1.0.7 
  │ │ │ │ │ └── hash.js@1.0.3 
  │ │ │ │ └─┬ parse-asn1@5.0.0 
  │ │ │ │   └── asn1.js@4.9.1 
  │ │ │ ├── create-ecdh@4.0.0 
  │ │ │ ├─┬ create-hash@1.1.2 
  │ │ │ │ ├── cipher-base@1.0.3 
  │ │ │ │ ├── ripemd160@1.0.1 
  │ │ │ │ └── sha.js@2.4.8 
  │ │ │ ├── create-hmac@1.1.4 
  │ │ │ ├─┬ diffie-hellman@5.0.2 
  │ │ │ │ └── miller-rabin@4.0.0 
  │ │ │ ├── pbkdf2@3.0.9 
  │ │ │ ├── public-encrypt@4.0.0 
  │ │ │ └── randombytes@2.0.3 
  │ │ ├── domain-browser@1.1.7 
  │ │ ├── events@1.1.1 
  │ │ ├── https-browserify@0.0.1 
  │ │ ├── os-browserify@0.2.1 
  │ │ ├── path-browserify@0.0.0 
  │ │ ├── process@0.11.9 
  │ │ ├── punycode@1.4.1 
  │ │ ├── querystring-es3@0.2.1 
  │ │ ├── stream-browserify@2.0.1 
  │ │ ├─┬ stream-http@2.6.3 
  │ │ │ ├── builtin-status-codes@3.0.0 
  │ │ │ ├── to-arraybuffer@1.0.1 
  │ │ │ └── xtend@4.0.1 
  │ │ ├── string_decoder@0.10.31 
  │ │ ├─┬ timers-browserify@2.0.2 
  │ │ │ └── setimmediate@1.0.5 
  │ │ ├── tty-browserify@0.0.0 
  │ │ ├─┬ url@0.11.0 
  │ │ │ ├── punycode@1.3.2 
  │ │ │ └── querystring@0.2.0 
  │ │ ├─┬ util@0.10.3 
  │ │ │ └── inherits@2.0.1 
  │ │ └─┬ vm-browserify@0.0.4 
  │ │   └── indexof@0.0.1 
  │ ├─┬ supports-color@3.2.3 
  │ │ └── has-flag@1.0.0 
  │ ├── tapable@0.2.6 
  │ ├─┬ uglify-js@2.7.5 
  │ │ ├── async@0.2.10 
  │ │ ├── uglify-to-browserify@1.0.2 
  │ │ └─┬ yargs@3.10.0 
  │ │   ├── camelcase@1.2.1 
  │ │   ├─┬ cliui@2.1.0 
  │ │   │ ├─┬ center-align@0.1.3 
  │ │   │ │ ├─┬ align-text@0.1.4 
  │ │   │ │ │ ├── longest@1.0.1 
  │ │   │ │ │ └── repeat-string@1.6.1 
  │ │   │ │ └── lazy-cache@1.0.4 
  │ │   │ ├── right-align@0.1.3 
  │ │   │ └── wordwrap@0.0.2 
  │ │   └── window-size@0.1.0 
  │ ├── watchpack@1.2.1 
  │ └─┬ yargs@6.6.0 
  │   ├── camelcase@3.0.0 
  │   ├─┬ cliui@3.2.0 
  │   │ └─┬ wrap-ansi@2.1.0 
  │   │   └─┬ string-width@1.0.2 
  │   │     └── is-fullwidth-code-point@1.0.0 
  │   ├─┬ os-locale@1.4.0 
  │   │ └─┬ lcid@1.0.0 
  │   │   └── invert-kv@1.0.0 
  │   ├── require-directory@2.1.1 
  │   ├── require-main-filename@1.0.1 
  │   ├─┬ string-width@1.0.2 
  │   │ ├── code-point-at@1.1.0 
  │   │ └─┬ is-fullwidth-code-point@1.0.0 
  │   │   └── number-is-nan@1.0.1 
  │   ├── which-module@1.0.0 
  │   ├── y18n@3.2.1 
  │   └── yargs-parser@4.2.1 
  ├─┬ webpack-dev-server@2.2.1 
  │ ├─┬ chokidar@1.6.1 
  │ │ ├─┬ anymatch@1.3.0 
  │ │ │ └── arrify@1.0.1 
  │ │ ├── async-each@1.0.1 
  │ │ ├── glob-parent@2.0.0 
  │ │ ├─┬ is-binary-path@1.0.1 
  │ │ │ └── binary-extensions@1.8.0 
  │ │ ├─┬ is-glob@2.0.1 
  │ │ │ └── is-extglob@1.0.0 
  │ │ └─┬ readdirp@2.1.0 
  │ │   └── set-immediate-shim@1.0.1 
  │ ├─┬ compression@1.6.2 
  │ │ ├─┬ accepts@1.3.3 
  │ │ │ └── negotiator@0.6.1 
  │ │ ├── bytes@2.3.0 
  │ │ ├── compressible@2.0.9 
  │ │ ├─┬ debug@2.2.0 
  │ │ │ └── ms@0.7.1 
  │ │ ├── on-headers@1.0.1 
  │ │ └── vary@1.1.0 
  │ ├── connect-history-api-fallback@1.3.0 
  │ ├─┬ express@4.14.1 
  │ │ ├── array-flatten@1.1.1 
  │ │ ├── content-disposition@0.5.2 
  │ │ ├── content-type@1.0.2 
  │ │ ├── cookie@0.3.1 
  │ │ ├── cookie-signature@1.0.6 
  │ │ ├─┬ debug@2.2.0 
  │ │ │ └── ms@0.7.1 
  │ │ ├── depd@1.1.0 
  │ │ ├── encodeurl@1.0.1 
  │ │ ├── escape-html@1.0.3 
  │ │ ├── etag@1.7.0 
  │ │ ├─┬ finalhandler@0.5.1 
  │ │ │ ├─┬ debug@2.2.0 
  │ │ │ │ └── ms@0.7.1 
  │ │ │ ├── statuses@1.3.1 
  │ │ │ └── unpipe@1.0.0 
  │ │ ├── fresh@0.3.0 
  │ │ ├── merge-descriptors@1.0.1 
  │ │ ├── methods@1.1.2 
  │ │ ├─┬ on-finished@2.3.0 
  │ │ │ └── ee-first@1.1.1 
  │ │ ├── parseurl@1.3.1 
  │ │ ├── path-to-regexp@0.1.7 
  │ │ ├─┬ proxy-addr@1.1.3 
  │ │ │ ├── forwarded@0.1.0 
  │ │ │ └── ipaddr.js@1.2.0 
  │ │ ├── qs@6.2.0 
  │ │ ├─┬ send@0.14.2 
  │ │ │ ├─┬ debug@2.2.0 
  │ │ │ │ └── ms@0.7.1 
  │ │ │ └── destroy@1.0.4 
  │ │ ├── serve-static@1.11.2 
  │ │ ├─┬ type-is@1.6.14 
  │ │ │ └── media-typer@0.3.0 
  │ │ └── utils-merge@1.0.0 
  │ ├─┬ http-proxy-middleware@0.17.3 
  │ │ ├─┬ http-proxy@1.16.2 
  │ │ │ ├── eventemitter3@1.2.0 
  │ │ │ └── requires-port@1.0.0 
  │ │ ├─┬ is-glob@3.1.0 
  │ │ │ └── is-extglob@2.1.1 
  │ │ └─┬ micromatch@2.3.11 
  │ │   ├─┬ arr-diff@2.0.0 
  │ │   │ └── arr-flatten@1.0.1 
  │ │   ├── array-unique@0.2.1 
  │ │   ├─┬ braces@1.8.5 
  │ │   │ ├─┬ expand-range@1.8.2 
  │ │   │ │ └─┬ fill-range@2.2.3 
  │ │   │ │   ├── is-number@2.1.0 
  │ │   │ │   ├── isobject@2.1.0 
  │ │   │ │   └── randomatic@1.1.6 
  │ │   │ ├── preserve@0.2.0 
  │ │   │ └── repeat-element@1.1.2 
  │ │   ├─┬ expand-brackets@0.1.5 
  │ │   │ └── is-posix-bracket@0.1.1 
  │ │   ├── extglob@0.3.2 
  │ │   ├── filename-regex@2.0.0 
  │ │   ├─┬ kind-of@3.1.0 
  │ │   │ └── is-buffer@1.1.4 
  │ │   ├── normalize-path@2.0.1 
  │ │   ├─┬ object.omit@2.0.1 
  │ │   │ ├─┬ for-own@0.1.4 
  │ │   │ │ └── for-in@0.1.6 
  │ │   │ └── is-extendable@0.1.1 
  │ │   ├─┬ parse-glob@3.0.4 
  │ │   │ ├── glob-base@0.3.0 
  │ │   │ └── is-dotfile@1.0.2 
  │ │   └─┬ regex-cache@0.4.3 
  │ │     ├── is-equal-shallow@0.1.3 
  │ │     └── is-primitive@2.0.0 
  │ ├─┬ serve-index@1.8.0 
  │ │ ├── batch@0.5.3 
  │ │ ├─┬ debug@2.2.0 
  │ │ │ └── ms@0.7.1 
  │ │ └─┬ http-errors@1.5.1 
  │ │   └── setprototypeof@1.0.2 
  │ ├─┬ sockjs@0.3.18 
  │ │ ├─┬ faye-websocket@0.10.0 
  │ │ │ └─┬ websocket-driver@0.6.5 
  │ │ │   └── websocket-extensions@0.1.1 
  │ │ └── uuid@2.0.3 
  │ ├─┬ sockjs-client@1.1.1 
  │ │ ├─┬ eventsource@0.1.6 
  │ │ │ └─┬ original@1.0.0 
  │ │ │   └── url-parse@1.0.5 
  │ │ ├── faye-websocket@0.11.1 
  │ │ ├── json3@3.3.2 
  │ │ └─┬ url-parse@1.1.7 
  │ │   └── querystringify@0.0.4 
  │ ├─┬ spdy@3.4.4 
  │ │ ├── handle-thing@1.2.5 
  │ │ ├── http-deceiver@1.2.7 
  │ │ ├── select-hose@2.0.0 
  │ │ └─┬ spdy-transport@2.0.18 
  │ │   ├── hpack.js@2.1.6 
  │ │   ├── obuf@1.1.1 
  │ │   └─┬ wbuf@1.7.2 
  │ │     └── minimalistic-assert@1.0.0 
  │ └─┬ yargs@6.6.0 
  │   ├── camelcase@3.0.0 
  │   ├── cliui@3.2.0 
  │   ├─┬ string-width@1.0.2 
  │   │ └── is-fullwidth-code-point@1.0.0 
  │   └── yargs-parser@4.2.1 
  ├── webpack-merge@2.6.1 
  ├── webpack-sources@0.1.4 
  └── zone.js@0.7.7 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @ngtools/webpack@1.2.9 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN @ngtools/webpack@1.2.9 requires a peer of @angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN @ngtools/webpack@1.2.9 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN @ngtools/webpack@1.2.9 requires a peer of @angular/tsc-wrapped@^0.5.0 but none was installed.

### Mention any other details that might be useful.

It doesn't seem like it caused an error in the npm install, but should I be concerned about the WARN messages resulting from unmet peer dependencies at the top of the tree? 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by taylorbasso** [comment]
Same error.

**Comment by fngpng** [comment]
Same error.

**Comment by alphaql** [comment]
Same error with OSX.

**Comment by DonYacos** [comment]
Same error here.

**Comment by ajscilingo** [comment]
same error as well in macOS Sierra 10.12.3

**Comment by Ib467** [comment]
similar to #4725 
https://github.com/angular/angular-cli/issues/4725

**Comment by iainplimmer** [comment]
Same error here too. macOS Sierra 10.12.3

**Comment by thabung** [comment]
+-- UNMET PEER DEPENDENCY @angular/core@2.4.8
+-- UNMET PEER DEPENDENCY @angular/http@2.4.8


Ubuntu 14.04

**Comment by piyushkathayat** [comment]
same error. any solution ?

**Comment by danny-36** [comment]
On windows 10 when try to install angular2-jwt

C:\WINDOWS\system32>npm install -g angular2-jwt
C:\Users\Daniele\AppData\Roaming\npm
+-- UNMET PEER DEPENDENCY @angular/core@^2.0.0
+-- UNMET PEER DEPENDENCY @angular/http@^2.0.0
+-- angular2-jwt@0.1.28
`-- UNMET PEER DEPENDENCY rxjs@^5.0.0

npm WARN angular2-jwt@0.1.28 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/http@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of rxjs@^5.0.0 but none was installed.

**Comment by UlyssesAlves** [comment]
@danny-36 Exact same error, except I'm not trying to install globally like you. My command differs from you just because yours have the -g flag/option. Out of that, the error here are pretty the same as yours:

`$ npm install angular2-jwt
prototipo-autenticacao-e-autorizacao@1.0.0 D:\Ulysses\Estudo\ASP.NET Web API\Seguranca\ServidorDeAutorizacao\Cliente
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.6
+-- UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.6
+-- angular2-jwt@0.1.28
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11

npm WARN angular2-jwt@0.1.28 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/http@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of rxjs@^5.0.0 but none was installed.
`

**Comment by jdufner** [comment]
Same error, any solution?

**Comment by MAJLGC** [comment]
angular-cli: 1.0.0-beta.28.3
node: 6.10.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32
@angular/compiler-cli: 2.4.8

npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN @angular/core@2.4.8 requires a peer of rxjs@^5.0.1 but none was installed.

**Comment by JimTheMan** [comment]
I'm getting this error too. :(

**Comment by troydcthompson** [comment]
I'm hurt. I've got the same issue.

**Comment by MAJLGC** [comment]
I solve my issue installing rxjs@^5.0.1 manually (with npm)

**Comment by shawnvoseRP** [comment]
@MAJLGC sometimes is the simple error message that gives it away! I did the same thing and it resolved my issue. I am on OSX as.

**Comment by vicatcu** [comment]
@MAJLGC acknowledge, 
for me:
npm install -g rxjs@^5.0.1
then ...
npm install -g @angular/cli 

... results in no peer dependency warnings.

**Comment by Arch88** [comment]
├── @angular/cli@1.0.0-rc.0 
├── UNMET PEER DEPENDENCY @angular/common@^2.0.0
├── UNMET PEER DEPENDENCY angular@1.6.2
├── UNMET PEER DEPENDENCY angular-animate@1.6.2
├── UNMET PEER DEPENDENCY angular-aria@1.6.2
├── angular2-fontawesome@0.8.0  extraneous
├── UNMET PEER DEPENDENCY css-loader@0.19.0
├── file-loader@0.9.0 
├── nvm@0.0.4  extraneous
├── postcss-loader@1.3.2 
├── style-loader@0.12.4 
└── url-loader@0.5.8 
:(

**Comment by UlyssesAlves** [comment]
@MAJLGC Globally installing rxjs and @angular/cli worked for me too. Thanks!

**Comment by avalonabecker** [comment]
Same issue here:
El Capitan 10.11.6
Node 6.9.5
NPM 3.10.10

**Comment by filipesilva** [comment]
Fixed in newer releases. There should be no peerdep problems anymore. Sorry about that.

**Comment by rinoldit** [comment]
i get 

UNMET PEER DEPENDENCY @angular/common@2.4.10
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.10
├── UNMET PEER DEPENDENCY @angular/core@2.4.10
└── UNMET PEER DEPENDENCY @angular/platform-browser@2.4.10

but after checking the ng --version i get : 
@angular/cli: 1.0.0
node: 7.7.2
os: linux x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

i think it is an update issues of separate packages  or Modules!!!

I think we should completely uninstall angular cli globally and install the latest version using @latest suffix.

**Comment by ryanaltvater** [comment]
@filipesilva "There should be no peerdep problems anymore."

I'm still getting the "npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed" error, even after installing angular-cli@latest. Am I missing something?

**Comment by ryanaltvater** [comment]
@filipesilva Never mind...installing @angular/cli is the new way to go and does not give that error. My mistake. :)

**Comment by SarahWallis** [comment]
I'm also having this issue, but additionally am getting an empty response. Any ideas on what the  `-- (empty) means or how to fix? Thanks.
>npm i rxjs@^5.0.1
```
project@0.0.0 C:\Users\n9148387\Documents\My Web Sites\RICI\src\RICI
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/core@2.3.1 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/http@2.3.1 requires a peer of @angular/platform-browser@2.3.1 but none was installed.
npm WARN @angular/router@3.0.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN The package typescript is included as both a dev and production dependency.
```

**Comment by canada11** [comment]
I had the same thing. Found out it was because I updated some of the @angular/ packages and not others. My fix was deleting the node modules folder and running `npm install` again. My issue was in relation to not knowing or having a good way to update and I found/like this feature request: https://github.com/angular/angular-cli/issues/5919 Which is about having some way to let developers know about new version releases and a quick and easy way to upgrade like with `ng update`

**Comment by diegonobre** [comment]
Just follow update guide https://github.com/angular/angular-cli#updating-angular-cli

**Comment by linuradu** [comment]
I've got the error:
UNMET PEER DEPENDENCY @angular/common@4.1.0
├── UNMET PEER DEPENDENCY @angular/compiler@4.1.0
├── UNMET PEER DEPENDENCY @angular/core@4.1.0
└── UNMET PEER DEPENDENCY @angular/platform-browser@4.1.0

I've tryed with "npm install" and finally after using "npm prune" worked fine "npm install" and I could install angular 4.

**Comment by shivshaktiss17** [comment]
getting the same error...nothing helped...

**Comment by linuradu** [comment]
The worse case, try to remove node_modules folder and again "npm install". Probably there is still something cashed.

**Comment by PeterDavidCarter** [comment]
This issue appears to be back...

**Comment by PeterDavidCarter** [comment]
If anyone has this problem with the newer versions make sure you are running `npm install -g @angular-cli/cli` not `npm install -g angular-cli`.

**Comment by Allajah** [comment]
I'm getting the same error. I installed the latest version of `@angular/cli` and did `rm -rf node_modules` and `npm install`

**Comment by TCB13** [comment]
Running into this error while running `sudo npm install -g @angular/cli` on latest (non-beta) macOS.

**Comment by shmoon2917** [comment]
same issue :(

**Comment by filipesilva** [comment]
`@angular/cli@1.2.2` has a peer dependency issue that is being tracked in https://github.com/angular/angular-cli/issues/7078. Please subscribe to that thread for updates specific to this version.

**Comment by KhizerRehan** [comment]
can anyone help? Even though i have installed @angular/cli latest still giving error on UNMET PEER DEPENDECIES ISSUSE! 
![screenshot_4](https://user-images.githubusercontent.com/17727069/28612890-7f32ca74-71a5-11e7-812a-6a282a706091.png)
![screenshot_5](https://user-images.githubusercontent.com/17727069/28612889-7f32969e-71a5-11e7-87b5-cf0ede4e4deb.png)

**Comment by filipesilva** [comment]
@KhizerRehan there is no peer-dependency issue with `@angular/cli` itself currently. The peer dependencies you have right now are due to your project dependencies. 

You should read through the errors that NPM shows you and provide the appropriate peer dependencies in `package.json`. You can read more about it https://nodejs.org/en/blog/npm/peer-dependencies/.

**Comment by ssalehi** [comment]
same error :(((

**Comment by tankala** [comment]
I faced same error
Below steps helped me. I hope these will help you also

npm update
npm uninstall -g angular-cli
npm cache clean
npm install -g @angular/cli

**Comment by linuradu** [comment]
Hi @tankala,
Did you tried to add in:
```
"dependencies": {
    ...
    "@angular/compiler-cli": "4.1.0",
}
```
and
```
"devDependencies": {
    ...
    "@angular/cli": "1.2.1",
    "@angular/compiler-cli": "4.1.0"
}
```
afterwards to run: 
```
npm prune
eventually: npm cacle clean
and: npm install
```

**Comment by tankala** [comment]
Hi @linuradu ,

I think I didn't typed properly. I got this problem and I solved this problem by using these steps

npm update
npm uninstall -g angular-cli
npm cache clean
npm install -g @angular/cli

**Comment by fetahokey** [comment]
same error here !
-------------------

**1. - C:\WINDOWS\system32>npm install -g angular-cli
2. - npm WARN deprecated angular-cli@1.0.0-beta.28.3: angular-cli has been renamed to @angular/cli. Please update your dependencies.
3. - npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
4. - C:\Users\Fetah\AppData\Roaming\npm\ng -> C:\Users\Fetah\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
5. - C:\Users\Fetah\AppData\Roaming\npm
6. - `-- angular-cli@1.0.0-beta.28.3
7. -   `-- UNMET PEER DEPENDENCY rxjs@^5.0.1
8. - 
9. - npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
10. - npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
11. - npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.**

**Comment by pstephenwille** [comment]
Yea!  Had this issue on Ubuntu but running `npm update` seems to have fixed it.

**Comment by b0rgbart3** [comment]
I'm still having UNMET PEER DEPENDECY issues...
UNMET PEER DEPENDENCY @angular/common@4.4.6
├── UNMET PEER DEPENDENCY @angular/core@4.4.6

I tried tankala's suggestion of runing npm update, uninstalling the cli, cleaning the cache and re-installing the cli -- and I also put 4.4.6 into my package.json for both of these -- 
`npm install` by itself works fine
but 
`npm i --save ngx-facebook `
--generates these two UNMET PEER DEPENDENCY error messages.

**Comment by Fthi-S3074641** [comment]
It worked with
First
        
    sudo npm prune rxjs angular/cli OTHERs
Second
        
    sudo npm i -g rxjs angular/cli OTHERs
