### ISSUE TITLE
ng run error on ubuntu

### ISSUE THREAD

**Issue by SomboChea** [angular/angular-cli#4809]
root@localhost:$ ng
/usr/local/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:33
            result.push(...indices);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/index.js:2:30)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

> How to resolve it! Please me! on Ubuntu 16.04 LTS

**Comment by iainplimmer** [comment]
Just installed the CLI myself this morning from an 'npm install -g angular-cli' and i get exactly the same issue when running 'ng new'.

I'm on MacOS though.

**Comment by Ionaru** [comment]
You should be using `npm install -g @angular/cli`

**Comment by iainplimmer** [comment]
Same problem after running the above command. 'ng new' just gives the following: 

iains-iMac:git iain$ ng new iainsangular
/usr/local/lib/node_modules/@angular/cli/models/config/config.js:15
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/config.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by skinsvideos21** [comment]
This seems to be occurring too on Win10, with the following:

Node v4.4.7
NPM v4.2.0

Strangely, **ng --v** causes the same error to pop up.

**Comment by Ionaru** [comment]
And this is why you use the issue template... Especially the 'Versions' section.

Node 4.4.7 is basically ancient at this point. Angular CLI uses new Javascript features that aren't available in Node 4. 
Upgrade Node to 6.9.5 LTS or above.

**Comment by dkinsbursky** [comment]
Thanks Ionaru.  Upgraded to v6.9.0 and error immediately disappeared.

**Comment by thojo** [comment]
[CLI Quickstart at angular.io](https://angular.io/docs/ts/latest/cli-quickstart.html) still mentions _at least node 4.x.x_ in Step 1.

**Comment by Ionaru** [comment]
@thojo Actually the information has been changed on Github, but the website hasn't updated yet.

**Comment by laguiz** [comment]
I fixed it with updated version of nodejs `npm install npm@latest -g`

**Comment by filipesilva** [comment]
Yeah I'm sorry about that, it took us a while to update the CLI quickstart. The problem really was node and npm version.

**Comment by sghaleb1** [comment]
Had the same issue; I updated npm but that didnt solve the issue.
So I uninstalled node.js from my computer and installed again, which fixed the problem.

**Comment by TheNuclearCat** [comment]
Same problem with ubuntu, even if you use the newest package via repo install it has still the version 4.X
Check your node version `node --version`
Or better use node version manager (nvm)

**Comment by cdvillagra** [comment]
Try this guys...

npm cache clean -f
npm install -g n
n stable

**Comment by Ionaru** [comment]
Ubuntu does not upgrade major NodeJS versions, you have to redo the installation steps to install a newer major version.

For example the commands below will install NodeJS 6

```bash
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

And these commands below will install NodeJS 8

```bash
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Notice the curl link changed from 6 to 8.

**Comment by LeonardoSSev** [comment]
lonaru, you comment helped me a lot. Thanks very much!

**Comment by wdranjeet** [comment]
I have same issue on Ubuntu 16.04, @Ionaru  comment solve my issue, thanks,

**Comment by ekstremedia** [comment]
@Ionaru's comment solved this for me on ubuntu 17.04. Reason for angular-cli not working was that legacy node was installed. Thank you ionaru!

**Comment by deepakpookkote** [comment]
how to update the node ..???  i have tried all the ways to update or upgrade still my node version is 
v4.2.6?? wt should i do?

**Comment by pjdufour** [comment]
You're probably running into the issue with `node` and `nodejs` pointing to different installs.  If you tried the following below, then the new version is `node` and you can remove `nodejs`.

```
npm cache clean -f
npm install -g n
n stable
```

Side note, I had to run `npm install @angular/cli` to my local working directory and then to my global too at `sudo npm install -g @angular/cli`.

**Comment by lrkwz** [comment]
If you follow the [apt install](https://nodejs.org/en/download/package-manager/) I would suggest to remove any locally installed node first:

    sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}

**Comment by bclincy** [comment]
Thank you Ionaru you the new repo and update worked well for me.
