### ISSUE TITLE
Cannot read property 'glob' of null

### ISSUE THREAD

**Issue by Nidhi08** [angular/angular-cli#5505]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

ng --version
@angular/cli: 1.0.0-rc.2
node: 6.10.0
os: darwin x64

npm -v
3.10.10

MacOs = Sierra

### Repro steps.

If I execute ng new as root/administrator then I get this error.
If I don't execute ng new as root then the project is created successfully, but I get this error while executing ng build and ng serve --open.

### The log given by the failure.

Nidhis-MacBook-Pro:hello nidhisakhala08$ ng serve --open
Cannot read property 'glob' of null
TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:224:131)
    at new ObjectSchemaTreeNode (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:209:14)
    at OneOfSchemaTreeNode._createChildProperty (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:161:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:160:48)
    at ArraySchemaTreeNode._createChildProperty (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
    at ArraySchemaTreeNode._set (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:286:39)
    at new ArraySchemaTreeNode (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:267:14)
    at ObjectSchemaTreeNode._createChildProperty (/Users/nidhisakhala08/Desktop/hello/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)

### Mention any other details that might be useful.

I read multiple issues related to this problem but they are on Ubuntu so I am posting this as a new issue.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/4207, fixed in https://github.com/angular/angular-cli/pull/5523, out next release.

**Comment by Nidhi08** [comment]
I downloaded the next release by installing @angular/cli@latest.
I still get the same error.

**Comment by balr404** [comment]
I have tried the following option to resolve the issue
Steps to resolve the issue

$ pwd
it shows —> /Users/YourName /*** That is your Home path***/
Execute the below command to display the hidden files

$ defaults write com.apple.Finder AppleShowAllFiles true
$ killall Finder
After executing the above command you will see the hidden files.
if “.angular-cli.json” file exist under “/Users/yourname” (i.e Home Path) then remove “.angular-cli.json” file.

then navigate to your application path and try execute ‘ng’ command.
