### ISSUE TITLE
Bug: Code Coverage Report

### ISSUE THREAD

**Issue by JWO719** [angular/angular-cli#5526]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
$ ng --version
@angular/cli: 1.0.0-rc.2
node: 6.9.5
os: win32 x64
@angular/common: 4.0.0-rc.5
@angular/compiler: 4.0.0-rc.5
@angular/core: 4.0.0-rc.5
@angular/forms: 4.0.0-rc.5
@angular/http: 4.0.0-rc.5
@angular/platform-browser: 4.0.0-rc.5
@angular/platform-browser-dynamic: 4.0.0-rc.5
@angular/router: 4.0.0-rc.5
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.0-rc.5

### Repro steps.
I have made a sample project, to reproduce this weird behaviour.
Please take a look at: https://github.com/Loster102/angular-coverage-sample
When I run 'ng test -cc true', there is a successful testrun.
But when I look at the coverage report, the branch coverage is really strange.
It says, that the constructor is not fully covered. 
![sample](https://cloud.githubusercontent.com/assets/6104311/24119839/ccb5a872-0db2-11e7-9b5c-2b24c275c55d.PNG)

### Desired functionality.
I would have expected that even the constructor is fully covered.

### Mention any other details that might be useful.
In my real world application, there are some further strange behaviours, exactly like the one above. 
I try to reproduce these in the sample project. In this application, I'm using angular@4.0.0-rc.2 and @angular/cli@1.0.0-rc.1.

**Comment by hotforfeature** [comment]
There are two related issues both in Istanbul and TypeScript:
https://github.com/gotwarlost/istanbul/issues/690
https://github.com/Microsoft/TypeScript/issues/13455

The latest suggestion from both threads is to run tests with coverage targeting ES6 instead of ES5. Unfortunately from what I can tell, the Angular CLI doesn't use `tsconfig.json` when running tests, and the suggestions of using `--compilerOptions '{\"target\":\"es6\"}'` won't work since Angular CLI doesn't recognize that.

At the moment, there's nothing to do, adding `/* istanbul ignore next */` comments everywhere around the constructor won't help. We're deadlocked while waiting for Angular, Istanbul, or TypeScript to change something.

**Comment by filipesilva** [comment]
If there's something we can do to help, we'd like to.

**Comment by stratus1011** [comment]
@hotforfeature you can actually change the "target" to es6 in the src/tsconfig.spec.json with the  version of angular cli that you are using. However, if you are running tests on phantomjs it will fail due to the "const" keyword/ES6/ES2015 not being supported yet. There is a beta version of phantomjs that they have released that you could try which should have support for it, but may have other issues.

**Comment by sandman21dan** [comment]
tsconfig.spec file has es6 as a target, running on CLI-1.0.0 still get all the missing branches from all the constructors, maybe I'm missing something?

**Comment by cpa-level-it** [comment]
I have the same problem as @sandman21dan.
Changed target from es5 to es6 in tsconfig.spec.json and constructor branches are still not covered.

Any idea ?

**Comment by raguilera82** [comment]
Any solutions? It is really frustrating :/

**Comment by SURENDARREDDY** [comment]
Since it is being 2 months, just want to know the progress.
Is there any ETA for this issue resolution?

**Comment by cortopy** [comment]
Changing `target` to es6 in the main tsconfig.json doesn't work either

**Comment by rdsedmundo** [comment]
Same problem here.

**Comment by PhillipZada** [comment]
Anyone got anything on this issue resolution ?

**Comment by dinvlad** [comment]
Changing to es6 doesn't work here as well. Is there a feasible solution in the works?

**Comment by rg1220** [comment]
Reproduced this issue by simply adding `http: HTTP` to the constructor of a newly created project created with angular-cli: https://github.com/rg1220/angular-cli-coverage-issue-5526

<img width="609" alt="screen shot 2017-07-02 at 9 20 11 am" src="https://user-images.githubusercontent.com/6728645/27770165-b1885d46-5f07-11e7-99d2-d5fc2a95a17a.png">

**Comment by brunolm** [comment]
I have the same issue :( ... Why is it blocked? Can we expect a fix in the near future?

**Comment by UnkJester** [comment]
Can we get a status update on this? This is blocking my ability to check in changes as the branches fails imposed standards...

**Comment by UnkJester** [comment]
I'm reading from other issues that it may be testing branches inside of super() calls. Is there any info why /*istanbul ignore next*/ is not working on constructors? Can we get a reason on the blocked label?

**Comment by brunolm** [comment]
## Workaround

As a **workaround** I found the special comment `/* istanbul ignore next */`

If you place after your class, the constructor gets ignored.

Example

```
export class InternalComponent {
    constructor(private authService: any) { 
    }
} /* istanbul ignore next */
```

Generates

```
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var InternalComponent = (function () {
        function InternalComponent(authService) {
            this.authService = authService;
        }
        return InternalComponent;
    }()); /* istanbul ignore next */
    exports.InternalComponent = InternalComponent;
});
```

Which ignores this line `exports.InternalComponent = InternalComponent;` that causes the issue.

To ignore **super**

```
super() /* istanbul ignore next */;
```

If you have generics and/or `@Inject` in your constructor params, try to break lines.

With those hacks I got 100% coverage.

**Comment by davinkevin** [comment]
@brunolm This workaround works if you don't use decorator on attribute in your code. 

![image](https://user-images.githubusercontent.com/1970922/29904527-8b2c8ab0-8e09-11e7-8eac-c78a0aabc23a.png)

If I remove the `@Effect` I have 100% coverage... do you have an idea ?

**Comment by filipesilva** [comment]
Heya, just wanted to mention that I added the `blocked` tag because I spent some time trying to fix it and as far as I can tell this is a limitation of the code coverage tools right now. @hotforfeature's comment (https://github.com/angular/angular-cli/issues/5526#issuecomment-288095948) explains the current situation well, I couldn't find any further developments.

Using an es6 target is not a real solution per se either, overall the CLI doesn't really support outputting es2015 (see https://github.com/angular/angular-cli/issues/2907),

**Comment by UnkJester** [comment]
Is there any other update? Has this been raised with the code coverage tools support? (I'm a bit new to this) I'm getting the issues @davinkevin mentioned, which breaks the only known workaround (other than lowering the branch requirement, which I'm being told is unsavory.

**Comment by kenisteward** [comment]
@filipesilva does #7610 now resolve this in the sense that we can provide es2015 for code coverage to run and it should work?

**Comment by webcat12345** [comment]
@brunolm , it works but `/* istanbul ignore next */` what does this hack do exactly?

**Comment by brunolm** [comment]
@webcat12345 `/* istanbul ignore next */` ignores the line bellow in the coverage. https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md

Following my instructions it will place the ignore statement exactly at a part of the generated code that is not being accessed.

It is a really ugly workaround and might not work in all cases.

**Comment by webcat12345** [comment]
Thanks @brunolm 
![image](https://user-images.githubusercontent.com/19761422/31908121-2c6dd798-b836-11e7-9111-bc0aa54ef77c.png)
Because of above kinds of issue, I was going to apply this hack to everywhere lol. you saved my life.

**Comment by kenisteward** [comment]
do note @webcat12345  @brunolm when they add --aot support to  ngtest then we'll be able to target es2015 from the resolved #7610 and it will fix everything for tests.

**Comment by dinvlad** [comment]
For some reason, after upgrading to 1.5 RC 8 (not sure about previous RCs though) the problem has gotten worse - now it also excludes imports from test coverage, like so:
![image](https://user-images.githubusercontent.com/137337/32251705-8f733dfa-be68-11e7-8a89-ef51dcf5daae.png)

As a result, my test coverage decreased from 95% to the dangerous 82% :(

**Comment by dinvlad** [comment]
With the release versions (Angular 5.0.0 and CLI 1.5) all coverage now appears perfect! There was a transient remap problem due to something in RC 8 and/or possibly TS>2.4. Is everyone's else experience the same?

**Comment by filipesilva** [comment]
@dinvlad that's somewhat surprising to me, because I haven't actually added any fixes in 1.5.0 for this. But maybe the change in compiler pipeline helped somehow, or one of the dependencies that does coverage had fixes in it. 

Can you share if added any workarounds or modifications in your project to address the coverage problems?

**Comment by filipesilva** [comment]
Now that I think about it, @hansl fixed a problem with sourcemaps in https://github.com/angular/angular-cli/pull/8230. Maybe that was the root cause of this issue in the first place.

Can other people confirm if your codeverage is now correct?

**Comment by rg1220** [comment]
@filipesilva - I can confirm it fixed the issue with constructors. I assume other similar issues were caused by the same thing.

I updated my test repo to Angular 5 and the coverage report is now correct:
https://github.com/rg1220/angular-cli-coverage-issue-5526/tree/feature/update-to-angular-5
<img width="625" alt="screen shot 2017-11-03 at 8 44 16 am" src="https://user-images.githubusercontent.com/6728645/32374309-6d72fb7a-c073-11e7-997c-ff10f7fca5b0.png">

**Comment by dinvlad** [comment]
@filipesilva I just made sure that all tsconfig files are identical to the auto-generated ones from a new project. No workarounds required.

**Comment by kenisteward** [comment]
I'm using 4.4.6 until a library i'm using fixes a deprecated API.  Just chiming in that CLI 1.5.0 and NG 4.4.6 does not correct it.  I think you may have to specifically be on NG5.0

**Comment by FaniloRandria** [comment]
I confirm that angular 5 solves the problem.
I move from:
- angular 4.4.6 to 5.0.0
- angular/cli 1.4.9 to 1.5.0
- nguniversal 1.0.0-beta.3 to 5.0.0-beta.5
- angular/flex-layout 2.0.0-beta.9 to 2.0.0-beta.10

and I can reach 100% code coverage on branches now.

Before:
<img width="993" alt="capture d ecran 2017-11-05 a 09 12 25" src="https://user-images.githubusercontent.com/16125061/32415549-87129af8-c209-11e7-9134-4e820fe25205.png">

After:
<img width="992" alt="capture d ecran 2017-11-05 a 09 12 05" src="https://user-images.githubusercontent.com/16125061/32415552-8cd25f0a-c209-11e7-8968-d249c0db5699.png">

I just don't understand the line src/app, it dropped down to 0%.
Here's my [project](http://github.com/kyptrack/frontend)

**Comment by brunolm** [comment]
I [upgraded to Angular 5](https://github.com/brunolm/angular-how-to/pull/6/files) in a big project.

Almost everything worked without workarounds, there is just one scenario where it didn't work:

![image](https://user-images.githubusercontent.com/706078/32417627-4d1c102e-c243-11e7-9e6e-8ece8a5c4d5c.png)

One of the tests for it:

```
it('calls setLocale', () => {
  spyOn(MomentDateAdapter.prototype, 'setLocale').and.callThrough();

  const adapter = new MomentDateAdapter();

  expect(adapter).toBeDefined();
  expect(MomentDateAdapter.prototype.setLocale).toHaveBeenCalledWith('pt-BR');
});
```

That's the only thing that didn't work for me.

Great job, Angular 5 is awesome :)

**Comment by laxu** [comment]
I'm still experiencing the constructor issue when using Jest with Angular 5.0 and jest-angular-preset. Setting `tsconfig.spec.json` target to es6 does not seem to have any effect.

**Comment by el-davo** [comment]
Also still experiencing this issue event after moving to angular 5. Its even highlighting comments as not being tests :(

**Comment by kenisteward** [comment]
@el-davo did you also upgrade to click 1.5.0?

**Comment by el-davo** [comment]
Am completely wrong it seems I had -sm set to false which was completely throwing the coverage off. My bad, Angular 5 FTW!!

**Comment by laxu** [comment]
@kenisteward Yup, cli is 1.5.0 too.

**Comment by kenisteward** [comment]
@filipesilva I can confirm after upgrading to Angular 5 and CLI 1.5.0 I also got full coverage for the constructors when before i was getting issues.

**Comment by Brototype** [comment]
@laxu did you find a solution for that issue with jest? I'm facing the same issue :(

**Comment by laxu** [comment]
@Brototype Unfortunately no. In the mean time you have to either use the `/* istanbul ignore next */` workaround or lower branch coverage to account for the issue.

**Comment by filipesilva** [comment]
I'm closing as it seems this is fixed with 1.5.

**Comment by nabeelgit** [comment]
I resolved it by running the unit test environment in full privileged mode

**Comment by otroboe** [comment]
Hey guys !
So de we know how Angular 5 fixed this issue... ? :-P

**Comment by kenisteward** [comment]
Yeah has to do with the annotations now being parsed as typescript
transformations instead. I'll try to find the article but it now doesn't
put the same ternary operators which were found in the code coverage for
constructors and input/outputs

**Comment by vigohe** [comment]
@laxu have you fix this when using jest????

**Comment by otroboe** [comment]
For me with Jest `22.3.0`, I just added this property in my `jest.json` config file:
```
{
  ...
  "mapCoverage": true
}
```

**Comment by AhnpGit** [comment]
@otroboe Angular 5 fixed the issue but only when testing with karma + jasmine, with Jest I also experience the same issue. @filipesilva can you tell us exactly what was the fix in Angular 5 ?

**Comment by kenisteward** [comment]
I don't believe that jest is covered by the cli. In which case this doesn't
belong here but on stack overflow.

**Comment by escorter** [comment]
+1

**Comment by mboughaba** [comment]
It seems most of the issues are solved nevertheless we are still experiencing same issue like @brunolm mentioned
![image](https://user-images.githubusercontent.com/3800584/37520694-57baf256-291e-11e8-92cc-c6f27bc87fa5.png)

**Comment by kellycrowther** [comment]
We are experiencing this in our project with constructors and decorators. Running angular 5.2.8, angular-cli 1.7.3, jasmine 3.1.0 running with karma.

**Comment by rousseaufiliong** [comment]
I resolve the problem by targetting es6 in tsconfig.spec.json
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es6",
    "types": ["jasmine", "node"]
  },
  "files": ["test.ts"],
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```

**Comment by macbem** [comment]
Just make sure that you have sourcemaps turned on for your tests and coverage will work fine.

**Comment by mboughaba** [comment]
@macbem Not the case for me, the experience this problem with and without sm flag.

**Comment by kellycrowther** [comment]
Thanks for the suggestions @macbem and @rousseaufiliong. I previously tried those suggestions along with the other suggestions in this thread like adding `/* istanbul ignore next */` and I tried again today for good measure but still find coverage is low for branches because of constructors and decorators. Hopeful an update solves this for our project

**Comment by tedp** [comment]
Is a fix on the way?

**Comment by victormejia** [comment]
I experience this problem with having source maps turned off for testing.

**Comment by rafaelnery** [comment]
@filipesilva with version 1.7.4 the problem continues :(

**Comment by kbui-prosper** [comment]
The problem persists and I can't seem to find a work-around
```
/* istanbul ignore next */
  /* istanbul ignore next */ constructor( /* istanbul ignore next */
    /* istanbul ignore next */ private /* istanbul ignore next */ appDataService: /* istanbul ignore next */ ApplicationDataService /* istanbul ignore next */, /* istanbul ignore next */
    /* istanbul ignore next */ private /* istanbul ignore next */ appWorkflowService: /* istanbul ignore next */ ApplicationWorkflowService /* istanbul ignore next */, /* istanbul ignore next */
  ) /* istanbul ignore next */ {/* istanbul ignore next */} /* istanbul ignore next */
```

**Comment by mcblum** [comment]
We're also still seeing the same problem, Angular 5.2.6, Jest 22.4.3 and Jest Angular Preset 5.2.2. For whatever reason, it's not all the time, but there are issues where some of the params in a constructor will be uncovered. It doesn't seem to make a lot of sense, because it's not consistent.

**Comment by soates** [comment]
Also seeing this behaviour as described by @mcblum

**Comment by dimitriy-k** [comment]
indeed, after adding ` --sourcemaps=false` coverage started giving wrong numbers (cli 1.7.4, target es5). When you remove it, coverage is ok.

![screenshot from 2018-06-20 10-55-28](https://user-images.githubusercontent.com/3017341/41648974-9eaf7bb2-747a-11e8-94c4-c253214d13d0.png)

**Comment by russcarver** [comment]
Same issues with Angular 5.2.11, Jest 23.1.0 and jest-preset-angular 5.2.2.   All the istanbul packages pulled in (inspected via package-lock.json) also appear to be the latest.

            "istanbul-api": "^1.3.1",
            "istanbul-lib-coverage": "^1.2.0",
            "istanbul-lib-instrument": "^1.10.1",
            "istanbul-lib-source-maps": "^1.2.4",

**Comment by aleh-vasilyeu** [comment]
Why is this issue closed?! 
The problem still remains, here is an example of an empty component: 
![image](https://user-images.githubusercontent.com/42133783/50823403-f293ff00-1344-11e9-9b0f-a0af6a864565.png)

How can I fix this? Thanks.

**Comment by rmorrise** [comment]
We fixed this by modifying `angular.json` to add the `sourceMap` flag:

The flag should be added under the following path: `projects.my-app.architect.test.sourceMap`

```
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [],
            "styles": [
              "src/styles.css"
            ],
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ],
            "sourceMap": true // <-- Add this flag!!
          }
        },
```

**Comment by rmorrise** [comment]
Angular CLI team reported that newer CLI versions will correct this automatically:
https://github.com/angular/angular-cli/issues/13093

**Comment by Javin007** [comment]
Angular CLI team lies.  I'm running the latest angular/jest and still seeing this problem.  NONE of the above "solutions" work.  I've tried /* istanbul ignore next */, sourcemaps (both on and off) setting the target to es6, even adding the deprecated "mapcoverage" setting.  Nothing works.  Problem still exists without so much as a workaround.  This is not a "closed" bug.

**Comment by ruimarques** [comment]
> Angular CLI team lies. I'm running the latest angular/jest and still seeing this problem. NONE of the above "solutions" work. I've tried /* istanbul ignore next */, sourcemaps (both on and off) setting the target to es6, even adding the deprecated "mapcoverage" setting. Nothing works. Problem still exists without so much as a workaround. This is not a "closed" bug.

Before calling a team as liars consider for a moment that you might be missing something or maybe you have encountered an edge case unknown to the community. If you provide a minimum reproducible example (created in stackblitz for instance) it would be more helpful to get your problem sorted out.

**Comment by mcblum** [comment]
@Javin007 bro... come on. These are some of the most capable people working on software today, so the chances that they are lying to cover up a bug that, at its core, leads to an incorrect coverage report number are almost 0. 

I'm using the latest CLI and Jest and ignore next works just fine. I would guess there is something else wrong with your setup.

Please consider the tone you take when commenting on projects which are free for you to use. No one owes you a fix, we're all in this together, and people are doing their best.

**Comment by Javin007** [comment]
@mcblum @ruimarques  

I'm sorry if I come off as a bit irritated, but this is a very easily duplicated bug: 

1.) Create new "hello world" project.
2.) Install Jest.
3.) Inject HttpClient into the app.component.ts
4.) Run tests with code coverage.

I JUST did it again to verify.  It literally happens every time.  On multiple versions of angular, and on every environment.  And I've spent the last 48 hours searching for a solution, and have tried every single "fix" found on google to no avail.  And this has been a problem for quite some time.  

I'm not even saying it's specifically the Angular team's fault.  It could very likely be a problem with Jest.  However, claiming that "it's fixed" when it's not, and it's so easily duplicated is not helpful.  Especially when I see numerous posts on numerous different sites (and even in this thread) claiming so without doing the very basic test outlined above.  This original post was from March of 2017.  It's now February of 2019, and this thread is a history of people continuing to have the exact same problem without a solution at any time.  So this isn't just some problem that "cropped up again."

And yes, I'm irritated at spending two days of seeing people saying "it's fixed" when it simply isn't, and none of the MANY, MANY proffered solutions (everything from creating an entirely new project, to reinstalling angular) are anything but a waste of time.  This kind of hand-waving away of the problem doesn't get it solved (obviously, since we're now on year two of the same issue).  

If you actually have a solution that fixes the problem, then I and the many other people suffering from this problem would very much love to hear it.  If you're not having this issue, then what is it that you're doing differently from the above steps?  We would very much like to know.

**Comment by mcblum** [comment]
@Javin007 since even the steps you list above could result in a different version being installed on my machine than yours, could you please put the exact configuration in a StackBlitz so one of us can grab the code and see what's up? When you say "install jest" there are 1,000 different options, stable vs. alpha version of `jest-preset-angular` and a bunch of other things that can change, so put your exact configuration in a SB and we can see how you're getting the issue you're getting.

Once again, I'm currently, as I type, working on a large project using Angular CLI + Jest + Istanbul and all of my ignore statements work correctly.

**Comment by ahnpnl** [comment]
I will drop one cent here:
- first of all, the issue with coverage constructor when using jest with Angular CLI isn't in Angular CLI fix because Angular CLI only fixed for karma + Jasmine.
- jest-preset-angular 7.0.0-alpha.1 fixed the issue with coverage when using jest. However we are trying to make jest-preset-angular to be compatible with jest 24 at the same time. Being compatible with jest 24 + alpha version work are 2 big breaking changes and require some times to release an official version.

**Comment by Javin007** [comment]
FWIW: Here's a project that has the problem: https://yqnigwvz.github.stackblitz.io

**Comment by mcblum** [comment]
@Javin007 could you try with the following:
```
"jest": "^23.6.0",
"jest-preset-angular": "7.0.0-alpha.2",
```
You will need to change your jest config when you update to the alpha of `jest-preset-angular`. It looks something like this:
```
"jest": {
    "preset": "jest-preset-angular",
    "setupFiles": [
      "jest-canvas-mock"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/config/jest/config.ts",
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!@ngrx|@agm)"
    ],
    "transform": {
      "^.+\\.js": "<rootDir>/node_modules/babel-jest",
      "^.+\\.(ts|html)$": "ts-jest"
    },
    "globals": {
      "ts-jest": {
        "tsConfig": "<rootDir>/tsconfig.spec.json",
        "diagnostics": false,
        "stringifyContentPathRegex": "\\.html$",
        "astTransformers": [
          "jest-preset-angular/InlineHtmlStripStylesTransformer.js"
        ]
      },
      "window": true
    },
    "modulePathIgnorePatterns": [
      "<rootDir>/coverage/",
      "<rootDir>/.storybook/",
      "<rootDir>/config/",
      "<rootDir>/dist/",
      "<rootDir>/e2e/",
      "<rootDir>/node_modules/"
    ],
    "collectCoverageFrom": [
      "{apps|libs}/**/src/**/*.ts"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 90,
        "branches": 90,
        "functions": 90,
        "lines": 90
      }
    },
    "testMatch": [
      "**/__tests__/**/*.ts?(x)",
      "**/?(*.)+(spec).ts?(x)"
    ],
    "snapshotSerializers": [
      "jest-preset-angular/AngularSnapshotSerializer.js",
      "jest-preset-angular/HTMLCommentSerializer.js"
    ]
  }
```
Obviously you'll need to change everything that's different, this is just from my project. Upgrading to the alpha version and sticking with Jest 23 for now should fix it.

**Comment by Javin007** [comment]
Now the app builds fine, and even serves fine, but all tests fail with: 

 Failed: "Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js"

**Comment by Javin007** [comment]
NVM, got it working.  (Had a single bad configuration.)  It does indeed seem to be working now.  So it would seem it's the fix is indeed in the Jest alpha.  Thanks for your help!
