### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined on new install

### ISSUE THREAD

**Issue by iainplimmer** [angular/angular-cli#6036]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.3

### Repro steps.
npm install -g @angular/cli
ng new projectname
cd projectname
ng serve
--> Browse to localhost:4200 in Chrome

### The log given by the failure.
When you first open the browser you get the following message: 
Angular is running in the development mode. Call enableProdMode() to enable the production mode.

Then the error
Uncaught TypeError: Cannot read property 'apply' of undefined
    at XMLHttpRequest.desc.get [as ontimeout] (zone.js:1265)
    at XHRLocalObject.AbstractXHRObject._cleanup (abstract-xhr.js:149)
    at XMLHttpRequest.xhr.onreadystatechange (abstract-xhr.js:125)
    at XMLHttpRequest.wrapFn (zone.js:1230)
    at ZoneDelegate.invokeTask (zone.js:398)
    at Zone.runTask (zone.js:165)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:460)

### Desired functionality.
Bug fix or the ability to work out why it's not actually working, i've cleaned the NPM cache, reinstalled with -g and still get an error.

**Comment by chusri** [comment]
I  got the same error.


<img width="1373" alt="screenshot 2017-04-22 15 51 51" src="https://cloud.githubusercontent.com/assets/2667287/25302936/a6c37380-2773-11e7-8377-df8522db7dd7.png">

**Comment by ssljivic** [comment]
Same issue here. 
I tried both node v6.10.2 and node v7.9.0.

**Comment by kGorozhanov** [comment]
in firefox works fine

**Comment by mpalourdio** [comment]
Same here from this morning in chrome. I tried downgrading to angular 4.0.0 but the problem is still here. I can't figure what has changed since yesterday.

**Comment by iainplimmer** [comment]
Yup Firefox doesn't give this error as mentioned by kGorozhanov.

**Comment by larrygeo** [comment]
in firefox i got this message **originalDescGet is undefined**

**Comment by mpalourdio** [comment]
@larrygeo same here, but as I never dev in firefox, I don't know if this error was here before.

**Comment by mpalourdio** [comment]
I've reverted my yarn.lock to an old one (https://github.com/mpalourdio/ng2/commit/b49dc1d63fdbfab7308d6cdbb6f5dffc43035608) and the errors didn't occur neither in firefox, nor in chromium.

**Comment by chusri** [comment]
i changed the yarn.lock to old one last week, i didn't see the error again.

**Comment by larrygeo** [comment]
Im not js developer,  but this line of code looks  weird 
in  **function patchProperty(obj, prop)** 

 **delete desc.value;
    var originalDescGet = desc.get;**

if  you delete desc.value the getter will return null?

**Comment by MchlFil** [comment]
Same issue here. Seems to be a Chromium bug only as Firefox is working fine for me.
If I make a production build the error message is gone. 
Must be something with `sockjs-node` as the error comes when the xhr request is responding to this call: `http://localhost:4200/sockjs-node/info?t=1492854252110`

Still trying to figure out the problem...

**Comment by admiralicic** [comment]
Same problem here.

**Comment by rilwans** [comment]
Same Problem here.

**Comment by Lightheaded** [comment]
Having the same issue with a fresh project started this morning

**Comment by NicoTuxx** [comment]
Having the same problem till yesterday night, glad to see I'm not alone...

**Comment by laiseng** [comment]
i think there is a mixup with npm verisons for zone.js
my package.json shows dependencies 
`    "zone.js": "^0.8.4"`

but inspecting 
`node_modules\zone.js\package.json`
shows that it's having different version downloaded by 

> ng new

` "_id": "zone.js@0.8.8",`

uninstall zone.js and reinstall zone.js using npm will upgrade it to 0.8.8 instead of 0.8.4
so angular/cli  1.0.0 is pointing to wrong version

**Comment by MchlFil** [comment]
I upgraded to zone.js@0.8.8 but the error is still present. @laiseng Had you have luck with the update?

**Comment by hravnx** [comment]
Downgraded to `zone.js@0.8.5` and the problem disappeared.

**Comment by NicoTuxx** [comment]
> Downgraded to zone.js@0.8.5 and the problem disappeared.
Works for me on both Chrome (58.0.3029.81) and Firefox (53.0).

**Comment by moeinpaki** [comment]
Same Problem here.

**Comment by laiseng** [comment]
yeah.. have to downgrade to zone.js@0.8.5 fix this problem
it's issue with zone.js@0.8.8.

**Comment by fifths** [comment]
Same Problem here.

**Comment by axtho** [comment]
Downgrading to zone.js@0.8.5 works

**Comment by mpalourdio** [comment]
Issues tracked here https://github.com/angular/zone.js/issues/746 and https://github.com/angular/zone.js/issues/747

**Comment by mpalourdio** [comment]
@laiseng the caret (^) is here to automatically pick safe upgrades in a semver way. Just remove the caret if you want to stick this dependency to a specific version.

**Comment by admiralicic** [comment]
I have "zone.js": "^0.8.5" but problem still persists.

**Comment by mpalourdio** [comment]
> I have "zone.js": "^0.8.5" but problem still persists.

remove the caret, and ``rm -rf node_modules && rm yarn.lock && yarn``

**Comment by avalero85** [comment]
Remove caret (^) and downgrade to 0.8.4. This works for me.

> "zone.js": "0.8.4"

**Comment by vyava** [comment]
You have to restart your server after downgrade to `zone.js@0.8.4` .

**Comment by rsaenen** [comment]
`zone.js@0.8.5` is working fine with `@angular/*@4.0.3`.
Thanks.

**Comment by Fingu** [comment]
Same here, with zone.js@0.8.5 the problem disappeared, thanks

**Comment by 2r0ck** [comment]
With zone.js@0.8.5 the problem disappeared, thanks

**Comment by TaylorPzreal** [comment]
same error, change the zone.js@^0.8.8 to ```zone.js@0.8.5``` can solve the problem, thanks

**Comment by iainplimmer** [comment]
Perfect! Quick fix is that if you just 'npm install zone.js@0.8.5' in the root of the application created by the CLI it fixes the issue :)

Well done tracking that one down @all.

**Comment by korolevsa** [comment]
With zone.js@0.8.5 the problem disappeared, thanks

**Comment by biwin** [comment]
@iainplimmer  No. It is just suppressed. :joy:

**Comment by JoseIgor** [comment]
Change "zone.js":"^0.8.5" to  "zone.js":"0.8.5" the problem disappeared, thanks

**Comment by alex-oliveira** [comment]
Same Problem here.

**Comment by rubenCodeforges** [comment]
same aswell

**Comment by benjaminu** [comment]
Same here. Had t downgrade to zone.js 0.8.5 as @JoseIgor  mentioned.

**Comment by rubenCodeforges** [comment]
Downgrade to 0.8.5 helped , thanks @JoseIgor

**Comment by tanvir-ux** [comment]
Downgraded zone and worked
npm install zone.js@0.8.5 --save
ng server

**Comment by fmorriso** [comment]
Angular-cli generated app upgraded (via npm-check-updates) fails as previously described.

downgrading from zone.js 0.8.8 to zone.js 0.8.5 - error disappears during ng serve --open

downgrading from zone.js 0.8.8 to zone.js 0.8.6 - error disappears during ng serve --open

downgrading from zone.js 0.8.8 to zone.js 0.8.7 - error disappears during ng serve --open

conclusion: angular 4.0.3 and zone.js 0.8.8 are not compatible.

**Comment by spartandeveloper** [comment]
same error, with a fresh project... 
Before:
![image](https://cloud.githubusercontent.com/assets/4668255/25311220/77926c54-27c0-11e7-9f6c-0fba626ec367.png)

Then:
1.edit package.json , check zone.js change version from 0.8.8 to 0.8.5, and save
`"zone.js": "0.8.5"`
2.install the specific version
`npm install zone.js@0.8.5`
3.if everything going well, do
`npm start`
5.Go to your browser localhost:4200 , and (firefox) javascript console don't show the error.
So ...are we stack on this version?

**Comment by TonyAnh** [comment]
Hi I had the same problem and I solve this with downgrading to zone.js@0.8.5 and the problem disappeared. Run the following command in your project folder:
`npm install zone.js@0.8.5 --save`

**Comment by leejoohan** [comment]
but it just works fine in firefox.

**Comment by nuoz** [comment]
How do you upgrade to 4.0.3 ? I'm having the same issues on 4.0.0 and zone.js 0.8.4

**Comment by irowbin** [comment]
Same here.. after upgrading to v0.8.8 
![capture](https://cloud.githubusercontent.com/assets/13050078/25312477/a212c216-2839-11e7-9bc3-319feb7e6a6d.PNG)

**Comment by fmorriso** [comment]
The way I upgrade Angular versions (e.g., 4.0.0 to 4.0.3) is to use the previously installed npm-check-updates command:
1. cd to the directory where package.json is located.
2. ncu -a
3. npm install
I did this recently and discovered that Angular 4.0.3 works with zone.js 0.8.7 and below but not with zone.js 0.8.8.

**Comment by yaroslavert** [comment]
+1

**Comment by yaroslavert** [comment]
npm install zone.js@0.8.5 --save

**Comment by nikosaliagas** [comment]
Thanks! it works with zone.js 0.8.4 :) :)

**Comment by hectorMurillo** [comment]
with zone.js@0.8.5 the problem disappeared.
Removes the node_modules folder and runs the npm install command again.

**Comment by jonathantorrens425** [comment]
Same situation/solution here: zone 0.8.5 worked for me!

**Comment by fmorriso** [comment]
Just a reminder that Angular 4.0.3 works fine with zone.js@0.8.7, as well as 0.8.5 and 0.8.6.  

Only zone.js 0.8.8 has the problem of "does not play nice with others" (Angular 4.0.3 to be specific), so do not feel like you have to downgrade all the way back to 0.8.5 as some have suggested.  That's a bit extreme.

**Comment by syscools** [comment]
Saw this issue today and the below on-liner fixes for me.
```Shell
npm install zone.js@0.8.5 --save 
```

**Comment by nlgi** [comment]
Same here, works in 0.8.7

**Comment by Klyner007** [comment]
npm install zone.js@0.8.7 --save: worked for me!

**Comment by sangecz** [comment]
I tried that, not even fresh new app is not working. I tried couple of times to remove angular/cli and angular-cli globally, multiple times local node_modules.  Tried to run ng serve globally and locally same error in chromium, but older project runs there fine. I think I need to run it in chromium as some of my target devices are build on it.

Also I noticed that `npm show zone.js version` shows globally installed version 0.8.8 (not obvious for me npm noob). And `npm list | grep zone` prints zone.js@0.7.8 as angular/clie dep. and  zone.js@0.8.5 as project dep. (my fixed version). The older working project has these the same.

I even tried to copy&paste node_modules from thw working project and install rest of the deps. -
 same error.

I don't know what to do next maybe complete reinstall node+npm+nvm and start from clean slate, but it seems rather extreme.

**Comment by nuirattapon** [comment]
@sangecz  What version you did you select in "package.json" ? if zone.js is not version 0.8.8, npm install again should be worked.

**Comment by nuirattapon** [comment]
@sangecz What version you did you select in "package.json" ? if zone.js is not version 0.8.8, npm install again should be worked.

**Comment by Migggz** [comment]
Zone version was 0.8.4 and there was that TyprError, 
When I installed 0.8.5 version it worked without any errors !!!

**Comment by micsimon** [comment]
zone.js downgrade from 0.8.8 to 0.8.7 worked for me

**Comment by kondi** [comment]
Should be fixed by https://github.com/angular/zone.js/pull/747. Wait for next release.

**Comment by developermahmoud** [comment]
just do this 
npm install zone.js@0.8.5 --save

**Comment by HFTSOL** [comment]
Got the same error/issue.  Version 0.8.7 fixed it for me.

@angular/cli@1.0.0
@agnular@4.0.0
zone.js@0.8.7

**Comment by bentedder** [comment]
Agreed. Locking to version 0.8.7 fixed it for me. 👍

**Comment by BamiGorengo** [comment]
Hmmm... doesn't really worked for me. I tried with 0.8.7 and with 0.8.8... Still same Console Error. ¯\_(ツ)_/¯

**Comment by sorin21** [comment]
1. updated manually package.js setting  zone.js:"0.8.5"

then run:
2. npm remove zone.js

then run:
3. npm install zone.js:@0.8.5

then run:
4. ng serve --open

**Comment by BamiGorengo** [comment]
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "zone.js:@0.8.5"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: zone.js:@0.8.5
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/budi/PhpstormProjects/DevReborn/npm-debug.log

**Comment by sorin21** [comment]
My bad @BamiGorengo I made a mistake  I put npm install zone.js:@0.8.5 instead of npm install zone.js@0.8.5, without ':'. Try it again.

**Comment by youngmob** [comment]
zone.js 0.8.5 solved my problem too. THanks.

**Comment by ChileNetwork** [comment]
After i run my ng serve i got this on my console firefoxDeveloperEdition browser:
[WDS] Disconnected!  vendor.bundle.js:27560:10
GET  http://localhost:4200/ [HTTP/1.1 304 Not Modified 68ms]
GET http://localhost:4200/inline.bundle.js [HTTP/1.1 304 Not Modified 2ms]
GET http://localhost:4200/polyfills.bundle.js [HTTP/1.1 304 Not Modified 20ms]
GET http://localhost:4200/styles.bundle.js [HTTP/1.1 304 Not Modified 19ms]
GET http://localhost:4200/vendor.bundle.js [HTTP/1.1 304 Not Modified 66ms]
GET http://localhost:4200/main.bundle.js [HTTP/1.1 304 Not Modified 65ms]
GET XHR http://localhost:4200/sockjs-node/info [HTTP/1.1 200 OK 1ms]
# #_**TypeError: originalDescGet is undefined[Aprender más]  polyfills.bundle.js:3918:17**_
GET http://localhost:4200/sockjs-node/540/k2jwl4hl/websocket

**Comment by sorin21** [comment]
Start it again. To test it you can create a new test app and then follow the steps that I put above. I got the same error in firefox when I didn't change manually from package.js setting zone.js:"0.8.5". Myselft I updated all projects with those steps and now works fine in firefox and chrome.

**Comment by INGCRENGIFO** [comment]
replace dist.
[dist.zip](https://github.com/angular/angular-cli/files/953448/dist.zip)

**Comment by JanStureNielsen** [comment]
See http://stackoverflow.com/questions/43598863/angular-4-0-3-uncaught-typeerror-cannot-read-property-apply-of-undefined

**Comment by wuzhouyang** [comment]
@hravnx     thx !!

**Comment by deepthan** [comment]
update to  zone.js@0.8.5 work for me ,thanks a lot !!

**Comment by nourBerro** [comment]
i got the same error only when i upgraded the zonejs to v0.8.8, i didnt get that error when i was using v0.8.4 but i needed to upgrade because redux didnt work well with old version of zonejs.

when i create the bundle of my app it worked without that error.

**Comment by hanquf1** [comment]
zone.js 0.8.7 work, thanks

**Comment by lto3-micros** [comment]
using node 6.10.2, npm 4.2.0 and angular 1.0.1, got the same issue.
upgrade the zone.js to 0.8.5 fixes the issue. 
thanks

**Comment by Klyner007** [comment]
Make sure you restart your application instead of just reloading the webpage ;)

**Comment by berardo** [comment]
FWIW, working fine on newest versions of:
node: v7.9.0
angular-cli: 1.0.1
@angular/common: 4.0.3
Got from `ncu -a`
But manually downgrading zone to 0.8.7:
`npm i -S zone.js@0.8.7`
Consider removing caret on package.json as [on commit above](https://github.com/gilhanan/angular2-express-starter/commit/78580f89b1e0113e5fcc644836a3bc4f85f91fdb) to avoid install zone.js 0.8.8 on later npm installs.

**Comment by peterbarraud** [comment]
For whatever it's worth, it works in Microsoft Edge :)

**Comment by kleber-swf** [comment]
I had the same issue, downgraded to zone.js to `0.8.7` and it worked.
I just upgraded to `0.8.8` again (actually `^0.8.7`) to test and still works!
I've tested on Chrome, Firefox and Edge.
Go figure...

**Comment by fmorriso** [comment]
kleber-swf:  Verify that you really did re-upgrade to zone.js@0.8.8 by checking your equivalent to `C:\projects\APM-Start-CLI\node_modules\zone.js\package.json` and verify that the 5th line (might be higher or lower) shows the following:

`"raw": "zone.js@^0.8.7",`

In your case, the "magic recovery to using zone.js@0.8.8" may in fact be using an older edition of zone.js.

To be really certain that zone.js 0.8.8 works, you should delete directory ``:\projects\APM-Start-CLI\node_modules\zone.js` and then go back and `npm install -S zone.js@0.8.8` to verify it has had the miraculous recovery that you mentioned earlier.

**Comment by MohammedEssehemy** [comment]
zone.js 0.8.5 solved the problem. Thanks.

**Comment by willyhakim** [comment]
zone.js 0.8.9 solved the problem

**Comment by mpalourdio** [comment]
+1 zone.js 0.8.9 is ok here. @iainplimmer  this issue can be closed IMO.

**Comment by kleber-swf** [comment]
@fmorriso you are right! The version in the file is different from the version shown by `npm view zone.js version` (thanks).
I deleted the folder, run `npm update` and the version now is `0.8.9`, which solves the problem.

**Comment by bezerrath** [comment]
Upgrade **@angular/core** from ^4.0.0 to **^4.0.3** and then upgrade zone.js to ^0.8.5.

**Comment by sangecz** [comment]
I tried to install @angular/cli on my debian server (no prev angular, angular/cli or whatever installed). 
I generated test app with `ng new zonetest` and run it with `ng build`. Then I hosted the dist/ dir with `python -m SimpleHTTPServer`. And in chrome, firefox and safari its working fine. But in chromium I get this error (same as on my machine):
<img width="639" alt="screen shot 2017-04-25 at 23 38 04" src="https://cloud.githubusercontent.com/assets/9822229/25409266/8b13b2b2-2a11-11e7-8bb4-fbd62a060f44.png">

<img width="520" alt="screen shot 2017-04-25 at 23 38 39" src="https://cloud.githubusercontent.com/assets/9822229/25409295/a6bd9758-2a11-11e7-9269-6474b4636a83.png">

I think that this error has nothing to do with zone.js. I don't know what to do, I really need this working in that damn chromium, and I know it worked...

**Comment by sangecz** [comment]
Ok, I solved it, new projects comes with switched off importing polyfills for IE9, IE10 and IE11 (polyfills.ts), uncommenting to actually import them solved my issue with chromium.

**Comment by gueroverde** [comment]
I solved with this:

npm install zone.js@0.8.7 --save 

is the rigth way?

**Comment by M-R-Bishop** [comment]
@gueroverde It looks like this is fixed in the latest release (0.8.9) too

**Comment by hexagon6** [comment]
@gueroverde I had the same issue, can confirm upgrading zone.js to 0.8.9 fixes it.

**Comment by anatoly314** [comment]
`Angular@4.0.3` together with `zone@0.8.9`, the issue is still here.
![screen shot 2017-04-26 at 15 46 59](https://cloud.githubusercontent.com/assets/1641594/25435154/ca255880-2a97-11e7-8512-ba6c52527ad4.png)
![screen shot 2017-04-26 at 15 47 13](https://cloud.githubusercontent.com/assets/1641594/25435165/d33b43da-2a97-11e7-8d71-fd06d04c662a.png)
![screen shot 2017-04-26 at 15 47 36](https://cloud.githubusercontent.com/assets/1641594/25435173/d8d51398-2a97-11e7-9bb0-59b62ed9b36b.png)

**Comment by Tyrix** [comment]
The latest zone.js@0.8.9 with @angular/cli@1.0.1 and @angular/...@4.1.0 fixes everything for me

**Comment by aguacongas** [comment]
I confirm, I cannot reproduce with zone.js@0.8.9, @angular/cli@1.0.1 and @angular/...@4.1.0

**Comment by sumitarora** [comment]
Closing Fixed by Zonejs Update.

**Comment by dfanica** [comment]
```

**Comment by ZhiliangGong** [comment]
down graded to zone.js@0.8.4 and issue fixed.

**Comment by issacong91** [comment]
I'm facing the same problem. Please refer to this link if you need the sample code 
https://stackblitz.com/edit/angular-xqfkvj?file=src%2Fmain.ts

You can turn on the developer tools to see the error. Anyone can help me with this? I'm trying to create angular custom web components and I have encountered this problem after I removed the zone.js in polyfills and apply option ngZone: 'noop'.
