### ISSUE TITLE
The ng test command results in Executed 0 of 0 ERROR on a new project

### ISSUE THREAD

**Issue by jschwarty** [angular/angular-cli#6284]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.0
node: 7.4.0
os: win32 x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.2

### Repro steps.

Run `ng new cli`
Change directory to `cli`
Run `npm test`

### The log given by the failure.

11 05 2017 15:48:09.772:WARN [karma]: No captured browser, open http://localhost:9876/
11 05 2017 15:48:09.786:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
11 05 2017 15:48:09.787:INFO [launcher]: Launching browser Chrome with unlimited concurrency
11 05 2017 15:48:09.792:INFO [launcher]: Starting browser Chrome
11 05 2017 15:48:11.635:INFO [Chrome 58.0.3029 (Windows 10 0.0.0)]: Connected on socket jxFy-w1ruFVYlutmAAAA with id 36112906
Chrome 58.0.3029 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.002 secs / 0 secs)

### Desired functionality.

Expected it to find `.spec.ts` files and run tests.

### Mention any other details that might be useful.

Just started experiencing this today (May 11th, 2017). Can replicate it on existing projects that are using `@angular/cli: 1.0.0` by deleting the `node_modules` dir and running an `npm i` then `npm test`.

Also note that `npm run e2e` works fine with a response of `Executed 1 of 1 spec SUCCESS in 1 sec.`.

**Comment by btassone** [comment]
I can also confirm I am experiencing the same issue with the same steps.

**Comment by rokikon** [comment]
Not reproduced with `@angular/cli: 1.1.0-beta.1`

**Comment by ERPedersen** [comment]
Same here

**Comment by btassone** [comment]
I can confirm like @rokikon that 1.1.0-beta.1 does not have this issue

**Comment by paynoattn** [comment]
same here, using 1.0.0

**Comment by trcollinson** [comment]
We were having this same issue. I was able to track it down to a change from mime@1.3.4 -> mime@1.3.5. Changing the dependency back to mime@1.3.4 fixed our build.

**Comment by paynoattn** [comment]
This issue is caused by dependency mime @1.3.5, which was released today. Mime is a dep of karma. You can overwrite it with ```npm install mime@1.3.4 -S```

**Comment by trcollinson** [comment]
Upon further investigation it seems that mime and or karma is no longer respecting the mime: {} portion of the karma.conf.js. Our karma.conf.js has the following:

```
    mime: {
      'text/x-typescript': ['ts','tsx']
    }
```

Previously this would override the apache mime type for .ts which is "video/mp2t" however it seems this is no longer being overwritten properly.

**Comment by paynoattn** [comment]
c9b1e6b820fdcade605cb1000f3e1f731f34ea38 should fix this I'll be submitting a pull request shortly

**Comment by filipesilva** [comment]
Heya, this issue shouldn't happen starting 1.1.0 (https://github.com/angular/angular-cli/pull/6160). That PR removed the need to specify mime types along with a performance increases. It's released as a beta in `@angular/cli@next` if you want to try.

**Comment by russcarver** [comment]
I'm still seeing this in 1.1.3.  I just upgraded from 1.0.0-beta.28.3.  It wasn't a problem before with the mime entry.  Now I'm seeing the issue both with and without the mime entry.

Any thoughts?

**Comment by filipesilva** [comment]
@russcarver try making a new project and checking out the differences between karma configs. There may be something you missed since you're updating from a very old version. Also check out https://github.com/angular/angular-cli/wiki/stories-1.0-update for other config items.

**Comment by russcarver** [comment]
@filipesilva Yeah, I've tried that too.  The odd thing is that it works about 1 in every 10 tries.  I've tried so much to get this working, I feel lost in the fray.

**Comment by filipesilva** [comment]
Have you tried migrating your src folder to a newly generated project?
