### ISSUE TITLE
ng build --prod fail with a message "compiler.compileAll is not a function"

### ISSUE THREAD

**Issue by morninng** [angular/angular-cli#6601]
### Bug Report 

When I build with "ng build --prod", following error come out
 `ERROR in this.compiler.compileAll is not a function`

### Versions.

@angular/cli: 1.1.0
node: 6.9.2
os: linux x64
@angular/common: 4.2.0-rc.2
@angular/compiler: 4.2.0-rc.2
@angular/core: 4.2.0-rc.2
@angular/forms: 4.2.0-rc.2
@angular/http: 4.2.0-rc.2
@angular/platform-browser: 4.2.0-rc.2
@angular/platform-browser-dynamic: 4.2.0-rc.2
@angular/router: 4.2.0-rc.2
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3

### Repro steps.
(1) ng new
(2) adjust package json
(3) ng build --prod 
error happen
the repository is here
https://github.com/morninng/issue_angularcli

### The log given by the failure.

following error comes out

ERROR in this.compiler.compileAll is not a function

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/morninng/development/Angular2/mixidea_cowork/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

### Desired functionality.

 build should be succeeded

### Mention any other details that might be useful.
 ng build --dev or ng build  works successfully

**Comment by filipesilva** [comment]
I can't reproduce this on the projects I test. Can you provide a reproduction please?

**Comment by morninng** [comment]
Hi @filipesilva 
I have added the reproduce way with repository

(1) ng new
(2) adjust package json
(3) ng build --prod
error happen
the repository is here
https://github.com/morninng/issue_angularcli

**Comment by stephanecot** [comment]
Same problem here with angular 4.2.0 release

**Comment by pgrm** [comment]
same issue here, it just started happening few minutes ago, until than all the builds were passing

**Comment by mzdunio** [comment]
I have this problem too after updating npm packages today

**Comment by rgant** [comment]
I think they changed the flag to `-prod` only one dash.

**Comment by garthtee** [comment]
I also have this problem. Has there been a fix/work around yet?

**Comment by skovmand** [comment]
I had the issue too. I don't know exactly what caused it, but this did the trick:

1) I aligned my package.json dependencies with the default ng-cli package.json. I deleted everything I didn't use anymore, and added everything except the jasmine/karma/protractor packages (I don't have tests yet in this project, maybe some day.... :-)

2) Delete node_modules and yarn.lock

3) Reinstall the packages, in my case using yarn. This fixed the problem.

**Comment by marius-oprea** [comment]
the same error with @angular 4.2.2 when I do ng build -prod

**Comment by jun06t** [comment]
I guess ``--aot`` option causes this problem.
``--prod`` option sets ``--aot`` automatically.
``$ ng build --aot``(without --prod) shows the same error.

**Comment by hheexx** [comment]
Broken by updating to 4.2.2

deleting node_modules does not work for me.

**Comment by andrelmp** [comment]
had to fix @angular/* packages to version 4.1.3 to restore my CI Build

**Comment by andrelmp** [comment]
Did some tests, and i think is related to  https://github.com/angular/angular/commit/ed73d4f3ac6b542bf5ea3eb73fbe91e2ceabcdb4
Adding ```"angularCompilerOptions": {
    "alwaysCompileGeneratedCode": true
  }``` to tsconfig.json solved the issue. 
I don't know if is the correct solution, but works.

**Comment by jun06t** [comment]
This problem is solved after updating angular-cli 1.1.2 in my environment.
```
$ ng --version
@angular/cli: 1.1.2
node: 8.1.0
os: darwin x64
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.2
```

**Comment by eddwin** [comment]
It also went away for me after updating angular-cli to 1.1.2

**Comment by ColeBeckwith** [comment]
Anyone find a solution that doesn't involve reverting to Angular 4.1?

**Comment by andrelmp** [comment]
@ColeBeckwith did you tried update @angular/cli to 1.1.2?

**Comment by samvloeberghs** [comment]
@andrelmp and what if I don't use CLI? This is a breaking change :(

**Comment by andrelmp** [comment]
@samvloeberghs if you don't use cli, you can't use "ng build" command, so isn't related to this issue

**Comment by samvloeberghs** [comment]
@andrelmp I have the impression the issue is not related specifically to the "ng-build" command.. it's related to the upgrade from 4.1.x to 4.2.X. I'm not using cli, and I have the same issue updating form 4.1 to 4.2. Even the same error message mentioned before: ```this.compiler.compileAll```

**Comment by samvloeberghs** [comment]
@andreImp @ColeBeckwith specifing the compiler-cli 4.2.3 resolved it for me

**Comment by soerenbf** [comment]
For me, the issue was my node version (8.1.2). If you use nvm to control your node environment, try downgrading to 7.x.x (i had 7.4.0 installed). This solved the issue for me.

**Comment by colordove** [comment]
update @angular/compiler-cli to 4.2.4 & @angular/cli to 1.1.3 resolved this error for me.

**Comment by jsessink** [comment]
Just wanted to point out that downgrading is unnecessary.  I was running into this issue as well with the **aot** flag, and have resolved it by:
- Updating NodeJS from 8.0.0 to 8.1.2
- Updating NPM from 5.0.3 to 5.0.4
- rm -rf on node_modules
- npm cache verify
- Set package versions:
    All @angular/* packages are at 4.2.4
    @angular/cli is at 1.1.3
- npm i

Verify that your packages are valid in your directory (do an **npm list --depth=0**).

I also removed my package-lock.json, since I was starting fresh, but not sure if necessary (as it should update that file with changes to the package.json and running npm i).

**Comment by filipesilva** [comment]
This seemed to be caused by a mismatch between `@angular/*` packages and is solved by upgrading to `4.2.4+`. https://github.com/angular/angular-cli/pull/6817 will also set that minimum for new apps.

**Comment by nicolae536** [comment]
Anyone getting this ? I still get it using @ngtools/webpack

**Comment by chelaruc** [comment]
Me too :(

**Comment by atifsaddique211f** [comment]
Resolved this error by updating @angular/compiler-cli to 4.2.3

**Comment by sasanazizi** [comment]
I update @angular/compiler-cli to 4.4.3 but not resolved !
environments : 
@angular/cli: 1.2.7
node: 7.8.0
os: win32 x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/platform-server: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.2.7
@angular/compiler-cli: 4.4.3

**Comment by atariman5000** [comment]
I am using ASP.NET Core 2.0's Angular template and upgraded from Angular 4 to Angular 5. I replaced two instances of AotPlugin in my wepack.config.js file with AngularCompilerPlugin to fix this problem. I can't recall where I got the link from now, but anyone looking to do the same can go (https://long2know.com/2017/11/angular-5-0-released/) to see how it is done.
