### ISSUE TITLE
NPM packages are not installing when generating a new project in cli 1.2.1

### ISSUE THREAD

**Issue by nvasilev1** [angular/angular-cli#7043]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.1
node: 6.11.1
os: win32 x64

### Repro steps.
ng new project

### The log given by the failure.
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Installing packages for tooling via npm.
'npm' is not recognized as an internal or external command,
operable program or batch file.

Package install failed, see above.
D:\temp\NV\node-v6.11.1-win-x64\node_modules\@angular\cli\tasks\npm-install.js:2
5
                    throw new Error(message);
                    ^

Error: Package install failed, see above.
    at child_process_1.exec (D:\temp\NV\node-v6.11.1-win-x64\node_modules\@angul
ar\cli\tasks\npm-install.js:25:27)
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

### Mention any other details that might be useful.

There is a thread #6964 for this kind of problem, I`ve read it, tried it and still has problem. Below is my comment (sorry if something is missing from my thread or it should be posted somewhere else):

Hello,
I have the same issue, but trying with the fix does not work for me unfortunately. I do not have npm-install.ts file, but instead i have npm-install.js (and npm-install.d - MPEG2 TS video file and npm-install.js.map). The file npm-install.js is with similar code than the one showed int he fix, but there are some differences, which crash the new project. For example if I copy paste the whole code into my file, this is the error:

Unexpected token import
D:\temp\NV\node-v6.11.1-win-x64\node_modules@angular\cli\tasks\npm-install.js:2

import * as chalk from 'chalk';
^^^^^^
SyntaxError: Unexpected token import
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (D:\temp\NV\node-v6.11.1-win-x64\node_modules@angular
\cli\tasks\init.js:5:23)

I am attaching the original npm-install.js file.
[npm-install.zip](https://github.com/angular/angular-cli/files/1158495/npm-install.zip)

Sorry if there is an easy fix shown in the answer or the procedure of asking this kind of stuff is different, but I am kind of new here.

**Comment by fmalcher** [comment]
This was a bug in 1.2.1. It should be fixed with https://github.com/angular/angular-cli/commit/aebf4c89b1b4c66316b0a396751f6bd9d9d1b645 and should land in the next release.

@nvasilev1 Why your fix doesn't work:
When installing via NPM, you always download the transpiled version so there is no TypeScript anymore (just the type definition files `.d.ts`). When you want to extend the original code you need to download the original sources and build them locally.

**Comment by nvasilev1** [comment]
@fmalcher Thanks for your answer. Will definitely try the fix. However i still do not see the .ts files (only .js and they are somehow different). From what you wrote (if I understand it correctly) it maybe because of using the binary installation where i should use the normal windows installer (.msi file). Am I correct and is there a fix for it?

**Comment by fmalcher** [comment]
@nvasilev1 For the original source code you need to clone this GitHub repo and build from this source.
Then you can use `npm link` to use the local repo like a globally installed NPM package.

However, this issue was already fixed, so no need for you to fix it again. If you're interested in how the CLI works internally, cloning the repo is a good point to start at.

**Comment by nvasilev1** [comment]
@fmalcher Thanks for the explanation. I`ve deleted the node, npm and Angular. Downloaded a fresh binary copy using the instruction here https://angular.io/guide/quickstart . Wrote all the needed commands for the version here:

D:\temp\NV\node-v6.11.1-win-x64>node -v
v6.11.1

D:\temp\NV\node-v6.11.1-win-x64>npm -v
3.10.10

D:\temp\NV\node-v6.11.1-win-x64>ng -v

@angular/cli: 1.2.1
node: 6.11.1
os: win32 x64

No problems on installing Angular at all, but once I try a new project it fails again on npm packages. Am I missing something?

**Comment by fmalcher** [comment]
The fix is merged into the repo but not released yet. We need to wait for the 1.2.2 release in order to see this in the latest NPM package.

**Comment by nvasilev1** [comment]
@fmalcher Thanks Man. Then will wait for 1.2.2 :)

**Comment by fmalcher** [comment]
1.2.2 is out now and the issue is fixed
