### ISSUE TITLE
ng eject creates absolute paths for "alias" in webpack config

### ISSUE THREAD

**Issue by mwager** [angular/angular-cli#8495]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0 (e)
Node: 8.9.1
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack-concat-plugin: 1.4.0
webpack-dev-middleware: 1.12.0
webpack-dev-server: 2.9.4
webpack-hot-middleware: 2.20.0
webpack: 3.8.1
```

### Repro steps.

`$ ng eject` # on mac

### Desired functionality.

aliases relative or remove them

### Mention any other details that might be useful.

Example webpack config output:

```
"alias": {
      "rxjs/AsyncSubject": "/Users/me/Projects/my/project/node_modules/rxjs/_esm5/AsyncSubject.js",
```

**Comment by jbandi** [comment]
I think it's fixed in angular cli 1.6:
I observed the problem in 1.5 in a vanilla ng new & ng eject.
I cant observe the problem in 1.6 in a vanilla ng new & ng eject.

**Comment by StefanKern** [comment]
Can confirm this. If you need to change an old webpack file just replace your alias with 

`
const rxPaths = require('rxjs/_esm5/path-mapping');
...
"alias": rxPaths()`

Thats how the new angular cli does it

**Comment by clydin** [comment]
Fixed in 1.5.4/1.6.0.

**Comment by raygerrard** [comment]
I have updated to 1.6.5 and ran ng eject again and I am still getting full paths in the output:

ng --version: 

Angular CLI: 1.6.5 (e)
Node: 9.0.0
OS: darwin x64
Angular: 5.0.3

webpack config contains:
const projectRoot = "/Users/raygerrard/Code/client/app-name";
