### ISSUE TITLE
[ERROR] ng new failed on @angular/cli 1.6

### ISSUE THREAD

**Issue by choucry13** [angular/angular-cli#8765]
### Versions
```
Angular CLI: 1.6.0
Node: 8.9.1
OS: darwin x64
```

### Repro steps
when i launch command `ng new` to create a new app, i have error.
### Observed behavior
ng new look-error   
error! look-error/src/app/app.component.html already exists.
error! look-error/src/app/app.component.spec.ts already exists.
error! look-error/src/app/app.component.ts already exists.
error! look-error/src/app/app.module.ts already exists.
ENOENT: no such file or directory, uv_chdir
Error: ENOENT: no such file or directory, uv_chdir
    at process.chdir (/usr/local/lib/node_modules/@angular/cli/node_modules/graceful-fs/polyfills.js:21:9)
    at /usr/local/lib/node_modules/@angular/cli/tasks/init.js:74:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by aiboy** [comment]
Same problem here :(

**Comment by sergkr** [comment]
Same here on Windows 7.

**Comment by JozefFlakus** [comment]
I have the same problem. But the strangest thing is that when I go back to v1.5.5 this problem still occurs.

```
Node: 8.9.2
OS: macOS 10.13.1
```

**Comment by wulfsberg** [comment]
Seeing this on Win 10, Node 8.1.2 too.

(I tried uninstalling, clearing NPM cache and re-installing, without luck)

**Comment by yarrgh** [comment]
I don't think it's an issue with angular-cli itself but on one of its dependencies.

**Comment by chunghha** [comment]
Same error on Window 7 and Ubuntu 16.04.

Angular CLI: 1.6.0
Node: 8.9.2
OS: win32 x64

Angular CLI: 1.6.0
Node: 9.1.0
OS: linux x64

**Comment by JozefFlakus** [comment]
@yarrgh you are right, when I downgraded it to 1.5.5 and 1.4.x this problem still occured.

**Comment by nicstrong** [comment]
Same error Windows 10:

Angular CLI: 1.6.0
Node: 9.2.0
OS: win32 x64

**Comment by hansl** [comment]
Testing locally, I'll come back with some (hopefully good) news soon.

**Comment by JasonGoemaat** [comment]
Same error here with Windows 10/Node 6.11.5/npm 3.10.10.

If I create the directory myself and run the command, it  has the same first errors and says it's installing packages and that it succeeds,  but there are only '.git' and 'node_modules' folders and no files, and node_modules is empty.

```
$ ng new tt2
error! tt2/src/app/app.component.html already exists.
error! tt2/src/app/app.component.spec.ts already exists.
error! tt2/src/app/app.component.ts already exists.
error! tt2/src/app/app.module.ts already exists.
Installing packages for tooling via npm.
npm WARN enoent ENOENT: no such file or directory, open 'C:\git\web\tt2\package.json'
npm WARN tt2 No description
npm WARN tt2 No repository field.
npm WARN tt2 No README data
npm WARN tt2 No license field.
Installed packages for tooling via npm.
Project 'tt2' successfully created.
```

**Comment by hansl** [comment]
This is a problem with trying to overwrite files in Schematics. It seems like some files were created twice and fixing a bug in validation actually uncovered the error. I'm working on a fix right now.

**Comment by choucry13** [comment]
Thank you @hansl.

**Comment by ezrasandzerbell** [comment]
Hopefully fixed soon ...

**Comment by hansl** [comment]
this commit is the fix https://github.com/angular/devkit/pull/319/commits/bd25a1ff88f7c15fe3c5b4d863bd7be7b8a443c5

Will release in 5-10 minutes.

**Comment by hansl** [comment]
(just need to release the devkit)

**Comment by YAdelMehraban** [comment]
Same thing here, also tested with v1.5.5

**Comment by hansl** [comment]
Done. Can someone checks that it works?

**Comment by YAdelMehraban** [comment]
Should I install the the latest? @hansl

**Comment by Brocco** [comment]
Just creating a new project should be sufficient.

**Comment by hansl** [comment]
@YAdelMehraban yes reinstall global CLI please.

**Comment by InfoScion** [comment]
Testing now @hansl

**Comment by vcalaelen** [comment]
@hansl Just tried it, everything is working.

**Comment by markbosky** [comment]
@hansl Can confirm working on mac os after reinstalling and creating new project. Thanks!

**Comment by YAdelMehraban** [comment]
@hansl works now, thank you so much

**Comment by hansl** [comment]
Closing this issue as fixed. Thanks all!

**Comment by robpodosek** [comment]
wow, thanks :) literally just found this a few minutes ago.

**Comment by MendelBak** [comment]
Thanks for the fix Hansl!

**Comment by cortez-scr** [comment]
I am completely new to this, can some one please give me some advice on how to apply the fix? Thanks in advance.

**Comment by markbosky** [comment]
@cortez-scr npm install -g @angular/cli, ng new my-app

**Comment by cortez-scr** [comment]
Oh ok, I understand . By re-executing npm install, i am downloading the fixes and automatically replacing them on my machine. Pretty cool! Thanks

**Comment by santiagopb** [comment]
Thanks @hansl

**Comment by fmorriso** [comment]
Shouldn't there be a publicly visible 1.6.1 release for this fix? I do not see it when I click on the Releases tab.

**Comment by yarrgh** [comment]
@fmorriso No, because it wasn't @angular/cli that had the issue. It was another package that @angular/cli depends on (angular/devkit package).

**Comment by fmorriso** [comment]
@yarrgh Thanks for the clarification.  I was unaware this issue was caused by another package, much less that it was fixed, which is why I waited (in vain it turns out) for a patch release to appear.

May I make a suggestion?  Whenever these situations exist and are fixed by some kind of "not visible to the general public" technique like was the case in this issue, can somebody make a public announcement (changelog.md ?, WiKi entry, etc.) so that it stands out?  Otherwise, you  have to search through the issues and hopefully notice that the issue was resolved, something I'm betting that not a lot of people will see.

Just my two cents worth.

**Comment by carlchandev** [comment]
Same issues here...Any workaround guys?
I am new to angularjs and just get angularcli installed and run
"ng new my-app" which from official getting started doc. And i got this issue.

(Win 10)
Angular CLI: 1.6.3
Node: 8.9.0
OS: win32 x64

**Comment by seekheart** [comment]
Hey guys,

I'm having the same issue and I've done

```
npm uninstall -g @angular/cli
npm cache verify
npm i -g @angular/cli
ng new t
```

Yet still get the same errors, I'm on now 8.9 and angular cli 1.6.6...

**Comment by andreobueno** [comment]
I'm also having the same problem... =/ 

$ sudo ng new angular-src
Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.

I'm using MacOs High Sierra 10.13.2

**Comment by ChandraniChatterjeeMolly** [comment]
@seekheart  try creating the project at some new path. this resolved the issue for me.
