### ISSUE TITLE
ng new hello Error: Path "/app/app.module.ts" does not exist. Path "/app/app.module.ts" does not exist. 

### ISSUE THREAD

**Issue by tejas17kuthe** [angular/angular-cli#8776]
### Versions
```
npm -v
5.5.1



I am facing problem in creating new project in angular.
When I run ng new myapp command I get following command


ng new hello
Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.

**Comment by gousehere** [comment]
I am also facing the same problem can anyone help me out???

**Comment by tejas17kuthe** [comment]
After searching for hours.
I did not find the solution anywhere.
But I reinstalled my node.js and npm, the problem was solved.

**Comment by Brocco** [comment]
Duplicate of #8765

**Comment by OrkhanHuseynli** [comment]
I reinstalled Node and Angular, did it several times. cleaning cache and so on. 
but still get this error 
Can anyone please help?
-----------------------
When I create a new project "ng new project-name" , I get this error: 
Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.

**Comment by lenichols** [comment]
+1

**Comment by bradkt** [comment]
Same issue on Windows 10. Tried to uninstall globally, clear cache and reinstall with no luck.

**Comment by carlchandev** [comment]
Same issues here...Any workaround guys?
I am new to angularjs and just get angularcli installed and run
"ng new my-app" which from official getting started doc. And i got this issue.

**Comment by OrkhanHuseynli** [comment]
@bradkt @carlchandev 

please, see my last answer above

**Comment by nemeth-tibor** [comment]
I reinstalled angular/cli globally (1.6.3), so the next message when I try _ng new project-name_ is:

Error: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

C'mon guys! What the heck are you doing with ng? I'm absolutely unable to do anything with it for a while, but I was able before..

**Comment by titusfx** [comment]
In my case the problem was folder permission. I tried in a folder with full permission and worked.

If you are using windows just uncheck Readonly

If you are using OS base on Linux Kernel just:

sudo chmod 644 -R foldername

**Comment by eragon11** [comment]
I'm also faced same issue ... i find the solution : 1. change the directory of your working and execute the code ng new "your app name" 2. other uninstall all the app(node,angular) and again reinstall................./

**Comment by adnanaslamit** [comment]
Hi Friends i found the answer 
for this error 
Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.
**while creating the angular project**

**Solution : Follow the steps :** 
_**Please go to the directory where you have installed the node then see in your project directory where you are creating the projects there you see node_modules folder simply delete that because its overwriting the your node modules directory**_

Cheers
https://github.com/adnanaslamit/

**Comment by harendrakarsh** [comment]
@adnanaslamit thanks brother it really worked for me but I delete node_modules outside of my projects directory
