### ISSUE TITLE
@ngtools/webpack doesn't support template compilation using entryModule

### ISSUE THREAD

**Issue by kylecannon** [angular/angular-cli#8897]
### Versions
```
Angular CLI: 1.6.1 (e)
Node: 8.9.0
OS: darwin x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-dev-server: 2.9.7
webpack: 3.10.0

```

### Repro steps
We have a very customized angular setup that allows us to drop in NgModules with EntryComponents as widgets on a page. This means that for each widget, we would like to run AOT separately. We have a specific build process internally that asserts that each widget is running the same exact version of angular down to the patch to avoid differing AOT builds between patch versions. JIT mode has been in use in production for 10 months with a total success, however, we want to take advantages of not having to ship the compiler to the browser and getting incremental AOT builds in development.

So on to the issue, we don't use `platformBrowserDynamic().bootstrapModule(...)` in the widgets themselves because the entry point on each widget is similar to this:

----

`src/app.component.ts`
```typescript 
import { Component } from '@angular/core';

@Component({ ... })
export class AppComponent {
}
```

----

`src/app.module.ts`
```typescript
import { NgModule } from '@angular/core';
import { AppComponent  } from './app.component.ts';
@NgModule({
  declarations: [AppComponent],
  exports: [AppComponent],
  entryComponents: [AppComponent]
})
export class MyWidgetModule {
}
```

----

`src/index.ts`
```typescript
import { MyWidgetModule  } from './app.module.ts';
import { AppComponent  } from './app.component.ts';


export const EntryNgModule = MyWidgetModule;
export const EntryComponent = AppComponent;

----

```

A custom webpack config bundles it and distributes it to the page global when lazy loaded.
```javascript

module.exports = {
    ....
    entry: {
        'widget-bundle': './src/index.ts'
    },
    output: {
        library: ['Apps', widgetName],
        libraryTarget: 'var',
    }
    ....
}
```

----

The core application that **DOES** call the `platformBrowserDynamic().bootstrapModule(...)` and the core application will load the widgets in when necessary via a lazy loading in the widget bundle. Here is an example of how we do this for each widget that is on the page:

```typescript
import { Component } from '@angular/core';

@Component({ ... })
export class WidgetAppContainerComponent implements AfterViewInit {
    @ViewChild('vcr', { read: ViewContainerRef }) vcr: ViewContainerRef;
    @Input() widget: any;
    constructor(public injector: Injector, public compiler: Compiler) {
    }

    ngAfterViewInit() {
        this.initAotComponent(Apps[this.widget.key]);
    }

    initAotComponent({EntryNgModule, EntryComponent}) {
        const componentFactory: ComponentFactory<any> = EntryComponent;
        const entryNgModule: NgModuleFactory<any> = EntryNgModule;
        const moduleRef = entryNgModule.create(this.injector);
        const componentRef = componentFactory.create(moduleRef.injector, [], undefined, moduleRef);
        this.vcr.insert(componentRef.hostView);
    }
}
```

So in the midst of doing research in using `@ngtools/webpack`, I looked at the documentation and also looked at the [`AngularCompilerPlugin`](https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack#options) documentation. It specifies that you can remove the `mainPath` and use `entryModule` in place of it.
This does make sense cosidering that's how it works using `ngc`. 

To test the viability of this, I created a brand new project, ran `ng eject --aot --force` and made [the following changes to the webpack config](https://github.com/kylecannon/entrymodule-aot-repro/commit/82cc8ee28a241fe3f60f3b66cfa2a690eca71a7a).

### Observed behavior
I saw that even though the build was successfully ran, using `yarn run build`, I found that there was [no template code generation happening](https://github.com/kylecannon/entrymodule-aot-repro/blob/dist-build-without-mainPath/dist/main.bundle.js).

### Desired behavior
I was expecting to get a bundle with AOTed code [excluding highlighted text because thats where the bootstrapping happens](https://github.com/kylecannon/entrymodule-aot-repro/blob/dist-build-with-mainPath/dist/main.bundle.js#L144-L167) 
that I can use to lazy load my applications in. Currently, if i run [ngc directly](https://github.com/kylecannon/entrymodule-aot-repro/tree/dist-build-with-ngc/out-tsc/app), I can successfully bootstrap the application into the page with webpack because it does the template code generation.

I am hoping that the `AngularCompilerPlugin` can support compilation without a `bootstrapModule` present in a "widget" like scenario. I think that this is an oversight on the `@ngtools/webpack` development because this is not a very common scenario.

After digging around in the codebase, I think this is the culprit because there is no fallback behavior for when `bootstrapModule` isn't present.

https://github.com/angular/angular-cli/blob/8ca3de7/packages/@ngtools/webpack/src/angular_compiler_plugin.ts#L690

**Comment by filipesilva** [comment]
@hansl is this something that we should support?

**Comment by kylecannon** [comment]
I would really hope that this is considered. From what I've been told by some angular team members, our application stack isn't out of the ordinary in an enterprise land (especially in applications where you can create pluggable widgets).

**Comment by hansl** [comment]
Have you tried `entryModule: null` in the options? If we don't find the entry module now we return null, instead of throwing an exception. Does this work with your use case?

We are adding library support in 6.0, so that should be fixed.

**Comment by kylecannon** [comment]
@hansl I still experience an empty bundle with the following:

```
    new AngularCompilerPlugin({
      "mainPath": "main.ts",
      "entryModule": null,
      "platform": 0,
      "hostReplacementPaths": {
        "environments/environment.ts": "environments/environment.ts"
      },
      "sourceMap": true,
      "tsConfigPath": "src/tsconfig.app.json",
      "compilerOptions": {}
    })
```

is that what you're referring to me trying?

**Comment by mgechev** [comment]
That's an old version of the CLI that we no longer support. If you still experience this issue with Angular CLI 8.2.2 and above, please open a new issue.
