### ISSUE TITLE
CSS comments are not removed from minified bundles.

### ISSUE THREAD

**Issue by coryrylan** [angular/angular-cli#9049]
### Versions
```
Angular CLI: 1.6.3
Node: 9.3.0
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.0
webpack: 3.10.0
```

### Repro steps

- CLI 1.6.1 css bundles removes comments. Update to 1.6.3 css bundles does not remove comments. 
My guess is this is a upstream issue with a dependency. I'm going to see if I can narrow down a isolated test using node sass.

![screenshot from 2017-12-31 14-36-43](https://user-images.githubusercontent.com/2021067/34464120-77756c28-ee38-11e7-8b01-2a1aad78fed0.png)

**Comment by clydin** [comment]
Confirmed this occurs with 1.6.3.  It does not happen on master which has improvements to the stylesheet optimization pipeline which will be in 1.7.

**Comment by coryrylan** [comment]
Looks like this was fixed in the latest 1.7 release of the CLI

**Comment by chrsmith** [comment]
@coryrylan I can confirm that single-line comments (`//`) are removed, but multi-line (`/* */`) are not. Is that expected? Should I open a new issue?

I'm seeing this on `1.7.3` of the CLI.

**Comment by adrianclaudiudima** [comment]
Still reproducing in 1.7.3 for multi-line. 
For now you can run your production build using --extract-css=false.
