### ISSUE TITLE
Error: dryRunSink.commit(...).ignoreElements(...).concat is not a function

### ISSUE THREAD

**Issue by rilwans** [angular/angular-cli#9194]
Just Upgraded to Angular CLI: 1.6.4

each time I run ng new I get this error

Error: dryRunSink.commit(...).ignoreElements(...).concat is not a function
dryRunSink.commit(...).ignoreElements(...).concat is not a function

**Comment by alexsapran** [comment]
same, just installed the cli and getting the same error.

**Comment by GeorgeDunee** [comment]
I am getting this error, too.

Angular CLI: 1.6.4
Node: 7.10.0
OS: linux x64
Angular: 
...

**Comment by j-c-levin** [comment]
Me too
Angular cli: 1.6.4
Node: 8.8.1
OS: Windows 10

**Comment by fhnaseer** [comment]
Same error,
Angular CLI: 1.6.4
Node: 8.9.4
OS: win32 x64

**Comment by nilsfriess** [comment]
Same Error:
Angular CLI: 1.6.4
Node: 9.4.0
OS: linux x64
npm --version: 5.6.0

**Comment by anankassis** [comment]
oh my god ! i am having the same problem ! 
in addition now ! i re down graded to my working version 1.5.3 , that was working all the time perfectly, and still ! i receive the same error ! nothing is fixing my problem !!! HELP NEEDED

**Comment by derobiom** [comment]
I can offer no help.  But I have deep sympathy as I see the same problem.

**Comment by mendhak** [comment]
Angular CLI: 1.6.4
Node: 8.9.4
OS: linux x64
Angular: 
...

npm --version 
5.6.0

I did try a `--verbose` flag when doing the `new` but nothing extra was shown

**Comment by nilsfriess** [comment]
https://github.com/angular/devkit/commit/e1f435606ffcf29b3311ab7204ef3eb84d661be2#diff-0dfbc02885bfb31a1e86e72520aad335

This is the commit in the `schematics.ts` file in the package `@angular-devkit/schematics` which is causing the problem

**Comment by nilsfriess** [comment]
See @maymarx answer in https://github.com/angular/devkit/issues/380:

adding
"@angular-devkit/schematics":"0.0.42", "@angular-devkit/core": "0.0.23", to the package.json fixes the problems if you need a quick fix before the weekend

**Comment by slick-k** [comment]
Same issue here too guys and gals!

**Comment by derobiom** [comment]
Adding
"@angular-devkit/schematics":"0.0.42", "@angular-devkit/core": "0.0.23", to the package.json (dev dependencies) worked for me also.

**Comment by anankassis** [comment]
how you add those things you talked about ?!
exactly ???
like what to add ?? just "":"0.0.42", "": "0.0.23" ???

**Comment by iamviswajith** [comment]
i have the same issue, after adding "@angular-devkit/schematics":"0.0.42", "@angular-devkit/core": "0.0.23", to the package.json, i uninstalled angular cli and re installed it, but the same issue pops up

**Comment by gurgelv** [comment]
they are dependencies which can be added to the package.json of your project, and no "":"0.0.42", "": "0.0.23" is not enough. you need the full dependency names:
`"@angular-devkit/schematics":"0.0.42", "@angular-devkit/core": "0.0.23"`

In my case, I had no project to add these dependencies to (creating a new one now), so I had to follow @eclanrs's solution at https://github.com/angular/devkit/issues/380:
```
npm i @angular-devkit/schematics@0.0.45 @angular/cli --no-save
```

**Comment by iamviswajith** [comment]
thanks @gurgelv that worked 👍

**Comment by ricartoons** [comment]
Thanks @gurgelv, works!

**Comment by anankassis** [comment]
That will make you able to create a new project correct !!
but try to do 
ng new component name
you will still get : Error: dryRunSink.commit(...).ignoreElements(...).concat is not a function
dryRunSink.commit(...).ignoreElements(...).concat is not a function

**Comment by IgorKharkiv** [comment]
Adding 
"@angular-devkit/schematics":"0.0.42", 
"@angular-devkit/core": "0.0.23" 
into devDependencies don't resolve problem in my case. The build still broken.

**Comment by LeezMito** [comment]
i have of same problem :C

**Comment by salimperwaiz** [comment]
I am also stuck with same error:
Angular CLI: 1.6.4
Node: 8.9.4
OS: win32 x64
Angular:

**Comment by tarah-s** [comment]
Great solution @gurgelv works perfect!

**Comment by casehill** [comment]
thank u! @gurgelv  it works fine!

**Comment by derobiom** [comment]
For some reason I had a earlier local version of the CLI?  Make sure you don't.  Mine seems to be working now (not getting this error) with the above additions to package.json BUT I think there may be other problems.  But I'm able to create components and modules.
Angular CLI: 1.6.4
Node: v8.9.1
OS: Win10 x64

**Comment by salimperwaiz** [comment]
Thank you @gurgelv  it works!

**Comment by anankassis** [comment]
I Needed to npm install , after adding those lines to the dev dependencies , and i think now it is working

**Comment by DiegoRodriguezTandil** [comment]
I have the same error: **_"Error: dryRunSink.commit(...)"_**
 - Node.js: v9.4.0
 - npm: 5.6.0
 - Angular CLI: 1.6.4

Maybe I would to reinstall Angular CLI 1.5

**Comment by cdCarlos** [comment]
The same problem here.

Node: 8.5
NPM: 5.3

ng-cli: 1.4.3
ng-cli: 1.5.3
ng-cli: 1.6.4

I've tried with the above cli's versions and is the same problem. For 1.4 and 1.5 cli version I can't create new components, with 1.6 version I can't create new projects.

**Comment by Metrophobe** [comment]
i don't get it ... was working fine just a while ago and then i got the dreaded error why is rolling back to an older version of the cli still producing the same error? tried 1.5.3

**Comment by Brocco** [comment]
There is a fix about to be released for this based upon PR angular/devkit#384

**Comment by Cosmin-Parvulescu** [comment]
@Metrophobe I think the issue is with the angular/devkit dependency, so even if you use lower releases of ng-cli you'll still get the faulty dependency.

**Comment by Metrophobe** [comment]
> @Metrophobe I think the issue is with the angular/devkit dependency, so even if you use lower releases of ng-cli you'll still get the faulty dependency.

so can we actually install an older angular/devkit and get back up and running ? the proposed solution previously further up is not working for me ... projects/ components not generating and am in the middle of some work! :(

**Comment by Metrophobe** [comment]
> There is a fix about to be released for this based upon PR angular/devkit#384

Many thanks for the effort! How do I apply this fix ?

**Comment by Brocco** [comment]
Working on getting it released to npm, so all you would need to do is reinstall.

**Comment by rilwans** [comment]
@Brocco Thanks

**Comment by Cosmin-Parvulescu** [comment]
@Brocco, does it fix the whole range of issues including the generator commands?

**Comment by DiegoRodriguezTandil** [comment]
@Brocco I reinstall angular-cli and the ng new is fixed but ng generate is still failing
Should I have to update anything else?
Node: 9.4.0
CLI: 1.6.4

**Comment by Cosmin-Parvulescu** [comment]
@DiegoRodriguezTandil, the fix is not on NPM yet, you can check it out on the [project page](https://www.npmjs.com/package/@angular-devkit/schematics)...

**Comment by gareththomasnz** [comment]
Oh boy - I guess there will be a fix by tomorrow

**Comment by Brocco** [comment]
@Cosmin-Parvulescu it will fix generate commands as well.

**Comment by Cosmin-Parvulescu** [comment]
The build seems to be up!

**Comment by Brocco** [comment]
FYI The updated version of @angular-devkit/schematics has been published, the correct version of that package should be `0.0.48`.

Closing this issue now, thank you for your patience and for following up on this issue!!! ❤️

**Comment by intellix** [comment]
Still getting this one myself:

```
$ ng g c player/inventory-form
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```

```
Angular CLI: 1.6.4
Node: 8.9.4
OS: darwin x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

I'm also using NX and am not sure if that changes anything. If it does then it might be helpful to list schematics when running `ng v`

**Comment by johnmikelridz** [comment]
@gurgelv Well played man!

**Comment by fmorriso** [comment]
Here are the steps that fixed this issue for an *existing* project that began to fail after upgrading to Angular-CLI 1.6.4:
1. create a new project using `ng new` in a different directory, such as c:\projects\aacli\
1. change to the root directory of the newly created project (e.g., c:\projects\aacli\)
1. perform a dry run to create a service, component, or module `ng generate service aatest --dry-run`
1. switch to the root directory of the failing project
1. make a copy of package.json in the failing project (e.g., package-backup.json)
1. compare the generated package.json file in the new project to the one used in the failing project.
1. carefully copy only the lines of "dependencies" that match by key from the new project (aacli\package.json) to the failing project.
1. copy *all* of the "devDependencies" portion of package.json from the new project to the failing project's equivalent "devDependencies".
1. rename package-lock.json in the failing project to package-lock.backup.
1. delete the node_modules directory in the failing project.
1. run `npm install` in the failing project.
1. perform a dry run to create a service, component, or module `ng generate service --dry-run`

The above sequence of steps worked for me on January 14, 2018 at approximately 8:15 AM EST.

After performing the above steps, when I ran `ng --version` in the (previously failing) project's top-level directory, it produced the following output:
```text
Angular CLI: 1.6.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.4
@angular/cli: 1.6.4
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

**Comment by byrondover** [comment]
I was getting the same issue as @intellix with an existing project. Purging lock files and `node_modules` worked for me.

```shell
rm -rf node_modules package-lock.json yarn.lock
yarn || npm install
```

Just a quick note for Hans and Mike: we know Schematics are work-in-progress (and super exciting!), but this isn't the first time they've affected the stability of Angular CLI core. Perhaps it's worth considering confining Schematics improvements to a non-critical path branch (e.g. 1.7.0) until they too are 1.0 ready. :bowtie:

**Comment by goldy-suryan** [comment]
npm i @angular-devkit/schematics@0.0.45 @angular/cli --no-save
worked for me,
thanks @gurgelv

**Comment by goldy-suryan** [comment]
`"@angular-devkit/schematics":"0.0.42", "@angular-devkit/core": "0.0.23"`
worked for me.
thanks @gurgelv

**Comment by gehreleth** [comment]
Installing @angular-devkit/schematics@0.0.48 solved this problem, I can generate new services and components now. But another annoying problem popped up instead:

@schematics/angular@0.1.13 requires a peer of @angular-devkit/schematics@0.0.46 but none was installed

**Comment by ltejoles** [comment]
I have the same issue as @gehreleth.  Not sure what to do here ...

**Comment by gehreleth** [comment]
Wait until  `@schematics/angular`'s dependency got updated to match `@angular-devkit/schematics@0.0.48`, I guess. It's not blocking, just outputs annoying warnings during build process.

**Comment by ltejoles** [comment]
I was able to make it work by downgrading the angular-cli to 1.32
"@angular/cli": "1.3.2",

**Comment by csmrkid** [comment]
by adding "@angular-devkit/schematics":"0.0.42", "@angular-devkit/core": "0.0.23" , then run "npm install" work for me

**Comment by nuriu** [comment]
@fmorriso steps worked for me (without dry run), thanks.

```
Angular CLI: 1.6.4 (e)
Node: 9.4.0
OS: linux x64
Angular: 5.2.0
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack-concat-plugin: 1.4.0
webpack-dev-server: 2.9.3
webpack: 3.8.1
```

**Comment by engemasa** [comment]
I'm currently working on a project that has existed for 6+ months. We encountered this issue with Angular CLI when our new developers attempted to set up their dev environments and run basic Angular CLI commands. I get the following error when we attempt to generate a component:

```bash
$ ng g c some-component
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```

So far the only thing that has worked was downgrading to `@angluar/cli` to v `1.3.2`. I also encountered an error regarding `rxjs` but that is resolved by upgrading `rxjs` to version `5.5.2`. Here is our package.json

```
"dependencies": {
    "@angular/animations": "4.4.3",
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@angular/platform-server": "4.4.3",
    "@angular/router": "4.4.3",
    "@types/lodash": "4.14.74",
    "angular2-csv": "0.2.5",
    "angular2-highcharts": "0.5.5",
    "core-js": "2.4.1",
    "lodash": "4.17.4",
    "ngx-bootstrap": "1.9.3",
    "rxjs": "5.1.0",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.4.4",
    "@angular/compiler-cli": "4.4.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.60",
    "codelyzer": "2.0.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "lite-server": "2.3.0",
    "protractor": "5.1.0",
    "ts-node": "2.0.0",
    "tslint": "4.5.0",
    "typescript": "2.2.0"
  }
```

Any help is greatly appreciated!

**Comment by ngochibamu** [comment]
npm install @angular-devkit/schematics@0.0.45 @angular/cli --no-save

This is the vodoo that worked!

**Comment by Deilan** [comment]
Nope, not fixed completely. Even after upgrading `@angular-devkit`s and purging `node_modules`, `package.lock.json` and `yarn.lock`.
```
$ ng generate service qwe
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```

```json
{
  "dependencies": {
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/forms": "5.0.1",
    "@angular/http": "5.0.1",
    "@angular/platform-browser": "5.0.1",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@angular/router": "5.0.1",
    "@angular/upgrade": "5.0.1",
    "@asymmetrik/ngx-leaflet": "^3.0.1",
    "bootstrap": "4.0.0-beta.2",
    "chart.js": "2.7.1",
    "core-js": "2.5.1",
    "font-awesome": "^4.7.0",
    "leaflet": "^1.3.0",
    "moment": "2.19.1",
    "ng2-charts": "1.6.0",
    "ngx-bootstrap": "1.9.3",
    "rxjs": "5.5.2",
    "simple-line-icons": "^2.4.1",
    "ts-helpers": "1.1.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular-devkit/core": "^0.0.25",
    "@angular-devkit/schematics": "^0.0.48",
    "@angular/cli": "^1.6.4",
    "@angular/compiler-cli": "5.0.1",
    "@types/jasmine": "2.6.3",
    "@types/leaflet": "^1.2.5",
    "@types/node": "8.0.50",
    "codelyzer": "4.0.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.2.0",
    "ts-node": "3.3.0",
    "tslint": "5.8.0",
    "typescript": "2.6.1"
  }
}
```

**Comment by yuveliremil** [comment]
working perfectly with following :

"dependencies": {
    "@angular/animations": "5.2.0",
    "@angular/common": "5.2.0",
    "@angular/compiler": "5.2.0",
    "@angular/core": "5.2.0",
    "@angular/forms": "5.2.0",
    "@angular/http": "5.2.0",
    "@angular/platform-browser": "5.2.0",
    "@angular/platform-browser-dynamic": "5.2.0",
    "@angular/router": "5.2.0",
    "bootstrap": "4.0.0-beta.2",
    "core-js": "2.5.3",
    "font-awesome": "4.7.0",
    "intl": "1.2.5",
    "jquery": "3.2.1",
    "ngx-perfect-scrollbar": "5.2.0",
    "popper.js": "1.12.9",
    "rxjs": "5.5.6",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.4",
    "@angular/compiler-cli": "5.2.0",
    "@angular/language-service": "5.2.0",
    "@types/jasmine": "2.8.4",
    "@types/node": "9.3.0",
    "codelyzer": "4.0.2",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.3",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.2.2",
    "ts-node": "3.3.0",
    "tslib": "1.8.1",
    "tslint": "5.9.1",
    "typescript": "2.4.2"
  }

**Comment by Wael3bbas** [comment]
It works for me on 
Angular CLI: 1.6.4
Node: 6.10.3
the common thing I can see on users had this issue is node version greater than 8 or less than 6.9

**Comment by CisSasGot** [comment]
I have the same problem and installing these libraries
```
    "@angular-devkit/build-optimizer": "^0.0.38",
    "@angular-devkit/core": "^0.0.25",
    "@angular-devkit/schematics": "^0.0.48",
```
 does not help, someone has already found a bug-fix?

**Comment by hugocaldeira** [comment]
Solved!
Add to package.json inside devDependencies
```
"@angular-devkit/schematics": "0.0.43",
"@angular-devkit/core": "0.0.23"
```
Save file
`npm install`

**Comment by Dok11** [comment]
@hugocaldeira I dont think. This way did not help me.

**Comment by Wael3bbas** [comment]
Also, this works for me 

npm i @angular-devkit/schematics@0.0.45 @angular/cli --no-save

**Comment by abalazsics** [comment]
@mendhak's solution worked for me
Angular CLI: 1.6.2
Node: 9.3.0
OS: darwin x64

**Comment by onedotover** [comment]
I just upgraded Angular CLI and ran into this issue generating components. I noticed I didn't get this issue when I created a new project.

The fix for me was to remove the **node_modules** folder and **package-lock.json**. Then re-install node modules using `npm install`

Angular CLI: 1.6.5
Node: 8.7.0
OS: darwin x64

```
package.json
{
  "name": "whatsnew",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.5",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

**Comment by ssokurenko** [comment]
That helped me:

- Removed `node_modules` and re-installed by `npm install`
- Installed `npm i --save-dev @angular-devkit/core`

**Comment by foote-Greg** [comment]
@ssokurenko solution worked for me after the other solutions failed to work....

**Comment by intellix** [comment]
same thing for me on 1.6.5 it seems

**Comment by chandurams** [comment]
Thanks @gurgelv its working.

**Comment by morismael** [comment]
Thanks @ssokurenko . Your solution worked for me!

**Comment by Siafu** [comment]
Why is this issue closed? I can't seem to get rid of it at all.

**Comment by topikus** [comment]
Thanks @ssokurenko . Your solution worked for me (CLI 1.6.5)!

**Comment by markus-heinisch** [comment]
Sorry, still get same error! 
I have deleted my node_modules folder and reinstalled my dependencies.
What can I do now?
Thanks, Markus

My environment:
Angular CLI: 1.6.5
Node: 6.9.1
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0

**Comment by Justin-MacIntosh** [comment]
The workaround in the commit by @jgarciao was the only thing that worked for me.

**Comment by marc101101** [comment]
still same problem. Tried @jgarciao 's solution - not working for me :(
```
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```

**Comment by kanafghan** [comment]
I'm also facing this issue with the following configuration:

```
Angular CLI: 1.6.5
Node: 6.11.2
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0
```

However, the following is working on another project on the same machine:

```
Angular CLI: 1.5.0
Node: 6.11.2
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.1.0
```

My global CLI version is 1.6.5

None of the solutions mentioned above are working for me.

Shouldn't this issue be opened again?

**Comment by Justin-MacIntosh** [comment]
@marc101101 Did you delete the node-modules folder, and npm install after making the fix in the commit?

**Comment by kchiragowni** [comment]
@Justin-MacIntosh deleting node_modules and ran npm install fixed my issue. Thanks

**Comment by ghego1** [comment]
The solution suggested by @jgarciao does not work for me, even after deleting all node modules. I also tried installing globally the packages, but still getting the same error. Any idea?

**Comment by Dok11** [comment]
@ghego1 check versions of your packages

**Comment by ghego1** [comment]
@Dok11  Yes checked, they all seem in line with those suggested by @jgarciao:

```
"dependencies": {
    "@angular-devkit/schematics": "0.0.51",
    "@angular-devkit/core": "0.0.28",
    "@angular-redux/store": "^7.0.2",
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.0.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/flex-layout": "2.0.0-beta.12",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.0.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@nguniversal/express-engine": "^5.0.0-beta.5",
    "@ngx-cache/core": "^5.0.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.1",
    "@ngx-universal/translate-loader": "^5.0.0",
    "@types/lodash": "^4.14.92",
    "core-js": "^2.5.3",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.4",
    "ngx-cookie-service": "^1.0.10",
    "q": "^1.5.0",
    "redux": "^3.7.2",
    "rxjs": "^5.5.6",
    "spider-detector": "^1.0.18",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.5",
    "@angular/compiler-cli": "^5.2.1",
    "@angular/language-service": "^5.2.1",
    "@types/jasmine": "~2.8.4",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~9.3.0",
    "angular-tslint-rules": "^1.1.0",
    "codelyzer": "~4.0.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.3",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.2.2",
    "ts-loader": "^3.2.0",
    "ts-node": "~4.1.0",
    "tslint": "^5.9.1",
    "typescript": ">=2.4.2 <2.6.0",
    "webpack-node-externals": "^1.6.0"
  }
```

**Comment by MartinNuc** [comment]
Deleting `yarn.lock` and running `yarn install` again helped me.

**Comment by ghego1** [comment]
@MartinNuc right! So the trick when using `yarn` is to first update `package.json` as described by @jgarciao, delete `yarn.lock`, and then run `yarn install`.

**Comment by MartinNuc** [comment]
I think there is some locked dependency in the `.lock` file (regardless of `yarn.lock` or `package-lock.json`). By deleting lock file you let dependency manager install a proper version.

**Comment by FreezeSoul** [comment]
same error, thk for up

**Comment by glebmachine** [comment]
I have fixed by install proper rxjs version:
`yarn add rxjs@5.5.2`

**Comment by olufemioyedepo** [comment]
@mendhak solution worked for me!

**Comment by RonakR** [comment]
I have the proper rxjs version `(5.5.2)` and I still see the same error. 
```Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function```

**Comment by markus-heinisch** [comment]
Hi, has someone tried to solve the problem with angular-cli v1.7.0-beta.1?
I'm referring to:
```
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function
```

**Comment by andreimcristof** [comment]
have the exact same issue right now when using `ng generate component`

**Comment by olufemioyedepo** [comment]
@andreimcristof try this
npm install @angular-devkit/schematics@0.0.45 @angular/cli --no-save

**Comment by yogibimbi** [comment]
seems updating to
```
"@angular-devkit/schematics":"0.0.51",
"@angular-devkit/core": "0.0.28",

```and deleting node_modules + npm install might have done the trick for me. But I also updated some other versions of ng libraries that were warned about after previous installs, so I can't say with absolute certainty that the above two lines are what pushed it over the top.
So, at least `ng g service bla` now works.

**Comment by NickToony** [comment]
Also experiencing this issue, tried various fixes suggested here. I don't think this issue should be closed.

Error:

`ng g component name
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function`

And version info:

`Angular CLI: 1.6.5
Node: 9.2.0
OS: darwin x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.2
webpack: 3.10.0`

**Comment by titusfx** [comment]
@mendhak solution didn't work for me. I got a new one after that:

> Error: Path "/app/app.module.ts" does not exist.
> Path "/app/app.module.ts" does not exist.

I don't think this issue should be closed.

**Comment by jorgeso** [comment]
I've tried every single solution offered here and nothing works. This is ridiculous.

**Comment by glebmachine** [comment]
Try using this:
```
yarn add --dev @angular-devkit/core@^0.0.28
yarn add rxjs@^5.5.2
rm -rf yarn.lock; rm -rf node_modules;
yarn;
```

This error cause in angular-devkit/core. There was undefined observable
method.
Yesterday it was take me about 3 hours to investigate and fix that. I hope
it will help

**Comment by markus-heinisch** [comment]
I have found a solution for my project: I have deleted my `node_modules` folder, checked my `package.json` and installed my dependencies in several steps:

1.  Angular dependencies and devDependencies (all the dependencies which come with  `ng new app`)
2. Material deps
3. all other dependencies

Here is my package.json
`"dependencies": {
    "@angular/animations": "~5.2.2",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "~5.2.2",
    "@angular/compiler": "~5.2.2",
    "@angular/core": "~5.2.2",
    "@angular/flex-layout": "2.0.0-beta.12",
    "@angular/forms": "~5.2.2",
    "@angular/http": "~5.2.2",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "~5.2.2",
    "@angular/platform-browser-dynamic": "~5.2.2",
    "@angular/router": "~5.2.2",
    "classlist.js": "1.1.20150312",
    "core-js": "2.5.3",
    "hammerjs": "2.0.8",
    "intl": "1.2.5",
    "moment": "2.20.1",
    "moment-business": "3.0.1",
    "parse-decimal-number": "1.0.0",
    "rxjs": "^5.5.6",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.5",
    "@angular/compiler-cli": "~5.2.2",
    "@angular/language-service": "~5.2.2",
    "@types/jasmine": "2.5.38",
    "@types/node": "6.0.96",
    "codelyzer": "4.1.0",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "replace-in-file": "2.6.4",
    "sass-lint": "1.10.2",
    "ts-node": "3.2.2",
    "tslint": "5.7.0",
    "typescript": "2.4.2"
  }`

**Comment by splincode** [comment]
Not working

```
mivanov@9TDQH5J MINGW64 /c/Develop/rosnfo-ui/rosnfo-ui/src/app/test (hotfix/RSBNFO-302/sms-product-bugfix)
$ ng g c Test
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function

mivanov@9TDQH5J MINGW64 /c/Develop/rosnfo-ui/rosnfo-ui/src/app/test (hotfix/RSBNFO-302/sms-product-bugfix)
$ ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.5
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.2
webpack: 3.10.0

```

**Comment by roddy** [comment]
This was closed as no longer an issue, but I just installed @angular/cli (using `npm install -g @angular/cli@latest`) and cannot create a new app. I don't have a project, so I cannot do an "npm install" on the fixed @angular/devkit. Is 1.6.5 still pulling in the old dependency?

```
C:\workspace>ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.5
Node: 6.11.1
OS: win32 x64
Angular:
...

C:\workspace>ng new test
Error: dryRunSink.commit(...).ignoreElements is not a function
dryRunSink.commit(...).ignoreElements is not a function

C:\workspace>npm list -g --depth=1
C:\Users\me\AppData\Roaming\npm
+-- @angular/cli@1.6.5
| +-- @angular-devkit/build-optimizer@0.0.42
| +-- @angular-devkit/core@0.0.29
| +-- @angular-devkit/schematics@0.0.52
| +-- @ngtools/json-schema@1.1.0
| +-- @ngtools/webpack@1.9.5
| +-- @schematics/angular@0.1.17
| +-- autoprefixer@7.2.5
| +-- chalk@2.2.2
| +-- circular-dependency-plugin@4.2.1
| +-- common-tags@1.5.1
| +-- copy-webpack-plugin@4.2.3
| +-- core-object@3.1.5
| +-- css-loader@0.28.7
| +-- cssnano@3.10.0
| +-- denodeify@1.2.1
| +-- ember-cli-string-utils@1.1.0
| +-- exports-loader@0.6.4
| +-- extract-text-webpack-plugin@3.0.2
| +-- file-loader@1.1.5
| +-- fs-extra@4.0.2
| +-- glob@7.1.2
| +-- html-webpack-plugin@2.30.1
| +-- istanbul-instrumenter-loader@3.0.0
| +-- karma-source-map-support@1.2.0
| +-- less@2.7.3
| +-- less-loader@4.0.5
| +-- license-webpack-plugin@1.1.1
| +-- loader-utils@1.1.0
| +-- lodash@4.17.4
| +-- memory-fs@0.4.1
| +-- minimatch@3.0.4
| +-- node-modules-path@1.0.1
| +-- node-sass@4.7.2
| +-- nopt@4.0.1
| +-- opn@5.1.0
| +-- portfinder@1.0.13
| +-- postcss-import@11.0.0
| +-- postcss-loader@2.0.10
| +-- postcss-url@7.3.0
| +-- raw-loader@0.5.1
| +-- resolve@1.5.0
| +-- rxjs@5.5.3
| +-- sass-loader@6.0.6
| +-- semver@5.4.1
| +-- silent-error@1.1.0
| +-- source-map-loader@0.2.3
| +-- source-map-support@0.4.18
| +-- style-loader@0.13.2
| +-- stylus@0.54.5
| +-- stylus-loader@3.0.1
| +-- uglifyjs-webpack-plugin@1.1.6
| +-- url-loader@0.6.2
| +-- webpack@3.10.0
| +-- webpack-dev-middleware@1.12.2
| +-- webpack-dev-server@2.11.1
| +-- webpack-merge@4.1.1
| +-- webpack-sources@1.1.0
| `-- webpack-subresource-integrity@1.0.2
`-- npm-check-updates@2.13.0
  +-- bluebird@3.5.1
  +-- chalk@1.1.3
  +-- cint@8.2.1
  +-- cli-table@0.3.1
  +-- commander@2.12.2
  +-- fast-diff@1.1.2
  +-- find-up@1.1.2
  +-- get-stdin@5.0.1
  +-- json-parse-helpfulerror@1.0.3
  +-- lodash@4.17.4
  +-- node-alias@1.0.4
  +-- npm@3.10.10
  +-- npmi@2.0.1
  +-- semver@5.4.1
  +-- semver-utils@1.1.1
  +-- snyk@1.53.0
  +-- spawn-please@0.3.0
  `-- update-notifier@2.3.0
```

**Comment by larssn** [comment]
Please reopen, still an issue

**Comment by Brocco** [comment]
We the "CLI Team" would like to apologize for the confusion.

### Status
This issue has been resolved in version `1.6.6`.

### Updating
The steps to update your environment to the latest version containing the fix:
```bash
npm uninstall -g @angular/cli
npm cache clean
# if npm version is > 5 then use `npm cache verify` to avoid errors (or to avoid using --force)
npm install -g @angular/cli@latest

rm -rf node_modules dist # use rmdir /S/Q node_modules dist in Windows Command Prompt; use rm -r -fo node_modules,dist in Windows PowerShell
npm install --save-dev @angular/cli@latest
npm install
```

### Explanation
The issue of `[rxjs operator] is not a function` is a result of the migration of the devkit repo to using "pipeable" (formerly "lettable") operators instead of the prototype patching approach that the Angular CLI was using prior to release `1.6.6` (which was just released). The commit which fixed it is [here](https://github.com/angular/angular-cli/commit/5a736bd90b69d86b77b7ef1ba2a71b76ad4e7d21).

The issue is that the CLI was using operators that were not imported and relied on them being on the Observable object. When the devkit was updated it removed this function and the bug in the CLI was exposed. The latest version of the CLI is now using pipeable operators and therefore importing all of the operators needed to work with observables, so this issue has been resolved.

Thank you for your patience and for contributing by reporting this issue.

**Comment by splincode** [comment]
I have done these operations

```
npm uninstall -g @angular/cli
npm cache clean
# if npm version is > 5 then use `npm cache verify` to avoid errors (or to avoid using --force)
npm install -g @angular/cli@latest

rm -rf node_modules dist # use rmdir /S/Q node_modules dist in Windows Command Prompt; use rm -r -fo node_modules,dist in Windows PowerShell
npm install --save-dev @angular/cli@latest
npm install
```

But I have `Cannot find module '@angular-devkit/core'`

```
mivanov@9TDQH5J MINGW64 /c/Develop/rosnfo-ui/rosnfo-ui/src/app/test (hotfix/RSBNFO-302/sms-product-bugfix)
$ npm run ng -- -v

> rosnfo-ui-app@0.0.0 ng C:\Develop\rosnfo-ui\rosnfo-ui
> ng "-v"


    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.6
Node: 8.9.1
OS: win32 x64
Angular: error
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, material, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: error
@angular-devkit/schematics: error
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: error
webpack-bundle-analyzer: error
webpack: 3.10.0

mivanov@9TDQH5J MINGW64 /c/Develop/rosnfo-ui/rosnfo-ui/src/app/test (hotfix/RSBNFO-302/sms-product-bugfix)
$ npm run ng -- g c Test

> rosnfo-ui-app@0.0.0 ng C:\Develop\rosnfo-ui\rosnfo-ui
> ng "g" "c" "Test"

Cannot find module '@angular-devkit/core'
Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Develop\rosnfo-ui\rosnfo-ui\node_modules\@schematics\angular\component\index.js:10:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rosnfo-ui-app@0.0.0 ng: `ng "g" "c" "Test"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rosnfo-ui-app@0.0.0 ng script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mivanov\AppData\Roaming\npm-cache\_logs\2018-01-26T08_09_20_766Z-debug.log
```

**Comment by splincode** [comment]
@Brocco Thank you, it is worked))

**Comment by mhmo91** [comment]
@Brocco 
We -The Developers- understand the complexity of such technology n we love n appreciate all of ur efforts BUT please take into consideration testing whatever new build before pushing, as a bug blocks n wastes thousands of hours of angular lovers, thanks for understanding, cheers!

**Comment by LunoDaniel** [comment]
Thank you @gurgelv, that's works fine for me.

**Comment by uloga** [comment]
Sorry but this is the most unreliable framework at the moment, too bad I chose it for our project now we have to waste more money and time migrating everything to a more reliable framework!

**Comment by CarMoreno** [comment]
@gurgelv You're a Rockstar!, thank you

**Comment by nyoman** [comment]
I had the same problem.
But this (npm install @angular-devkit/schematics@0.0.45 @angular/cli --no-save) solved my problem.

My big thanks go to Mendhak.

**Comment by Sharkesm** [comment]
I had the same problem but not quite sure if it might work for the rest of you guys, but essentially i deleted node_module folder then uninstalled @angular/cli and re-install it once again but with higher version and finally updated the current node.

**Comment by Herotko** [comment]
I was helped
    "@angular-devkit/core": "^0.6.8",
    "@angular-devkit/schematics": "^0.6.8",
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^5.1.1",

**Comment by zshlomyz** [comment]
> We the "CLI Team" would like to apologize for the confusion.
> 
> ### Status
> This issue has been resolved in version `1.6.6`.
> 
> ### Updating
> The steps to update your environment to the latest version containing the fix:
> 
> ```shell
> npm uninstall -g @angular/cli
> npm cache clean
> # if npm version is > 5 then use `npm cache verify` to avoid errors (or to avoid using --force)
> npm install -g @angular/cli@latest
> 
> rm -rf node_modules dist # use rmdir /S/Q node_modules dist in Windows Command Prompt; use rm -r -fo node_modules,dist in Windows PowerShell
> npm install --save-dev @angular/cli@latest
> npm install
> ```
> 
> ### Explanation
> The issue of `[rxjs operator] is not a function` is a result of the migration of the devkit repo to using "pipeable" (formerly "lettable") operators instead of the prototype patching approach that the Angular CLI was using prior to release `1.6.6` (which was just released). The commit which fixed it is [here](https://github.com/angular/angular-cli/commit/5a736bd90b69d86b77b7ef1ba2a71b76ad4e7d21).
> 
> The issue is that the CLI was using operators that were not imported and relied on them being on the Observable object. When the devkit was updated it removed this function and the bug in the CLI was exposed. The latest version of the CLI is now using pipeable operators and therefore importing all of the operators needed to work with observables, so this issue has been resolved.
> 
> Thank you for your patience and for contributing by reporting this issue.

Hi, The suggested version 1.6.6 is compatible with Angular 5? If no, there is a different version that is compatible & work properly?
Regards
