### ISSUE TITLE
Dev server syntax error in IE11

### ISSUE THREAD

**Issue by tmakin** [angular/angular-cli#9293]
### Versions
Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.1
Internet Explorer: 11

Which pulls in:
webpack-dev-server: 2.11.0

### Repro steps
```
$ng new app
$cd app
$npm start
```
Navigate to `http://localhost:4200` using IE11

### Observed behavior
IE11 reports syntax error in console:
```
SCRIPT1002: Syntax error
vendor.bundle.js (43208,21)
```

The AOT production build is fine. Just the dev server which is a problem

### Desired behavior
Be able to use dev server with IE11

### Mention any other details that might be useful (optional)
The cause seems to be fat arrow es6 syntax that has sneaked into the webpack-dev-server output. See here:
https://github.com/webpack/webpack-dev-server/issues/1278

So probably this will be fixed with the next update to webpack-dev-server

**Comment by surensubhu** [comment]
I am also facing the same issue.

**Comment by ciesielskico** [comment]
Also having this issue

**Comment by tmakin** [comment]
This is now fixed. Just rerun `npm install` and check you have picked up webpack-dev-server 2.11.1. 
```
$npm info webpack-dev-server version
2.11.1
```

**Comment by surensubhu** [comment]
@tmakin  it worked..thanks!!

**Comment by ayush987goyal** [comment]
Still facing the issue even after webpack-dev-server@2.11.1 in IE11

**Comment by tmakin** [comment]
Looks like the fix was to downgrade strip-ansi to version `^3.0.0`, so I would check what version you have installed. Maybe a clean npm install would help.
https://github.com/webpack/webpack-dev-server/commit/b78e249c7953f4a7676ec0f32990777edf45c01e

**Comment by ayush987goyal** [comment]
I did a clean npm install by removing node_modules. Still facing the issue while in development mode. It works fine with prod build.

**Comment by tmakin** [comment]
Must still be picking up wrong version. I suggest manual install of webpack-dev-server or add an explicit dependency on `2.11.1` in your package json.
```
"webpack-dev-server": "^2.11.1"
```

Either way, IE is not going to work until the following command returns ^3.0.0
```
$npm info webpack-dev-server dependencies.strip-ansi
^3.0.0
```

**Comment by ayush987goyal** [comment]
The above commands returns ```^3.0.0``` but I am still having trouble. I have opened a issue for the same [#9310](https://github.com/angular/angular-cli/issues/9310)
